### ISSUE TITLE
pip version different from git

### ISSUE THREAD

**Issue by liviobait** [jonathanslenders/python-prompt-toolkit#104]
Hello
I installed python-prompt-toolkit with pip on python 2.7.6.1. I suppose is a different version of master github, because the file shortcurts.py use history_filename and not history attribute.
And a this point the example sqlite-cli do not work.
I have another strage issue, SqlLexer do not exist, I have only Sql.

**Comment by jonathanslenders** [comment]
Hi @liviobait,

I'm aware that the lastest master commit is ahead of the latest Pypi release. The commit on Pypi is this one: https://github.com/jonathanslenders/python-prompt-toolkit/commit/7cab47cc3aaf4b7720f90416b6f206f8ac14d3ff

About SqlLexer, what version of Pygments do you have? Maybe something was changed there?
Thanks for reporting in any case! I appreciate it.

**Comment by liviobait** [comment]
I have the version of pypi for python 2.7.6.1
