### ISSUE TITLE
Home & End keys

### ISSUE THREAD

**Issue by krisztianfekete** [jonathanslenders/python-prompt-toolkit#106]
I have just found out about ptpython and how nice its multi-line support is.

Except, that my expectations of the Home and End keys are different: I expect them to move the cursor to the beginning/end of line respectively.  What happens instead is to move the cursor to the beginning/end of the buffer, which moves the cursor far away from the point I want it to go.

https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/basic.py#L97

**Comment by jonathanslenders** [comment]
Hi @krisztianfekete , thank you for the feedback! That's easy to fix. I will probably do that.

**Comment by krisztianfekete** [comment]
Hi @jonathanslenders , I see you have already implemented it in 7a4bf4fe1137b9a1bf0fae5c4dc9e43966ab81f7.  Thanks!

**Comment by jonathanslenders** [comment]
Yes, I implemented this yesterday. Hopefully, I'll be able to do a new release on Pypi soon.
