### ISSUE TITLE
ASCII color codes in prompt

### ISSUE THREAD

**Issue by anula** [jonathanslenders/python-prompt-toolkit#109]
Let's say I want to have colorful prompt. I guess I can achieve it somehow using Pygments's styles, but first idea would be to use ASCII color codes. So if I wanted a red "hello>":
` prompt = '\001\033[0;31m\002hello>'`
And now, indeed, printing prompt like that:
`print(prompt)`
Yields expected result. But call to `get_input`: 
`answer = get_input(prompt)`
Prints: 
"^A^[[0;31m^Bhello>"

Is that behavior expected? Is there a workaround for this?

**Comment by jonathanslenders** [comment]
Hi @anula,

Sorry for the late reply.
Right now it is possible. Have a look at this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/colored-prompt.py

The reason that defining ANSI colors doesn't work is that the library is terminal agnostic. That means, applications using it should work on Windows as well and windows doesn't know about these escape codes.

Is this what you need?

![image](https://cloud.githubusercontent.com/assets/216638/7901308/675cc872-0781-11e5-8c28-137b27022500.png)

**Comment by jonathanslenders** [comment]
It's released on Pypi.
Cheers,
Jonathan

**Comment by jonathanslenders** [comment]
It's released on Pypi.
Cheers,
Jonathan
