### ISSUE TITLE
[feature request] use IPython zmq-interface

### ISSUE THREAD

**Issue by Carreau** [jonathanslenders/python-prompt-toolkit#12]
First super awesome project. 

Looking at ipython integration I suppose it would be possible to use the two-process console that uses zmq in contrib/ipython.py It would have the nice addition of beeing able to use this with all the kernels [supported by IPython](https://github.com/ipython/ipython/wiki/Projects-using-IPython), [bipython](https://github.com/ivanov/bipython) is using a similar approach. 

I might take a shot at that later.

**Comment by jonathanslenders** [comment]
(I guess this is not relevant anymore.)
