### ISSUE TITLE
Some files needs to be updated 

### ISSUE THREAD

**Issue by fbenmena** [jonathanslenders/python-prompt-toolkit#121]
Since some recent changes invloving `KeyBindingManager` the awesome `layout.py` example
doesn't run anymore.

Hope this helps.
Regards

**Comment by jonathanslenders** [comment]
Thanks for pointing out @fbenmena! 

Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/0c08f2c0c8d8aa8232382787493979ce1086af2c

While going forward, I should have missed that example.
Cheers,
Jonathan
