### ISSUE TITLE
REPL tutorial fails in Python 2.7

### ISSUE THREAD

**Issue by lillian27** [jonathanslenders/python-prompt-toolkit#123]
Code provided for initial step in REPL tutorial fails in Python 2.7 (clean virtualenv, only prompt_toolkit and deps installed):

```python
from prompt_toolkit.shortcuts import get_input

def main():
    text = get_input("> ")
    print('You entered:', text)

if __name__ == '__main__':
    main()
```

>File "/Users/lillian/Documents/Projects/st_p2x/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 266, in get_input
    application=create_default_application(message, **kwargs),
  File "/Users/lillian/Documents/Projects/st_p2x/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 239, in create_default_application
    extra_input_processors=extra_input_processors),
  File "/Users/lillian/Documents/Projects/st_p2x/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 122, in create_default_layout
    assert isinstance(message, text_type)
AssertionError
>

This same code works as advertised in Python 3.4

**Comment by jonathanslenders** [comment]
Hi @blueyed,

Thanks for reporting! The problem was the missing``from __future__ import unicode_literals`` import.
I fixed it in the tutorial.

Jonathan

**Comment by bmer** [comment]
Hi @jonathanslenders -- this also needs to be changed in the "Getting Started" section in README.rst
