### ISSUE TITLE
Add tests to release tarball

### ISSUE THREAD

**Issue by jlec** [jonathanslenders/python-prompt-toolkit#126]
Could the test be added to the release tarball, so that OS package maintainers could test in the end environment of the distribution?

**Comment by jonathanslenders** [comment]
Hi @jlec,

We can do that, yes. I just checked and Django for instance is doing it as well.
What is the best approach? Do I have to change something to the ``setup.py``?

One remark though. Right now, the tests are not covering everything. They do save me from time to time, but I need to put some more effort in it to get a better coverage. (I'm not targeting full coverage, but a few parts are very good testable.)

Jonathan

**Comment by jlec** [comment]
Hi @jonathanslenders,

You only need to make sure in setup.py that the test don't get installed. There is some exclude list for such things.

We are trying to do test with all packages. This helps us to trigger down incompatibilities with dependencies and in situations where our installations might differ from what upstream tested.

It would be great if you could do the same for ptpython, too.

Thanks Justin

**Comment by jonathanslenders** [comment]
I believe tests were included some time ago. See the MANIFEST.in.
