### ISSUE TITLE
vi mode example assertion error

### ISSUE THREAD

**Issue by Aluriak** [jonathanslenders/python-prompt-toolkit#128]
When launch Python3 on [vi_mode example](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/get-input-vi-mode.py), the following stack trace is generated :

    You have Vi keybindings here. Press [Esc] to go to navigation mode.
    Traceback (most recent call last):
      File "p.py", line 8, in <module>
        answer = get_input('Give me some input: ', multiline=False, vi_mode=True)
      File "/usr/lib/python3.4/site-packages/prompt_toolkit/shortcuts.py", line 266, in get_input
        application=create_default_application(message, **kwargs),
      File "/usr/lib/python3.4/site-packages/prompt_toolkit/shortcuts.py", line 229, in create_default_application
        enable_open_in_editor=enable_open_in_editor).registry
      File "/usr/lib/python3.4/site-packages/prompt_toolkit/key_binding/manager.py", line 44, in __init__
        assert isinstance(enable_vi_mode, CLIFilter)
    AssertionError

**Comment by jonathanslenders** [comment]
Hi @Aluriak,

Thanks for pointing this out. That's a bug.

The patch below could fix it. I will check tomorrow whether I missed something and if not apply it.

```diff
diff --git a/examples/get-input-vi-mode.py b/examples/get-input-vi-mode.py
index 610548f..05c5b12 100755
--- a/examples/get-input-vi-mode.py
+++ b/examples/get-input-vi-mode.py
@@ -1,9 +1,10 @@
 #!/usr/bin/env python
 from __future__ import unicode_literals
 from prompt_toolkit.shortcuts import get_input
+from prompt_toolkit.filters import Always
 
 
 if __name__ == '__main__':
     print("You have Vi keybindings here. Press [Esc] to go to navigation mode.")
-    answer = get_input('Give me some input: ', multiline=False, vi_mode=True)
+    answer = get_input('Give me some input: ', multiline=False, vi_mode=Always())
     print('You said: %s' % answer)
```

**Comment by jonathanslenders** [comment]
Fixed: https://github.com/jonathanslenders/python-prompt-toolkit/commit/c7b38d3f54b05f30d13e56f7cce8b3d2cf801463

Thanks!
