### ISSUE TITLE
Control-T Emacs keybinding swaps wrong characters

### ISSUE THREAD

**Issue by brenns10** [jonathanslenders/python-prompt-toolkit#129]
In Emacs, the shortcut `C-t` (`transpose-chars`) does the following things:

- Swap the character under point with the character before it.
- Move point one character to the right.

(The only exception here is when point is at the end of the line, in which case it swaps the *two characters to the left of point*, and keeps point where it is).

So, if you had "a**b**c" in a buffer (bold represents point), then after doing `C-t`, you would have "ba**c**".

The keybinding in `prompt_toolkit` always swaps the two characters to the left of point, and doesn't move it.  It seems silly, but the transpose shortcut can be a ridiculously useful one, and when the semantics are just a bit off like this, it can really mess you up!  It would be nice if `C-t` behaved the same as Emacs.  Is this something that you'd feel comfortable changing, or is it implemented that way for a reason?

I see that the ControlT binding is implemented in `prompt_toolkit.key_bindings.bindings.basic` and not overridden in `prompt_toolkit.key_bindings.bindings.emacs`.  I could probably implement the expected behavior and submit a PR, but I wanted to figure out if you'd be open to such a change before spending time on it.

(Also, *great* work on this module!  I use it daily as a replacement for the default REPLs, and it blows them away!  I really appreciate the work.)

**Comment by jonathanslenders** [comment]
Hi @brenns10,

Thanks a lot for pointing this out!
I wasn't aware of it (that's a shortcut a barely use myself) but it's clearly a bug. 

If you like to, feel free to submit a pull request and I'll merge it. (Please fix in ``key_bindings.bindings.basic``.)

Cheers and thanks for the complement,
Jonathan
