### ISSUE TITLE
create_default_application() got an unexpected keyword argument 'patch_stdout'

### ISSUE THREAD

**Issue by Aluriak** [jonathanslenders/python-prompt-toolkit#135]
When launching python3 or python2 on the example test [patch_stdout](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/patch-stdout.py), the error **create_default_application() got an unexpected keyword argument 'patch_stdout'** is raised:

    i=1
    Traceback (most recent call last):
      File "p.py", line 31, in <module>
        main()
      File "p.py", line 25, in main
        result = get_input('Say something: ', patch_stdout=True)
      File "/udd/lbourneu/.local/lib/python3.4/site-packages/prompt_toolkit/shortcuts.py", line 283, in get_input
        application=create_default_application(message, **kwargs),
    TypeError: create_default_application() got an unexpected keyword argument 'patch_stdout'
    i=2

**Comment by jonathanslenders** [comment]
Hi @Aluriak,
This should be fixed now. It was implemented in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/ce91011f23d33a1ebce8a515df6a3f6d586fdeb3

It should work with the latest Pypi release of today. Feel free to reopen the ticket if it still doesn't work.

Jonathan
