### ISSUE TITLE
Colors in Windows

### ISSUE THREAD

**Issue by darikg** [jonathanslenders/python-prompt-toolkit#137]
It looks like win32_output.py maps all colors to the closest color in a 16-color table. ConEmu supports ANSI color codes. Is it possible to detect which console is being used and only fall back to 16-bit color if necessary?

**Comment by jonathanslenders** [comment]
That should be possible. ConEmu sets the ``ConEmuANSI`` environment variable when it has ANSI colors enabled. I guess it should be easy to switch to 256 colors in that case. I'll have a look. Thanks for the suggestion!

**Comment by jonathanslenders** [comment]
It should work now: https://github.com/jonathanslenders/python-prompt-toolkit/commit/17b8a3a08fcd26dcaa9c917dafd32552f8612b2a

However, for some reason ConEmu only supports 256 colors in the "bottom region". So you have to print ``print('\x1b[9999;1H')`` to make it scroll to the bottom first. (I don't like it entirely, but the colors look good.)

**Comment by jonathanslenders** [comment]
See: https://github.com/Maximus5/ConEmu/issues/227

**Comment by jonathanslenders** [comment]
The latest release always uses ANSI escape codes when ConEmu has been detected. However, unfortunately 256 colors only works in the bottom region.
I close this, because there is nothing more on our side that we can do.
