### ISSUE TITLE
Multiline Editing (provide default text)

### ISSUE THREAD

**Issue by meeas** [jonathanslenders/python-prompt-toolkit#140]
How do you do multiline editing?  I see the example to do multiline inputs, which I love, but how do you provide default text to edit?  I don't see an argument you can pass to get_input() or CommandLineInterface() when looking through the source.

**Comment by jonathanslenders** [comment]
Hi @meeas,

Currently, it's not yet possible to provide a default text through the shortcuts module. (Thanks for the suggestion, I'll do that.)

However, what is already possible is to create an Application/CommandLineInterface manually, and give it a Buffer with a ``default_document``: https://github.com/jonathanslenders/python-prompt-toolkit/blob/9aa56e741444ff0c2756e531b3a352063b7e99c2/prompt_toolkit/buffer.py#L171
That's a bit more work though.

Jonathan

**Comment by jonathanslenders** [comment]
Hi @meeas,

Now it's implemented: https://github.com/jonathanslenders/python-prompt-toolkit/commit/18d85d5a236c7b434fddc8c21cfa0fd3113e0fcc
(Not yet on Pypi.)

You can provide a ``default="some text"`` to ``get_input``.

Hope that helps,
Jonathan

**Comment by jonathanslenders** [comment]
Closing this. (In the meantime, ``get_input`` has been renamed to ``prompt``. But it still takes the ``default`` argument.) Let me know whether there is something else.
