### ISSUE TITLE
ImportError: cannot import name windll in OS X 

### ISSUE THREAD

**Issue by glennq** [jonathanslenders/python-prompt-toolkit#142]
I'm surprised no one else has reported this issue, but probably `is_windows()` in `utils.py` needs to be changed, as `sys.platform` returns `'darwin'` in OS X

**Comment by jonathanslenders** [comment]
Thanks, just received this issue: https://github.com/jonathanslenders/ptpython/issues/60

Fixing right now.

**Comment by jonathanslenders** [comment]
Thanks a lot for reporting, @glennq !

Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/aa32f27944c9cd4e370d7e993bb7649a1ad66348 and new release pushed to Pypi.
