### ISSUE TITLE
Add left/right arrow to navigate across columns in multi-column completion menu

### ISSUE THREAD

**Issue by amjith** [jonathanslenders/python-prompt-toolkit#147]
Right now I have to press up/down arrow or use Tab key to cycle through the suggestions. But it will be more powerful if we let the user jump between columns using left/right arrow keys.

**Comment by jonathanslenders** [comment]
See also: https://github.com/jonathanslenders/ptpython/issues/46

This is ambiguous, because left/right already means: "move the cursor". What I guess I will do is support left/right, but only after down has been pressed at least once to select a completion. If no completion has been selected, it will still move the cursor.

**Comment by amjith** [comment]
Yes that would be ideal behavior. 

While you're doing that I'm wondering if you can make the down/up arrows only work after the tab key is pressed? This will allow me to start typing a partial query and then press up arrow to navigate the history that match the partial query and not select something from the menu.

**Comment by ahundt** [comment]
I'd like for it to work like zsh:
[![zsh tab completion](https://cloud.githubusercontent.com/assets/55744/25497561/06bfe6aa-2b53-11e7-831f-233ef80623a9.png)](https://youtu.be/ew51b7n7QOQ)

It probably sounds silly, but I use this so often that I'm actually sticking to zsh until this is available.

**Comment by ahundt** [comment]
@jonathanslenders any chance you could point me to the spot(s) in the code that might need to change? If it looks straightforward (~1-3 hours) I'll see if I can write a PR. I saw [PathCompleter](https://github.com/jonathanslenders/python-prompt-toolkit/blob/99fa7fae61c9b4ed9767ead3b4f9b1318cfa875d/prompt_toolkit/contrib/completers/filesystem.py#L12) and [KeyPress](https://github.com/jonathanslenders/python-prompt-toolkit/blob/96a6435558251aa68e603cd7ca8b0388678ac557/prompt_toolkit/key_binding/input_processor.py#L28) and it looks like [completer in interface.py](https://github.com/jonathanslenders/python-prompt-toolkit/blob/70795a7a13044515ebe1b2d28e0993f447fbf5e5/prompt_toolkit/interface.py#L210) gets created, but I'm not sure where the up/down keypresses go so I can forward & handle left right keypresses too.

**Comment by jonathanslenders** [comment]
Hi @ahundt,

Thank you for the offer, but unfortunately, it's not that obvious. It has to be implemented as a key binding, But the completions list is a one dimensional list of completions, while it's the ``CompletionsMenu`` that knows how many columns were displayed during the last rendering. From the key bindings it's not obvious to get access to the menu. Probably you'd have to traverse the whole layout recursively.
Probably, I'd also like this to be implemented as a prompt_toolkit 2.0 feature, where the  architecture is a bit more flexible to do these things.

**Comment by ahundt** [comment]
Ah yes that does sound tricky. Well, thanks for the explanation!

**Comment by jonathanslenders** [comment]
This has been implemented for 2.0, so I'm closing this issue. Feel free to open again if it still doesn't work.

**Comment by ahundt** [comment]
I gave this a try in 2.0 and it works well, thanks!
