### ISSUE TITLE
TypeError when running tutorial

### ISSUE THREAD

**Issue by ALSchwalm** [jonathanslenders/python-prompt-toolkit#150]
When running `sqlite-cli.py`, it fails with

    Traceback (most recent call last):
      File "sqlite-cli.py", line 55, in <module>
        main(db)
      File "sqlite-cli.py", line 29, in main
        history = History()
    TypeError: Can't instantiate abstract class History with abstract methods __getitem__, __len__, append

I'm running Python 3.4.3

**Comment by dhesson** [comment]
Fails with the same error for Python 2.7.6 as well
