### ISSUE TITLE
Remove prompt_toolkit/libs

### ISSUE THREAD

**Issue by kitterma** [jonathanslenders/python-prompt-toolkit#157]
Shipping this wcwidth copy doesn't seem necessary.  If it's not present, setuptools will install it from pypi.  For distros (like Debian in my case) we use a packaged copy of wcwidth and not the one included in prompt_toolkit.  I'm not submitted a pull request since it's just deleting the directory.

**Comment by jonathanslenders** [comment]
That's right. Thanks for pointing out.

Done: https://github.com/jonathanslenders/python-prompt-toolkit/commit/2dcb5c69b871f1788ba750ac6778852ac2ad3460
