### ISSUE TITLE
  ctrl-w ctrl-w then ctrl-y

### ISSUE THREAD

**Issue by dbolser-ebi** [jonathanslenders/python-prompt-toolkit#158]
In emacs this will eat the last two words then paste them both. In mycli (which uses python-prompt-toolkit) it eats two words then pasts only the last one eaten.

**Comment by jonathanslenders** [comment]
Ok, fixed in https://github.com/jonathanslenders/python-prompt-toolkit/commit/bfd9bb82956628a79c78a89c99cee97a118d8440

Thanks for reporting!

**Comment by dbolser-ebi** [comment]
Thanks dude!

On Wed, Sep 16, 2015 at 7:02 PM, Jonathan Slenders <notifications@github.com
