### ISSUE TITLE
mosh [mobile shell] compatibility

### ISSUE THREAD

**Issue by azag0** [jonathanslenders/python-prompt-toolkit#16]
When connected via [mosh](http://mosh.mit.edu) the ptpython console is broken and blinking. I guess this might have something to do with the VT100 requirement, so it's not a bug but a design limitation? My expertise is non-existent here.

**Comment by jonathanslenders** [comment]
It looks that by now, in the mosh version that I have. (1.2.5), it works fine, so I'm closing this issue.
Please reopen if you still experience any issues.
Jonathan
