### ISSUE TITLE
Add documentation for more complex layouts + tutorial.

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/python-prompt-toolkit#161]
cc: @matrixise @j-bennet

**Comment by jonathanslenders** [comment]
Hi @matrixise @j-bennet,

Have a look at this example:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/full-screen-layout.py

It should be a starting point. I'm planning to write more extensive examples in the future.

Jonathan

**Comment by matrixise** [comment]
Cool, I will read the code and try on my laptop.
Thanks

**Comment by jonathanslenders** [comment]
See also: https://github.com/jonathanslenders/python-prompt-toolkit/issues/350

(Right now, it's still difficult to create very custom full screen applications. Like in: much more difficult than I'd like it to be. But due to high demand, this becomes a priority for me. Expect in about 6-12 months to have an improved API for full screen applications.)

**Comment by j-bennet** [comment]
Thanks @jonathanslenders, can't wait for that!

**Comment by jonathanslenders** [comment]
More documentation has been written. So, closing this. But it'll still improve in the future.
