### ISSUE TITLE
How to best handle passing commands to the shell

### ISSUE THREAD

**Issue by donnemartin** [jonathanslenders/python-prompt-toolkit#162]
Hi Jonathan,

In the [SAWS](https://github.com/donnemartin/saws) project I have the following issue: https://github.com/donnemartin/saws/issues/17.

For shell execution, `subprocess` does the heavy lifting.  Piping of some commands work well, but not others.

I'm a little hesitant to go down the `pexpect` route for Windows compatibility reasons.  Hoping you might have some tips or could point me in the right direction of how to best proceed.

-Donne

**Comment by donnemartin** [comment]
Figured it out, it was an error on my end with the pygments output highlighting.

**Comment by jonathanslenders** [comment]
Glad you found it! Feel free to create new issues for all possible bugs that you find ;)

**Comment by sac2171** [comment]
Link for the curious:
https://github.com/donnemartin/saws/commit/0d7f59b197eda562673292959c3bc641de4462e7
