### ISSUE TITLE
Mouse support breaks scrolling

### ISSUE THREAD

**Issue by mdraw** [jonathanslenders/python-prompt-toolkit#168]
As I mentioned here https://github.com/scopatz/xonsh/pull/393#issuecomment-143664623, enabling the new mouse support makes scroll wheel scrolling impossible.

Code to reproduce:

    from prompt_toolkit.shortcuts import get_input
    get_input(mouse_support=True)

Execute and try using your scroll wheel in the terminal. Does it work on your system?

**Comment by jonathanslenders** [comment]
Hi @mdraw,

It depends. By default, it's impossible to to both capture mouse events and support scrolling. (That would be ambiguous.) However, it's up to the terminal application to decide whether or not forward the scrolling event to the pseudo terminal. E.g. in tmux it's always possible (Press ``Ctrl-B`` followed by ``[``.) In some terminals, scrolling still works when shift or option is pressed. (E.g. shift for urxvt.)

We output a vt100 instruction that requests the terminal to send button clicks to stdin. Unfortunately scrolling is considered a click as well, (using button 4 and 5.)

So, I guess not much to do about this. Better to make it configurable and allow the user to decide whether or not to handle mouse events.

Jonathan

**Comment by mdraw** [comment]
Thanks for the explanation! Good to know that tmux scrolling with `[` still works, I hadn't tried that.

Looks like this is a trade-off and a matter of personal preference, so I completely agree with you that it's a nice feature as long as it is optional and the potential problems with it are well-documented and easily visible by users.
