### ISSUE TITLE
Example refactor?

### ISSUE THREAD

**Issue by sac2171** [jonathanslenders/python-prompt-toolkit#169]
Most of the examples have a line:
from prompt_toolkit import prompt

Was this interface renamed?
eg:
>>> from prompt_toolkit.contrib.completers import WordCompleter
>>> from prompt_toolkit import prompt
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name prompt

I'm using the newest toolkit version, aka prompt-toolkit (0.52)

**Comment by jonathanslenders** [comment]
Hi @sac2171,

That is right. The function was renamed yesterday from ``get_input`` to ``prompt``, but this is not yet released on Pypi. I will probably release today, but in any case, the old name should keep working for a while.

Currently, I'm busy writing extensive Sphinx documentation, and I try to iron out inconsistencies and bad names.

**Comment by jonathanslenders** [comment]
I released a new version to Pypi.

New documentation is work in progress (There are still many gaps, but we keep improving.)
http://python-prompt-toolkit.readthedocs.org/en/latest/
