### ISSUE TITLE
Cannot get expanduser to work with PathCompleter

### ISSUE THREAD

**Issue by pombredanne** [jonathanslenders/python-prompt-toolkit#170]
Using this minimal snippet:
```

from __future__ import unicode_literals
from __future__ import print_function
from prompt_toolkit.contrib.completers.filesystem import PathCompleter
from prompt_toolkit.shortcuts import get_input

def main():
    completer = PathCompleter(only_directories=False, expanduser=True)
    while True:
        try:
            text = get_input('path> ', completer=completer)
        except EOFError:
            break
        except KeyboardInterrupt:
            continue
        if text and text.strip():
            print('You selected: ', text)

if __name__ == '__main__':
    main()
```
I fire the script and start typing `~/` and I get no completion at all...
Typing tab completes on the path of os.cwd alright.
I am getting something wrong to get exxpanduser to work?

I think this is missing a test and possibly something like that about there:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/c7c306bc5ca57beff9a64150eb86b7d75453ab48/prompt_toolkit/contrib/completers/filesystem.py#L45
```
if self.expanduser:
    text = os.path.expanduser(text)
```

**Comment by pombredanne** [comment]
User expansion now works with the proposed pull request. Let me add some tests too.

**Comment by jonathanslenders** [comment]
Hi @pombredanne That pull request has been merged. Can I close this?

**Comment by pombredanne** [comment]
please to. It has been tested on my side on Mac, Linux and Windows.
