### ISSUE TITLE
Please ship tests to pypi

### ISSUE THREAD

**Issue by jlec** [jonathanslenders/python-prompt-toolkit#180]
Could you please include the tests in the pypi tarball so that downstream maintainers can run the testsuite during installation? thanks

**Comment by danirus** [comment]
@jlec, thank you for catching it, I missed this one.
I'll do it as soon as I'm back to work next week.

**Comment by jlec** [comment]
Thanks.

**Comment by danirus** [comment]
Sorry, I answer the wrong comment. 
The decision on this belongs to Jonathan :)
Sorry @jonathanslenders.

**Comment by jonathanslenders** [comment]
Hi all,

I will do this. If it's urgent, then a pull request is appreciated.

Thanks,
Jonathan

**Comment by jonathanslenders** [comment]
I believe tests were included some time ago. See the MANIFEST.in.
