### ISSUE TITLE
How to scroll one buffer's content while focus is in another buffer?

### ISSUE THREAD

**Issue by svetlyak40wt** [jonathanslenders/python-prompt-toolkit#185]
Hi, I have a chat app where chat's stream is rendered into one buffer, and input taken from another
buffer at the bottom of the screen.

I'm wondering if there is a way to scroll big inactive buffer using some shortcuts?

**Comment by jonathanslenders** [comment]
Hi @svetlyak40wt,

Currently, there is no key binding that does this out of the box. But to give you some directions, the following could work:

Have a look at this file. There are ``scroll_forward`` and ``scroll_backward`` functions. As they are now, they operate on the buffer that has the focus. Replace ``event.cli.current_buffer``, by ``event.cli.buffer['your_buffer_name']`` to make them operate on another buffer.
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/scroll.py

For more info about creating key bindings for a full screen application, see: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/full-screen-layout.py

Hopefully that helps.
Jonathan

**Comment by svetlyak40wt** [comment]
Hi Jonathan!

Your advice is perfect, thank you! Now it works as desired.
