### ISSUE TITLE
history-search-backward

### ISSUE THREAD

**Issue by justmytwospence** [jonathanslenders/python-prompt-toolkit#188]
Does prompt_toolkit have an equivalent functionality to readline's `history-search-backward` (and forward as well). This is one readline feature I can't live without (always kinda felt like it should be the default).

**Comment by jonathanslenders** [comment]
Hi @justmytwospence,

I guess this is what the ``enable_history_search`` option does. Have a look at this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/up-arrow-partial-string-matching.py

Maybe also have a look at this, related example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/auto-suggestion.py

Jonathan

**Comment by jonathanslenders** [comment]
Closing this. Please reopen if you have other questions.

**Comment by MarkLodato** [comment]
Is it possible to bind this to a different key (with IPython, at least)?  I find it intolerable to have up arrow be anything but scrolling through history, but the `history-search-backward` feature is useful so I bind it to a different key. Thanks!
