### ISSUE TITLE
Conda package available on conda-forge

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#197]
As per conda-forge/staged-recipes#31, a prompt_toolkit conda package is available via conda-forge.  To install, please use.

```console
$ conda install -c https://conda.anaconda.org/conda-forge prompt_toolkit
```

Might be nice if this made it into the docs somehow. Thanks!

**Comment by jonathanslenders** [comment]
Added to the readme: https://github.com/jonathanslenders/python-prompt-toolkit/commit/1d1ebc0bd6d06f89de282ed87c6f4a75ab9d679c

There is also this pull request: https://github.com/jonathanslenders/python-prompt-toolkit/pull/196
Should I merge that or not? I have no idea whether or not other Python packages add the conda build recipes to their repository. (I'm not sure it makes sense to have build scripts for all Python distributions in this repository.)

Jonathan

**Comment by scopatz** [comment]
Thanks @jonathanslenders!  

For what it is worth, a lot of packages (and least in the scientific python ecosystem) have started including the conda recipes in the source repo as a way for people to build the conda package from the source code itself, rather than some external place.  For what it is worth, I also think that @melud's PR looks good.
