### ISSUE TITLE
No way to asynchronously load history with prompt()

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#202]
I am opening this PR in light of scopatz/xonsh#578.  Basically, if history takes a long time to load, it is beneficial to do so in a background thread and return the prompt as soon as possible.  However, because there is no access to the buffer object and [the buffer copies the history](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/buffer.py#L268), there is no way to reset the buffer after history has been added to in this way.  

I am not sure that this is fixable without some gymnastics.  Maybe the right thing to do would be to have a Prompt class, as opossed to the `prompt()` function that gives the user access to the `cli` and `buffer` objects.

**Comment by jonathanslenders** [comment]
Thanks for this request. It definitely makes sense. I will have a look at how to approach it. Asynchronous should be possible.

But how is it possible that it takes so much time? The history should be huge! I mean,... processing a million lines of history should be possible in a fraction of a second. (I think.)

**Comment by scopatz** [comment]
Well, xonsh has a [rich history object](http://xonsh.org/tutorial_hist.html) that stores each session in its own file. Assembling and aggregating input history is a more length computation.  Its kinda like if history was stored in a database somewhere. It might take longer to communicate with the server than you want to wait for the prompt to show up.

**Comment by scopatz** [comment]
So this can be accomplished by calling `Buffer.reset()` method in the asynchronous loader, as see in scopatz/xonsh#593 [on this line](https://github.com/scopatz/xonsh/pull/593/files#diff-97766854f37c68cd75347652fb11e8c4R68).  

The problem is getting access to the buffer in the first place, which is stored on the application which is itself on the cli.  The approach xonsh takes is to make significant portions of `prompt_toolkit.shortcut` into a `Prompter` class, that has a prompt method.  The the cli then gets stored and cleared as an attribute of that class. This allows for asynchronous access. `Prompter` is a context manager to ensure that the cli is not around longer than needed.

It would be nice if this approach made it into prompt-toolkit itself.  Then the `prompt()` function could just be a wraper around `Prompter().prompt()`.  Does this sound reasonable to you?

**Comment by jonathanslenders** [comment]
I will think about this. Not sure right now. From ``prompt_toolkit.shortcuts.prompt``, I could probably make the CLI available through a callback.

**Comment by jonathanslenders** [comment]
@scopatz: Async loading of history, implemented in https://github.com/jonathanslenders/python-prompt-toolkit/pull/621
It is as simple as wrapping the history in ``ThreadedHistory``.

**Comment by jonathanslenders** [comment]
Closing. Prompt_toolkit 2.0 supports async history loading.

**Comment by scopatz** [comment]
This is great news!
