### ISSUE TITLE
version not available at run time

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#205]
it would be nice to have a `prompt_toolkit.__version__` variable.

**Comment by jonathanslenders** [comment]
I'll make it available. Thanks for noticing!

**Comment by jonathanslenders** [comment]
Done: https://github.com/jonathanslenders/python-prompt-toolkit/commit/986a6c3a9f48cdc714e683a36b82fcc5123b1fe7

**Comment by scopatz** [comment]
Thanks again!
