### ISSUE TITLE
`control-[` does not invoke escape

### ISSUE THREAD

**Issue by esheldon** [jonathanslenders/python-prompt-toolkit#208]
The `control-[` sequence does not seem to map to escape, as it normally does.

The motivation for this is to minimize movement of the hands from the home
row.  I map caps-lock to control and then use `control-[` instead of hitting
escape to switch vi mode.

I think this is standard behavior, at least it is supported in all the
terminal apps I normally use.

Note I was actually testing ptpython when I noticed this, but I suspect the
implementation of this sequence would be in prompt-toolkit so I posted the
issue here.

**Comment by esheldon** [comment]
never mind, bug on my end

**Comment by jonathanslenders** [comment]
Don't worry. Glad you found it!
