### ISSUE TITLE
Multiline prompt

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#209]
I couldn't figure this out from the docs or the source code, so there may not currently be a way to do this. Right now there doesn't seem to be a way to have prompt-toolkit issue prompts on any line but the first.  For example, in xonsh, we see the current behaviour with scopatz/xonsh#601

```console
scopatz@localhost ~ $ def g():
                          print(2)
                          
scopatz@localhost ~ $ g()
2
```

However, what I would like to see is something like the following:

```console
scopatz@localhost ~ $ def g():
.....................     print(2)
.....................                          
scopatz@localhost ~ $ g()
2
```

I think that this is more readable.  Basically the problem I was running into is that the get_tokens_func seems to only affect the first line.  Any ideas?

**Comment by jonathanslenders** [comment]
Hi @scopatz,

This has been implemented in one of the last commits today.
Have a look at this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/get-multiline-input.py#L6

Please let me know if this doesn't work for you.

**Comment by scopatz** [comment]
Thanks a million @jonathanslenders, this seems like it should work.  Any idea when this will make it into a release? I am hesitant to add code to xonsh master that hasn't been released by prompt-toolkit.

**Comment by jonathanslenders** [comment]
Hi @scopatz,

I will first try to create pull requests for all prompt-toolkit projects that are still using older versions to upgrade to the latest prompt-toolkit. (These are only a few.) Then I'll see whether the IPython guys have any special requirements. And then I'll do a new release. (Just trying to avoid releasing too quick and often.)

Jonathan

**Comment by scopatz** [comment]
Sure thing! Is there a mailing list or anything where these get announced on?  They just sort of seem to happen unless you are watching the repo (which I am not).

**Comment by jonathanslenders** [comment]
No, right now we don't have a mailing list yet. (I will think about it, but often my mailbox is flooded enough that I easily forget to answer e-mails.)

**Comment by scopatz** [comment]
> my mailbox is flooded enough that I easily forget to answer e-mails

yeah.... I really hate email myself.  That is one of the reasons why I don't want to watch this repo.  It would be *that* many more emails.

**Comment by kitterma** [comment]
For all the users of prompt-tookit that are in Debian, mycli, pgcli, and softlayer-python, they should work fine with the current release (due to the backward compatibility changes of mine you merged) - unless you added more changes that will break backward compatibility.  For those at least there's no need to do anything to have them update (and softlayer-python requires you to sign a CLA if you're going to contribute code to it).
