### ISSUE TITLE
Slight documentation error

### ISSUE THREAD

**Issue by stweller** [jonathanslenders/python-prompt-toolkit#230]
In the example about creating a custom style (section "Colors") on readthedocs the import for "Token" is missing. Not super important but it is nice if the code snippets are copy-and-pasteable into a python file and just work.

**Comment by stweller** [comment]
Oh, and PygmentsLexer and HtmlLexer are also missing.

**Comment by jonathanslenders** [comment]
Ok, thanks for pointing out! Feel free to create a pull request for this. If not, I'll fix it later on.

**Comment by stweller** [comment]
I just found another similar error while going through the docs and playing around. I will collect everything I find and create a PR later.

**Comment by jonathanslenders** [comment]
This was merged from that pull request, so I guess we can close it. (Feel free to reopen if not.)
