### ISSUE TITLE
right prompt

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#237]
This is a feature request that we got over at scopatz/xonsh#674 that I thought I would pass along.  Apparently, zsh and others have an "RPROMPT" or right prompt ability.  I realize that this may be out of scope, but we'd certainly use it in xonsh if PTK supported it.  Maybe @arkhan can add more?

**Comment by jonathanslenders** [comment]
Hi @scopatz, @arkhan,

Prompt-toolkit doesn't support this RPROMPT yet, but we can definitely implement that. It's an interesting feature.

I just tried RPROMPT in zsh, and it seems that it is hidden when the text flows over it. Is that what you would expect?

We can probably implement that in the default layout from prompt_toolkit.shortcuts by adding a right aligned float. One that is only displayed if the underlying region is still empty.

Are there any other variations to this RPROMPT, known in other shells? Maybe we need a more generic, universal solution, that is more flexible than what I currently have in mind.

Jonathan

**Comment by scopatz** [comment]
Hi @jonathanslenders RPROPMT is totally new to me.  The first I have heard of it has been from @arkhan.  I agree that the implementation is way easier if you allow it to be overwritten when the input becomes too long. Is this what you were expecting @arkhan?

**Comment by arkhan** [comment]
if the idea is to have separate prompt, left and right

**Comment by jonathanslenders** [comment]
Hi all, rprompt has been added to prompt-toolkit. It's commited to the master branch.
Can you have a look at this commit https://github.com/jonathanslenders/python-prompt-toolkit/commit/a666010fc4bfa302e5f34cab868a48869ba6bc6d and see whether that is what you expect?

**Comment by arkhan** [comment]
cool, but how to instegrate in xonsh...?

**Comment by scopatz** [comment]
Thanks @jonathanslenders!  @arkhan this is something that will need to be changed in `xonsh.ptk.shell` Please feel free to open up a PR to xonsh for this, otherwise it will have to wait for someone else to get to it.  Thanks!

**Comment by scopatz** [comment]
@jonathanslenders I have now implemented what I believe are the correct hooks in scopatz/xonsh#696

**Comment by scopatz** [comment]
Thanks again!

**Comment by arkhan** [comment]
+1

**Comment by jonathanslenders** [comment]
Ok, closing this. A new release should follow one of these days.
