### ISSUE TITLE
bug in autosuggest text in multiline

### ISSUE THREAD

**Issue by gforsyth** [jonathanslenders/python-prompt-toolkit#245]
`git bisect` points to 1a55699 as the culprit for this.  A minor display issue that I ran across in `xonsh`

I'm on `xonsh` master for both of these.  
With `prompt_toolkit 0.57` this is the autosuggest display:

![pt57xonshmaster](https://cloud.githubusercontent.com/assets/3596999/13186489/7824b2ec-d714-11e5-8e32-b0fc0af68954.png)

After 1a55699 the autosuggest text is mirrored at the end of the first line:

![ptmasterxonshmaster](https://cloud.githubusercontent.com/assets/3596999/13186490/78257222-d714-11e5-9465-3533c97faa08.png)

**Comment by jonathanslenders** [comment]
Hi @gforsyth, Thank you for pointing out this bug. I'll fix it asap.
Jonathan

**Comment by jonathanslenders** [comment]
Hi @gforsyth, it should be fixed in https://github.com/jonathanslenders/python-prompt-toolkit/commit/c8ef2b9b3e19b10741a525e770f6562279234336
Could you try again. Thanks!

**Comment by gforsyth** [comment]
Hey @jonathanslenders, that did it!  Thanks!
