### ISSUE TITLE
get_prompt_tokens() too frequently called

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#247]
I can't tell whether this is a feature (to work around) or a bug, but it seems as though - with xonsh at least - that the `get_prompt_tokens()` function that we pass in is being called at each and every key press. This is pretty much *not* what we want since we do things like check the branch of a repository in the prompt.  Is there any way to make prompt-toolkit call this function only once without providing some sort of closure or cache mechanism to trick prompt-toolkit.  I bring this up because it may have been causing noticeable slowdown issues (@BYK reported 1 sec to render each key event) and I am not sure it is an intended part of the design.

**Comment by jonathanslenders** [comment]
Hi @scopatz,

This is definitely as expected. I'm going to document this better. There are many situations where the prompt can actually change on every key press. (Imagine that the current key bindings are displayed there, or something else that can change on every key stroke.)

A simple workaround could be this:

```python
prompt_tokens_cache = get_prompt_tokens()  # call your own function once.

# Pass this cache to the ``prompt`` function.
prompt(get_prompt_tokens=lambda cli: prompt_tokens_cache)
```

**Comment by scopatz** [comment]
Hi @jonathanslenders - OK, good to know.  This is what I meant by having a closure that contains the data :).  For what it is worth, I think that some more documentation could help. 

I think xonsh is in a funny position because computing our prompts can be arbitrarily expensive.  In my simple testing on a high end desktop there were 4 - 5 orders of magnitude separating the timings of the closure vs non-closure methods.

Thanks for explaining, I have implemented the fix.
