### ISSUE TITLE
0.58 released.

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/python-prompt-toolkit#249]
Version 0.58 has been released.
This release implements the continuation tokens. (among other things.)
Have a look at the changelog: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG

If you have time, I appreciate if you could have a try and report new issues.

@scopatz @amjith @Carreau @takluyver @donnemartin @j-bennet

Thanks a lot,
Jonathan

**Comment by amjith** [comment]
What are continuation tokens?

**Comment by jonathanslenders** [comment]
For a multiline prompt, you can specify what needs to be displayed in the left margin. Typically some dots, like in a Python shell. See: http://python-prompt-toolkit.readthedocs.org/en/latest/pages/building_prompts.html#multiline-input
or this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/get-multiline-input.py

A right prompt is another new thing: http://python-prompt-toolkit.readthedocs.org/en/latest/pages/building_prompts.html#adding-a-right-prompt

**Comment by takluyver** [comment]
Thanks!

**Comment by scopatz** [comment]
Thanks a ton @jonathanslenders! I'll take a look in the next couple of days.  We already have reports that the right prompt works as expected from @gilforsyth scopatz/xonsh#696

**Comment by scopatz** [comment]
Also, @jonathanslenders, was there are reason for removing pygments from the `install_requires`? This happened to break xonsh CI, as noticed by @gforsyth.  Is pygments not actually required?  And if not, what do you do for coloring if it is not present?

**Comment by jonathanslenders** [comment]
Pygments became an optional dependency. At some point, about 95% of the terminal rendering was reimpemented in prompt-toolkit. We now have this because we support 16colors, 256 colors and true color, as well as Windows console rendering. Further, we have support for underline, blink and reverse, which Pygments does not have. A light version of ``pygments.token`` has been implemented in ``prompt_toolkit.token``. (Those are compatible.) 

So, Pygments is only needed if you actually need syntax highlighting from a Pygments lexer. So, indeed you'll have to add Pygments directly as a dependency in xonsh.
