### ISSUE TITLE
Allow VSplit (HSplit), to get a height (width) keyword

### ISSUE THREAD

**Issue by Carreau** [jonathanslenders/python-prompt-toolkit#258]
I want to write something like 

```
HSplit([
    VSplit(..., height=LayoutDimension(...)),
    VSplit(..., height=LayoutDimension(...)),
])
```

Or vice versa. write now it does not seem to be possible without an extra overriding of the `get_prefered_width|height`.

Does that make sens ?

I think I have roughly an idea on how to implement that.

**Comment by jonathanslenders** [comment]
If we do this, then we should probably allow both VSplit and HSplit to accept a with and a height.
A VSplit can be nested in a VSplit as well, and a HSplit can also be nested in a HSplit.

If you don't mind, maybe I'll do it.
(If we do this, I'd like to have as much consistency as possible between HSplit/VSplit and Window classes. And right now, a Window class already takes a with/height as well as get_width/get_height.
This is also why I didn't merge the other pull request yet. I'm balancing between keeping stuff as DRY as possible, but without going too far and making sure it's still understandable. -- I have to think how to approach this.)

**Comment by Carreau** [comment]
Sure no problem, I'm still looking at the codebase and learning, I'm mostly reporting the pain I'm feeling and the limitations I hit.

**Comment by jonathanslenders** [comment]
Prompt_toolkit 2.0 has now width/height arguments for both VSplit and HSplit.
