### ISSUE TITLE
Question on ConditionalContainers 

### ISSUE THREAD

**Issue by Carreau** [jonathanslenders/python-prompt-toolkit#262]
Hey, 

I am playing with filters/HSplit/VSplit

I roughly have a 
```
HSplit([
     ... long list
    ConditionalContainer(.., a_filter)
    ... long list
])
```

I was expecting the `ConditionalContainer` to get a height of 0 when "hidden", which apparently is not the case. The current behavior make sens with respect to the doc, and and see its use with floats. 
But would it make sens to have the dimension set to zero when hidden ?

(I'm basically creating a list of 1 line editable buffer that can be filter based on some rules, I might be attacking the problem in a completely incorrect way.)

**Comment by jonathanslenders** [comment]
Actually, it should have a height of zero, when it's hidden.

When hidden (When the filter returns False), it returns ``LayoutDimension.exact(0)``
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/layout/containers.py#L1507

```python
 def preferred_height(self, cli, width, max_available_height):
        if self.filter(cli):
            return self.content.preferred_height(cli, width, max_available_height)
        else:
            return LayoutDimension.exact(0)
```

I just did a test, and it works for me. Could you maybe test again and email me the code if that's possible?

**Comment by Carreau** [comment]
> I just did a test, and it works for me. Could you maybe test again and email me the code if that's possible?

Hum, ok I'll retry, and make a smaller example. 
I'm likely not familiar enough with how to do thing. 

[here](https://gist.github.com/Carreau/9e7805354413231cf690) is what I have for now.

**Comment by Carreau** [comment]
I'm stupid, nevermind.
