### ISSUE TITLE
Right prompt not aligned to the top

### ISSUE THREAD

**Issue by melund** [jonathanslenders/python-prompt-toolkit#264]
The right prompt is not aligned with normal prompt. See the picture:

![image](https://cloud.githubusercontent.com/assets/1038978/13669383/68875c68-e6c3-11e5-8ce8-c63942f3d4b9.png)

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/478d8c7d8c66a71469a7be05af7339f6a2f5f541

**Comment by melund** [comment]
I can confirm that it fixes it...

**Comment by jonathanslenders** [comment]
A new release has been published to Pypi. Thanks for reporting!
