### ISSUE TITLE
Handle Escape in reverse search.

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/python-prompt-toolkit#265]
https://github.com/ipython/ipython/issues/9309#issuecomment-194479419

**Comment by jonathanslenders** [comment]
We can't do this by default. Handling escape in reverse search would mean that Alt-Enter doesn't won't work anymore. (Alt-enter in reverse search should execute the current match right away.)

It's more important to have alt-enter work than to have Esc as an alias for Control-G and Control-C.

**Comment by randy3k** [comment]
What about double <esc>?

**Comment by jonathanslenders** [comment]
Hi @randy3k,
Even double-escape is possible.
Right now, I just implemented this on the 2.0 branch. But it's not trivial to backport it to the current master 1.0 branch (current master). A lot of stuff is changed regarding the event loops and handling of the escape key. I'll see whether it's feasible and not too much work.
