### ISSUE TITLE
Strange Redirection Problem with Xonsh Interactive Login Shell in mlterm 

### ISSUE THREAD

**Issue by ajstein** [jonathanslenders/python-prompt-toolkit#267]
I cannot tell if this is something strange I have done with my mlterm configuration, which is minimal, or my new xonsh configuration.  I usually use emacs as a term multiplexer these days, and mlterm was a hold-over for complex script languages I read and sometimes use.  I am unable to delete a file when prompted, it immediatetly throws an error when prompted for user input.

```
me@computer ~ $ mlterm -v
mlterm version 3.7.0
me@computer ~ $ import xonsh
me@computer ~ $ xonsh.__version__
'0.2.6'
me@computer ~ $ import prompt_toolkit
me@computer ~ $ SHELL_TYPE=prompt_toolkit
me@computer ~ $ prompt_toolkit.__version__
'0.60'
me@computer ~ $ rm ~/Code/conf.py
/usr/bin/rm: remove regular file '/home/me/Code/conf.py'?
*[1] stopped: rm /home/me/Code/conf.py & (10123)
TypeError: unorderable types: NoneType() > int()
```

For the last line, if I redirect output with xclip to speed up copy-paste for this ticket, redirection magically is fine and I can actually answer yes or no.

```

me@computer ~ $ rm ~/Code/conf.py | xclip -sel clip
/usr/bin/rm: remove regular file '/home/me/Code/conf.py'?
```

My dotfiles are [in my repo.](https://github.com/ajstein/dotfiles.git)  I just created the most minimal xonsh possible from my minimal needs with xonfig.

```
{
 "foreign_shells": [
  {
   "login": true,
   "shell": "bash"
  },
  {
   "shell": "bash"
  }
 ]
}
```

Did I wrap two login shells into each other or something basic I forgot?  I have tried running `mlterm` straight with the default `bash` shell, but also tried bypassing this and running just xonsh with `mlterm -e xonsh` and I get the same behavior on all attempts.

**Comment by ajstein** [comment]
Sorry you can disregard. I foolishly copy pasted into this bug tracker when I intended for xonsh. Sorry.

**Comment by jonathanslenders** [comment]
No problem!
