### ISSUE TITLE
Example for updating toolbars periodically?

### ISSUE THREAD

**Issue by deeplook** [jonathanslenders/python-prompt-toolkit#277]
I'm new to python-prompt-toolkit, but can see many exciting use cases! As a first I want to build some simple toolbar-like thing, showing a sparkline of a data series, see:

- https://github.com/kablamo/git-spark
- http://python-prompt-toolkit.readthedocs.org/en/stable/pages/building_prompts.html#adding-a-bottom-toolbar

Now the last example updates the toolbar only after a key press, but I'd like it to be updated periodically, after every five seconds, say. Is there a way to do this, using threads or async? I'd appreciate if an example for that would be added to the documentation.

**Comment by jonathanslenders** [comment]
Hi @deeplook,

Have a look at this example:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/clock-input.py
This updates the clock in the prompt every second. The key is to call ``cli.request_redraw()`` when the UI needs to be updated. The same thing can be done for the bottom toolbar.

Jonathan

**Comment by deeplook** [comment]
Thanks, I'm trying to wrap my head around it (not quite seeing how to add a toolbar to the Application layout, yet).

Another immediate encoding issue I have is that adding anything like real Unicode chars, say '€', in this line will result slightly garbled on screen, despite the import line `from __future__ import unicode_literals`:

https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/clock-input.py#L23

**Comment by jonathanslenders** [comment]
What terminal and Python version are you using? On my system it works without issues.

**Comment by deeplook** [comment]
The issue with Unicode chars has disappeared after moving to version 1.0. Thanks!

Now I only need to get the auto-redrawing right. I'd be glad to contribute this code below as an example. Instead of random numbers it could show something more meaningful like CPU load using the `psutil` package.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import random
import subprocess

from prompt_toolkit import prompt
from prompt_toolkit.styles import style_from_dict
from prompt_toolkit.token import Token


def sparkline(numbers=[]):
    "Calculate a 'sparkline' for a list of input numbers, handle Nones, too."

    if len(numbers) == 0:
        return ''

    # find min/max values, ignoring Nones
    filtered = [n for n in numbers if n is not None]
    min_ = min(filtered)
    max_ = max(filtered)
    dv = max_ - min_

    # below X is only a dummy character used for convenience
    if dv > 0:
        ticks = 'X▁▂▃▄▅▆▇█'
        num_ticks = len(ticks) - 1
        values = [round((num_ticks - 1.)/(dv)*x + (max_*1. - min_ * num_ticks)/(dv)) if not x is None else None
            for x in numbers]
    else:
        ticks = 'X▄'
        values = [1 for x in numbers]

    res = [u' ' if v is None else ticks[int(v)] for v in values]
    return ''.join(res)


toolbar_style = style_from_dict({
    Token.Toolbar: '#0000ff bg:#ffffff',
})


def get_bottom_toolbar_tokens(cli):
    ## todo: make this redraw itself every second...
    values = [random.randint(0, 9) for i in range(80)]
    line = sparkline(values)
    return [(Token.Toolbar, line)]


def main():
    while True:
        try:
            text = prompt('> ', 
                get_bottom_toolbar_tokens=get_bottom_toolbar_tokens,
                style=toolbar_style)
        except KeyboardInterrupt:
            break
        if not len(text):
            pass
        try:
            subprocess.check_call(text.split())
        except:
            print('?')
            pass


if __name__ == '__main__':
    main()
```

**Comment by jonathanslenders** [comment]
Hi @deeplook,

I'm working on a patch for prompt-toolkit to make this significantly easier. Hopefully, I can finish and push this later this week. I'll keep you posted.

Jonathan

**Comment by deeplook** [comment]
@jonathanslenders, thanks! I was using Mac OS X with the built-in terminal or iterm2 and Python 2.7 in this case.

**Comment by jonathanslenders** [comment]
Hi @deeplook 

Have a look at this example. (Requires the latest github version)
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/clock-input.py

**Comment by deeplook** [comment]
Hi @jonathanslenders!
Looks wonderful! Will test more early next week in combination with my https://pypi.python.org/pypi/sparklines. So far it seems that I'm not expected to use escape codes like those introduced by `termcolor`. But for now: thanks so much!

**Comment by jonathanslenders** [comment]
You're welcome.
If you want more color. Use different Tokens, and give them a style. termcolor-like escape sequences don't work. (They are also not platform independent.)
