### ISSUE TITLE
Direction of prompt-toolkit

### ISSUE THREAD

**Issue by certik** [jonathanslenders/python-prompt-toolkit#285]
The README says "prompt_toolkit could be a replacement for GNU readline, but it can be much more than that.". It seems to me that it is now also a replacement for `curses`.

I was wondering, what direction you want to go. I have written up the background here:

https://github.com/inducer/pudb/issues/181

Do you think that `prompt-toolkit` would be a good foundation to get a full featured text UI, like I mention in the pudb issue above (see the screenshots there etc.)? Such a full featured set of widget would probably be written on top of a `prompt-toolkit`, as a separate library.

**Comment by jonathanslenders** [comment]
Hi @certik,

Excuse me for the late reply. Prompt_toolkit 2.0 has been released now, and as you can see it is possible to build full screen applications now. It took some time to get here, and I'm sure we need to implement more widgets. My ptterm project could be useful too for embedding a vt100 emulator as a widget in a prompt_toolkit application. It will gradually improve, but it's hard to decide whether everything you need is possible right now.
