### ISSUE TITLE
custom key bindings

### ISSUE THREAD

**Issue by obeleh** [jonathanslenders/python-prompt-toolkit#290]
How can I make custom key bindings like "Shift-F11" ? I tried 
- `@manager.registry.add_binding('Shift', 'F11', eager=True)`
- `@manager.registry.add_binding(Key('<Shift-F11>'), eager=True)`
- `@manager.registry.add_binding(Key('<Shift>'), Key('<F11>'), eager=True)`

How do I make "shift"-key combinations?
My gut says no but I want to ask the question to be sure: Would it be possible to suppress the terminals' key bindings so that I could use keys like F1, F10, F11, F12, Ctrl-S

**Comment by jonathanslenders** [comment]
Hi @obeleh,

The underlying terminal protocol does not define something like ``Shift-F11``. However, I think that most terminal applications send this combination as ``F23``. Could you try binding a handler to ``F23``?

https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/keys.py#L99
