### ISSUE TITLE
Cursor disappears on forward-delete

### ISSUE THREAD

**Issue by Carreau** [jonathanslenders/python-prompt-toolkit#296]
Gif is better to explain.

![cursordisapear](https://cloud.githubusercontent.com/assets/335567/15403424/ba735a74-1dad-11e6-8987-65a2d52e14c1.gif)

In words, when using forward delete (fn-backspace for example), the cursor disappear until it is moved.

**Comment by jonathanslenders** [comment]
This is weird. What terminal application are you using?
gnome-terminal and xterm don't seem to have the issue.

**Comment by Carreau** [comment]
iTerm2, OS X, Build 2.9.20160510

**Comment by Carreau** [comment]
> iTerm2, OS X, Build 2.9.20160510

Ouh, i just realised it's a date: 2016-05-10. And it's the latest non-nightly.

**Comment by jonathanslenders** [comment]
Hi @Carreau,
I'm closing this issue. I haven't heard of anyone else that had the same issue, and I don't believe I could reproduce it. Feel free to open again, if you think it's still the case.
