### ISSUE TITLE
load_vi_mode() takes an excessive amount of time, even when vi mode isn't used.

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#298]
Hi @jonathanslenders et al., I just wanted to let you know that after profiling xonsh startup times a bit, I have found that one of the major culprits is the `load_vi_mode()` function.  This figure shows the breakdown for the shell initialization function, which calls the KeyManager initializer:
http://vmprof.com/#/56e022bb8e1d53cffec42ff1b8d230b6?id=2,0,0&view=flames

Worst of all, there doesn't seem to be a way to turn this off selectively in the event that vi mode won't be used.  Even weirder is that the emacs mode loading doesn't take nearly as long.

This was on v1.0

A fix would be great, because we'd like to keep our startup times as low as possible.

**Comment by jonathanslenders** [comment]
Thanks for pointing out! I was aware that loading the Vi bindings took a bit more time, but didn't realize that it was this much. I'm sure it should not be hard to optimize, I'll have a look during the coming days.

**Comment by scopatz** [comment]
Thanks @jonathanslenders!

**Comment by scopatz** [comment]
Note that this was made using vmprof, and so it might not be an exact representation of execution time.

**Comment by jonathanslenders** [comment]
It's probably quite accurate. The slowness seems to come mostly from the generation of key bindings for the named registers. That on itself is fine, but the I think the many layers of functions wrapping function in key_binding/bindings/utils.py is too much and not necessary. I'll try to simplify it.

**Comment by jonathanslenders** [comment]
Hi @scopatz,

Could you try and measure again with the latest commit of prompt-toolkit?
I did a rewrite of the input processor. So, now it's possible to have key bindings, consisting of several keys, with ``Keys.Any`` anywhere in the sequence. Because of this, we have only one key binding for operations on named register, instead of for each possible register.
See this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/c65b9e387ece4d0a781724208906e8dc5a0395c1

The unit tests became twice as fast, because of this.

**Comment by scopatz** [comment]
Hi @jonathanslenders - this is looking much better thanks!  You can see the latest profile here: http://vmprof.com/#/1ac6191b0c3283c2315b38529aee5193?id=2,0,0&view=flames  (note that the original link was for 41.47% of the total runtime, while this one is for only 23.2%)

This seems to cut xonsh's ptk startup time to be within 5% - 10% larger than when using readline.

Interestingly though, `load_vi_bindings()` is still responsible for about half of the remaining startup time. I am happy to close this issue, but this function may still be worth investigating. Thanks for the promptness!

**Comment by jonathanslenders** [comment]
Don't close it yet. I will see whether it's feasible to improve this even more. I think it should be possible.

**Comment by jonathanslenders** [comment]
One more fix: https://github.com/jonathanslenders/python-prompt-toolkit/commit/e2bb3434a51c1b70e87ccff9284198efdd944f9e

Could you please measure again? After this, I have probably have one more improvement.

**Comment by scopatz** [comment]
Hi @jonathanslenders - sorry about the delay. Here are the results I am seeing now:

e2bb343: http://vmprof.com/#/ad493ed7c30eeee8cf1e5facba871625?id=2,0,1&view=flames

f827949: http://vmprof.com/#/60ff6b401a5973eaf12356327c2fffe4?id=2,0,1&view=flames

It looks like f827949 is better than the other.  I would recommend keeping both since every microsecond counts here :)

**Comment by jonathanslenders** [comment]
Closing this. Many optimizations have been done. Let's open a new issue if there are still some performance issues in the code.
