### ISSUE TITLE
A wrapper around prompt-toolkit to emulate tkinter api design

### ISSUE THREAD

**Issue by iogf** [jonathanslenders/python-prompt-toolkit#303]
Hello. I have been working on modal editor on top of tkinter
that shares with vim some similarities.

https://github.com/iogf/vy

It actually runs in a GUI, i'm planning to create a wrapper around ncurses that simulates tkinter API, so i could run vy on top of it by just changing some imports. what do you say of using your prompt-toolkit lib to build that wrapper?

**Comment by jonathanslenders** [comment]
Interesting project. For now, just be aware that the prompt-toolkit API for full screen applications is not stable, and will probably change in the coming years. It's good and powerful, but maybe not yet ready for what you want. However, have a look at pyvim. I made that as a demonstration of what will be possible and is already possible with prompt-toolkit.

**Comment by jonathanslenders** [comment]
Closing this.
Right now, by the way, the full screen API is much more stable. In case, you're interested, check out the documentation and the examples.
