### ISSUE TITLE
Keep getting the same window data when constructing windows dynamically

### ISSUE THREAD

**Issue by tony** [jonathanslenders/python-prompt-toolkit#306]
I am trying to rewrite the viewer for [what-studio/profiling](https://github.com/what-studio/profiling) in ppt @ https://github.com/what-studio/profiling/compare/master...tony:ppt-cleaned

I've managed to port some of the basic stuff from urwid, however, I've hit a stumbling block on how layout / window state work.

<img width="765" alt="screen shot 2016-05-29 at 6 07 58 am" src="https://cloud.githubusercontent.com/assets/26336/15632852/176885c0-2564-11e6-9687-eb1899f7d5be.png">

I'd expect that if I iterate through these stats, which I confirmed give me different results, I'd see different entries. However, I only seem to see one rendered.

https://github.com/tony/profiling/blob/ppt-cleaned/profiling/viewer.py#L709

Is there something wrong with how I'm approaching rendering this?

I've double and triple checked that I'm getting fresh data when I run ``for _stats in make_frozen_stats_tree(stats)``.

```python
class ViewerThing(object):
    def __init__(self):
        self._fc = FloatContainer(
            content=VSplit([
                Window(content=BufferControl(buffer_name=DEFAULT_BUFFER))]),
            floats=[
                Float(
                    content=Window(
                        height=D.exact(1),
                        content=FillControl('-', token=Token.Line)))
            ]
        )

        self.layout = HSplit([
            # The titlebar.
            Window(
                height=D.exact(1),
                content=TokenListControl(
                    self.get_titlebar_tokens, align_center=True)
            ),
            Window(
                height=D.exact(1),
                content=FillControl('-', token=Token.Line)),
            self._fc,
        ])

        self.widget = Application(
            layout=self.layout,
            buffers=buffers,
            key_bindings_registry=manager.registry,

            # Let's add mouse support!
            mouse_support=True,

            # Using an alternate screen buffer means as much as: "run full
            # screen". It switches the terminal to an alternate screen.
            use_alternate_screen=False)

        self.eventloop = create_eventloop()

    def loop(self, *args, **kwargs):
        kwargs.setdefault('unhandled_input', self.unhandled_input)
        self.cli = CommandLineInterface(application=self.widget,
                                        eventloop=self.eventloop)

        return self.cli

    def get_result(self):
        try:
            if self.paused:
                result = self._paused_result
            else:
                result = self._final_result
        except AttributeError:
            return
        return result

    def update_result(self):
        """Updates the result on the table."""
        result = self.get_result()
        if result is None:
            return

        self.update()
        self.cli.request_redraw()

    def update(self):

        def create_layout_from_stats():
            result = self.get_result()
            stats, cpu_time, wall_time, title, time = result
            if result is None:
                return VSplit([Window(
                    height=D.exact(1),
                    content=FillControl('-', token=Token.Line))])
            else:
                stats, cpu_time, wall_time, title, time = result
                panels = []

                for _stats in make_frozen_stats_tree(stats):
                    name = _stats[1][0]
                    if name is not None and 'run' in name:
                        continue
                    else:
                        assert name != 'run'
                        stat_line = ' | '.join(six.text_type(s) for s in _stats[1])
                        panels.append(Window(
                            height=D.exact(1),
                            content=TokenListControl(
                                lambda x: [(Token.Title, stat_line)], align_center=True)
                        ))
                return HSplit(panels)
        layout = create_layout_from_stats()
        self._fc.content = layout

```

**Comment by tony** [comment]
Ok, I'm starting to realize the approach of generating a windows to show the data may be wrong.  I will keep at it and report back.

I'm closing this for now.

**Comment by jonathanslenders** [comment]
Hi @tony,

I did not had the time yet to analyse the above code that you shared. But I'd like to say that improving the experience of developing full screen terminal UIs is somewhere at the top of my list.

While technically, prompt-toolkit is very capable to create nice looking UIs, there is room for improvement. The Pyvim and Pymux projects + some other experiments with widgets have given me a good idea of what needs to be done. Especially the way how the focus works, which is currently tied to the Buffer object instead of the UI needs to change. Also, it should be possible to define key bindings for a widget. It shouldn't be application wide with the ``HasFocus`` filter.

So, (without commitment) this is probably what I'll be working on during the coming months. If you want, I can keep you posted of all the improvements.

Jonathan
