### ISSUE TITLE
Missing Starting Newlines in Prompt

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#310]
Hello all, xonsh has noticed some weird behaviour with prompts that start with newlines not being rendered appropriately in all cases, specifically if there aren't other newlines and whitespace. For example a simple case that fails is:

```console
$PROMPT = '\n>>>'
```

xonsh renders this as `[(Token, '\n>>>')]` when passing it to ptk.

This was first reported by @tgoodlet in scopatz/xonsh#1052, where you can see more examples.

@gforsyth believes this to be caused by https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/shortcuts.py#L138

Any help would be really appreciated!

**Comment by jonathanslenders** [comment]
Hi @scopatz,

Thanks for reporting, that should be a bug, and could indeed be caused by that function. (thanks for giving the pointers.) I'll dive into this.

b.t.w: nice talk at Pycon US!

**Comment by jonathanslenders** [comment]
It was more challenging than expected, but finally solved: https://github.com/jonathanslenders/python-prompt-toolkit/commit/8258a98c1ce59c8c845c7b4b32b91b9204d2b596
Could you have a try?

**Comment by scopatz** [comment]
That seems to work great for me, @jonathanslenders! Thanks a ton.

> b.t.w: nice talk at Pycon US!

Thanks!  Folks were really impressed with ptk :)
