### ISSUE TITLE
ptipython is not working ok with ipython5.0b3

### ISSUE THREAD

**Issue by stonebig** [jonathanslenders/python-prompt-toolkit#317]
see
 https://github.com/ipython/ipython/issues/9548

![ptipython_ipython5b3](https://cloud.githubusercontent.com/assets/4312421/15983864/7fd87c68-2fb5-11e6-98ae-dcb3e77f82ce.PNG)

**Comment by jonathanslenders** [comment]
Thanks for creating the issue here!

**Comment by jonathanslenders** [comment]
Probably this should fix it: https://github.com/jonathanslenders/ptpython/pull/125

**Comment by stonebig** [comment]
it works indeed !
![ptipython_ipython5b3_ok](https://cloud.githubusercontent.com/assets/4312421/15992944/1b0534be-30d9-11e6-8a56-a86fa796bbcb.PNG)
