### ISSUE TITLE
pymux can't start with prompt_toolkit-1.0.3

### ISSUE THREAD

**Issue by cwt** [jonathanslenders/python-prompt-toolkit#329]
I install pymux with command "pip install pymux", which it will download the latest version of prompt_toolkit (1.0.3), which it can't start.

I have to downgrade prompt_toolkit back to 1.0.0 in order to make pymux working again.

Please see me screen cast here: https://asciinema.org/a/50238

**Comment by jonathanslenders** [comment]
Hi @cwt,

Thanks for notifying me! I just released a new version of pymux. (0.11) Could you try to reinstall pymux? ``pip install -U pymux``?

Thanks!

**Comment by cwt** [comment]
Yeah! it's working now. Thanks.
