### ISSUE TITLE
Ctrl-z should background processes on windows.

### ISSUE THREAD

**Issue by melund** [jonathanslenders/python-prompt-toolkit#341]
One loose control of the shell when foregrounding application on windows. 
```
snail@sea ~\Documents\AnyPyTools\Tutorial
$ fg 1
[1]+ running: jupyter notebook (11768)
```
The only way to recover is to kill the process. 

Since suspending processes doesn't work on windows, I suggest that ctrl-z should instead just background it and give the console back to the user.

**Comment by jonathanslenders** [comment]
Hi @melund,

What do you mean by "background process"?
Is there any Windows application doing this?

Right now, it is ignored on Windows: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/interface.py#L744

Jonathan

**Comment by melund** [comment]
He he. I posted on the wrong project. It was a xonsh issue :) Bad habbit of quickly posting the issue not to forget. And   the prompt_toolkit  github page was open in a tab. Sorry for the confusion..

**Comment by jonathanslenders** [comment]
No problem!
