### ISSUE TITLE
Styling an editing buffer?

### ISSUE THREAD

**Issue by bobburnham** [jonathanslenders/python-prompt-toolkit#342]
This is a very cool toolkit. I would like to make a very simple full-screen application to view code and going through the examples I have been able to style small Token objects like this:

```
style = style_from_dict({
    Token.Toolbar: '#ffffff bg:#00cccc',
    Token.Line: '#cccccc'
})

layout = HSplit([
    Window(content=BufferControl(buffer_name=DEFAULT_BUFFER)),
    Window(height=D.exact(1),
           content=FillControl(unichr(9608), token=Token.Line)),
    Window(height=D.exact(1),
           content=TokenListControl(get_bottom_toolbar_tokens, align_center=True,
                                    default_char=Char(' ', Token.Toolbar)))
])
```

Is there a way to style the main window, i.e. the DEFAULT_BUFFER? I have been looking through the pyvim and pymux code, but have not been able to figure it out just yet.

Thank you.

**Comment by biermeester** [comment]
I just started to use ppt and since I had the same question _and_ found the answer, I thought I'd share it here.

To style the content of your `DEFAULT_BUFFER`, create a lexer and assign it to the `BufferControl`. This will style the content of the buffer. The empty space around the content can be styled using a `Char`.

```python
BufferControl(
    buffer_name=DEFAULT_BUFFER,
    lexer=SimpleLexer(Token.SomeToken),  # See the lexer module for more details
    default_char=Char(' ', Token.SomeOtherToken),
)
```

**Comment by jonathanslenders** [comment]
Hi both, that worked indeed for prompt_toolkit 1.0
Now that we have 2.0 released, many more ways of styling are possible. Check the docs. ;)
Also, closing this now.
