### ISSUE TITLE
Implement readline's `yank-last-arg`

### ISSUE THREAD

**Issue by pkgw** [jonathanslenders/python-prompt-toolkit#343]
The implementation of readline's `yank-last-arg` command [is currently a TODO](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/emacs.py#L298). It would be good for it to actually get implemented!

**Comment by haridsv** [comment]
How about creating a patch based on [this gist](https://gist.github.com/haridsv/7b8ea0a6861582b1bc0b6997f075b980) ? I doesn't currently cycle back to the beginning, but it should be easy to modify it. It is also not identical to the readline's behavior, specifically on how readline recalls arguments from `(n-1)th` item if you are currently at `nth` item, but honestly, I prefer always starting from `-1` irrespective of where you are in the history.

@jonathanslenders

**Comment by haridsv** [comment]
The gist also takes care of `yank-nth-arg`, though I noticed that the issue #359 makes it less useful.

**Comment by adamchainz** [comment]
Thanks for the gist! I adapted it into my implementation in #407 which uses function 'local' variables rather than a separate state and also deduplicates on repeat presses like readline does.

**Comment by jonathanslenders** [comment]
Thanks everyone for the pull requests! So far, I did not had any time yet to review/merge this functionality, but I hope to do it soon. It's very useful!

**Comment by jonathanslenders** [comment]
Hi everyone, this functionality has been mergen in https://github.com/jonathanslenders/python-prompt-toolkit/commit/0c09bf034aeeb2facbfbc070cc4fa2f58620baa5

If you have time, could you have a look and see whether it works?

Jonathan

**Comment by amitkot** [comment]
Can this useful feature be used with vi binding as well?

I'm using Xonsh and for the time being I added this binding:
```python
@events.on_ptk_create
def custom_keybindings(bindings, **kw):

    @bindings.add('escape', '.')
    def yank_last(event):
        event.current_buffer.yank_last_arg()
```

**Comment by adamchainz** [comment]
Please don’t comment on **eight year old** issues. Instead, open a new one referencing this one...
