### ISSUE TITLE
vi-mode digraphs could search for the "swapped" digraph

### ISSUE THREAD

**Issue by anntzer** [jonathanslenders/python-prompt-toolkit#356]
From the Vim docs:
> If a digraph with {char1}{char2} does not exist, Vim searches for a digraph
{char2}{char1}.  This helps when you don't remember which character comes
first.

This would be nice to have here too.  (It actually took me a while to figure out that PTK does support digraphs and that I memorized quite a few of them in the wrong order... :-))

**Comment by jonathanslenders** [comment]
Hi @anntzer,

Thank you for pointing this out! It has been implemented in the following commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/572198f15616935247f2d01275f05af3a1efd1f1

Cheers,
Jonathan
