### ISSUE TITLE
Additional text objects (vi-mode)

### ISSUE THREAD

**Issue by anntzer** [jonathanslenders/python-prompt-toolkit#357]
These are not standard but could be useful too:

https://github.com/vim-scripts/argtextobj.vim

> This plugin provides a text-object 'a' (argument). You can
> d(elete), c(hange), v(select)... an argument or inner argument in familiar ways.
> That is, such as 'daa'(delete-an-argument) 'cia'(change-inner-argument) 'via'(select-inner-argument).
> What this script does is more than just typing
>   F,dt,
> because it recognizes inclusion relationship of parentheses.

https://github.com/michaeljsmith/vim-indent-object

> a new text object representing lines of code at the same indent level. Useful for python/vim scripts, etc.

**Comment by jonathanslenders** [comment]
This is an example of how custom text objects can be added to any prompt_toolkit application in 2.0: https://github.com/jonathanslenders/python-prompt-toolkit/blob/70dc3769e2da8daa54cebd2db24307527962700e/examples/prompts/custom-vi-operator-and-text-object.py

I don't plan on adding non standard text objects to prompt toolkit, so I hope you don't mind I close this issue.
