### ISSUE TITLE
Stop replacing \r with \n

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/python-prompt-toolkit#358]
See: https://github.com/jonathanslenders/pymux/issues/49

**Comment by haridsv** [comment]
Thank you, @jonathanslenders! Note that you would also need to clear additional flags while switching to raw mode, e.g.,:

```
newattr[tty.IFLAG] &= ~(termios.INLCR | termios.ICRNL | termios.IGNCR)
```

I confirmed that the current setup is not enough as the terminal driver would have already done the switch by the time we would see the key.

**Comment by jonathanslenders** [comment]
Thank you! I didn't know about this.

**Comment by haridsv** [comment]
Here is what the [termios man page](http://linux.die.net/man/3/termios) says about these flags:

```
INLCR
Translate NL to CR on input.

IGNCR
Ignore carriage return on input.

ICRNL
Translate carriage return to newline on input (unless IGNCR is set).
```

**Comment by jonathanslenders** [comment]
The flags were added in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/5400d0f5fe55b1174d4f6f5f4c23aef69653de37

+ I added a comment to fix this in the future version. (That will be prompt-toolkit 2.0.0.)

**Comment by jonathanslenders** [comment]
This has been fixed, so I'm closing this issue. Feel free to open again if needed.
