### ISSUE TITLE
Negative argument needs to be supported for cursor movement commands

### ISSUE THREAD

**Issue by haridsv** [jonathanslenders/python-prompt-toolkit#361]
Readline supports reversing the direction of the cursor movement with a -ve argument. I.e., `<Esc>-f` with `-2` as argument is same as `<Esc>-b` with `2` as the argument. The same seems to also work for others, like left and right arrow keys.

**Comment by jonathanslenders** [comment]
Hi @haridsv,
Thanks for the request. I think the following pull request should do it: https://github.com/jonathanslenders/python-prompt-toolkit/pull/379
But before merging, I need some time for testing this a bit more and writing unit tests.

**Comment by jonathanslenders** [comment]
Implemented in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/316e28702c155ec636e8197acc65878b341ba9a9
Unit tests: https://github.com/jonathanslenders/python-prompt-toolkit/commit/c05010b094fe301c028808e2a51bc40bf0b83713

**Comment by haridsv** [comment]
This seems to work well for reversing the backward movement (`Esc+b`), but the same for forward movement has some issue, perhaps a minor "off-by-one" type of issue. To reproduce, say you enter:

abc def ghi

and start typing `Alt+-` `f` sequence repeatedly, first you end up with cursor on "g" which is correct, but next time you are left at the space in front of "g" and then it gets stuck there. If you instead type `Alt+-2` `f`, then the cursor is correctly positioned on "d".

Also noticed that, if you type `Alt+-3` `f`, instead of moving to the beginning, the cursor doesn't move at all.
