### ISSUE TITLE
Parts of remaining substring inserted/removed when attempting code completion

### ISSUE THREAD

**Issue by the-holger** [jonathanslenders/python-prompt-toolkit#370]
I hope this is the right place for this issue, I noticed it while using the jupyter console.

I noticed that when starting to type e.g. a variable name or a package name and then using code completion, additional characters are inserted (i.e. parts of e.g. the file name are repeated) depending on previous tab completions. Steps to reproduce and screenshot below.

I'm running prompt_toolkit 1.0.5 and jupyter-console 5.0.0 on an Anaconda installation of Python 3.5.2 on Mac OS X (10.11.6).

Example:
1. >>> from pyramid.c <tab> completes to >>> from pyramid.co, showing a dropdown with the two options "pyramid.compat" and "pyramid.config" 
2. Selecting either of them results in from pyramid.cod.compat or pyramid.cod.config
3. >>> from pyramid.co <tab> opens the dropdown, the completion by selecting one of the options works though.

Same thing happens with variable names with underscores present:
1. >>> variable_name_one = 1
2. >>> variable_name_two = 2
3. vari <tab> completes to variable_name_ and opens the dropdown showing both names
4. Selecting either of them results in variable_name_le_name_xxx

When completing from a different position in the name:
5. varia <tab> completes to variable_name_ and opens the dropdown showing both names
6. Selection either results in variable_name_able_name_xxx

variable_name_ <tab> and selecting from the dropdown works though.
I'm absolutely clueless what might trigger that behaviour, so again: I'm sorry if jupyter-console is the wrong place to report that.

Cheers!
Holger

<img width="650" alt="screen shot 2016-08-09 at 19 28 12" src="https://cloud.githubusercontent.com/assets/1640406/17526437/8eed0742-5e67-11e6-9743-112803748205.png">

**Comment by mikenerone** [comment]
I was seeing something similar, and I did some tests using ipython. I created a situation where the only two matches for these tests are `thing_one` and `thing_two`.

- `th[TAB]`: partial-completes to `thing_`, but cycles between the two matches `thing_ing_one` and `thing_ing_two`. It's as if prompt_toolkit forgot that it already filled in the portion common to both matches and is re-appending it. Unfortunately, this doesn't stay consistent...
- `thi[TAB]`: partial-completes to `thing_`, but now cycles between `thing_thing_one` and `thing_thing_two`. As if its forgotten there was a partial completion at all, _including_ the portion I had typed.
- `thin[TAB]`: partial-completes to `thing_`, but now cycles between `thing_ne` and `thing_wo`. In this case, it actually _drops_ the initial character from the remaining match, so it's not as simple as saying it adds additional parts (@the-holger, you might update the subject line of this issue).
- `thing[TAB]`: partial-completes to `thing_`, but now cycles between `thing__one` and `thing__two`. This appears similar to the `th[TAB]` case above, where it's re-appending the part it already partial-completed.
- `thing_[TAB]`: match completion works correctly

**Comment by the-holger** [comment]
Thanks @mikenerone, I completely missed that when I wrote up the issue.
I'm really completely lost why this happens - apparently this isn't a widespread issue, as the first reaction to my post was after 9 days (in which I have gone bonkers because ipython is pretty much unusable).

**Comment by the-holger** [comment]
Just repeated @mikenerone's steps. Reproduced all on Python 3.5.2 |Anaconda custom (x86_64)| IPython 5.0.0 on **macOS 10.12 Beta 6**

**Comment by jonathanslenders** [comment]
See also: https://github.com/ipython/ipython/issues/9865#issuecomment-240909163

I think that the following commit fixes it: jonathanslenders/python-prompt-toolkit@970c763
Could checkout prompt_toolkit master and try again?
Thanks for reporting!

**Comment by theychx** [comment]
> Could checkout prompt_toolkit master and try again?

I just repeated @mikenerone's steps, it seems to be working properly now.

**Comment by the-holger** [comment]
With commit [@970c763](https://github.com/jonathanslenders/python-prompt-toolkit/commit/970c763) installed I cannot reproduce the bug anymore.

What a relief! Thank you @jonathanslenders !

**Comment by mikenerone** [comment]
Confirmed fixed in 1.0.7. Thanks much!
