### ISSUE TITLE
Multiline paste not fully displayed, starting 1.0.4

### ISSUE THREAD

**Issue by ushuz** [jonathanslenders/python-prompt-toolkit#371]
Install `ipython` in a fresh virtualenv, `prompt-toolkit-1.0.5` will be installed, paste multiline text  into ipython, only the first line will be displayed. Any multiline text can be used to reproduce, below is what I used.

```
I was wondering if bracketed past was there mostly for security reasons or not. 

And if so I was wondering, would it be also possible/desirable, when you past something we could/should have an overlay highlighter that mark non-ascii caracters with specific token with a different visual style. 
Thus decreasing chances of pastjacking.
```

The problem appears in 1.0.4, can be solved by installing 1.0.3. 

I'm using iTerm2 3.0.7, OSX 10.11.6.

![image](https://cloud.githubusercontent.com/assets/1430856/17551650/f3d8399e-5f2d-11e6-8268-2912935a5349.png)

**Comment by jonathanslenders** [comment]
Hi @ushuz,

This should be the same issue as https://github.com/ipython/ipython/issues/9737 (and the related issues.) Can you try again after upgrading to prompt_toolkit 1.0.6? (Released today.)

**Comment by jonathanslenders** [comment]
Highlighting non-ascii characters would certainly be possible. (By adding a custom layout Processor.) But this is not something we will do by default. Many users use non-ascii characters every day.

Bracketed paste adds some security, but it also allows us to paste multiline text without interpreting the enter key as an "execute" command. See this article: https://cirw.in/blog/bracketed-paste

**Comment by ushuz** [comment]
@jonathanslenders I installed ipython 5.1.0 and prompt-toolkit 1.0.6, the problem was fixed, thanks.
