### ISSUE TITLE
ImportError with pytest: ImportError: cannot import name 'DEFAULT_STYLE'

### ISSUE THREAD

**Issue by gardiac2002** [jonathanslenders/python-prompt-toolkit#375]
My _prompt-toolkit_ script works wonderful when I run it as a command line application. 
However, when I run my tests with _pytest_  I get the following ImportError: cannot import name 'DEFAULT_STYLE'. 

**Versions and plugins:**
- prompt-toolkit: 1.0.5
- pytest: 2.9.1
- Python 3.5.2

Pytest Plugins:
- pytest-timeout-1.0.0 
- pytest-cov-2.2.1
- pytest-xdist-1.14 

**Error message:**
```
ama/cli.py:37: in <module>
    from prompt_toolkit.contrib.completers import WordCompleter, PathCompleter
/usr/local/lib/python3.5/dist-packages/prompt_toolkit/__init__.py:16: in <module>
    from .interface import CommandLineInterface
/usr/local/lib/python3.5/dist-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
/usr/local/lib/python3.5/dist-packages/prompt_toolkit/interface.py:19: in <module>
    from .application import Application, AbortAction
/usr/local/lib/python3.5/dist-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
/usr/local/lib/python3.5/dist-packages/prompt_toolkit/application.py:15: in <module>
    from .styles import DEFAULT_STYLE, Style
E   ImportError: cannot import name 'DEFAULT_STYLE'
```

**Comment by davidszotten** [comment]
See #383. As a workaround you can (uninstall and) install with `pip install --no-use-wheel`

**Comment by jonathanslenders** [comment]
Hi @gardiac2002,

Can you have a look again, after installing the latest prompt_toolkit version. Normally it should be fixed now.

**Comment by gardiac2002** [comment]
@jonathanslenders , 
thank you for fixing this issue. The import worked fine!
