### ISSUE TITLE
Force an app to use 16 basic ANSI colours

### ISSUE THREAD

**Issue by krigstask** [jonathanslenders/python-prompt-toolkit#376]
Is there any way to force an application using *prompt-toolkit* to use only basic 16 colours? For example, this is how ''mycli'' session looks now in my iTerm2 with pretty famous [dark Solarized colour scheme](http://ethanschoonover.com/solarized)
![screen shot 2016-08-10 at 16 44 25](https://cloud.githubusercontent.com/assets/419654/17555967/a969a588-5f22-11e6-8113-ccfd9bc3bb62.png)
Note practically unreadable blue table names :(

And that's how my terminal looks usually:
![screen shot 2016-08-10 at 16 46 55](https://cloud.githubusercontent.com/assets/419654/17555970/abba1f34-5f22-11e6-852d-232838c07658.png)

![screen shot 2016-08-10 at 16 52 42](https://cloud.githubusercontent.com/assets/419654/17556122/511d7dd6-5f23-11e6-9e6e-4673d0278018.png)

I know that I can change colour scheme to my liking, but I would really prefer to just tell *mycli*/*prompt-toolkit* "Stick to basic colours" and have it always respecting my terminal settings.

For example, this could be controlled with environment variable like `$PROMPT_TOOLKIT_USE_256_COLOURS` (defaulting to true).

**Comment by jonathanslenders** [comment]
Hi @krigstask,
Prompt_toolkit 1.0.6 has been released today and I included a fix. When ``$PROMPT_TOOLKIT_ANSI_COLORS_ONLY=1`` was set, it should use the 16 ANSI colors only. Let me know whether this works.

**Comment by krigstask** [comment]
Awesome, thanks a lot!  I've read the notification late at night, went to sleep full of hope, and after coming to work...
![screen shot 2016-08-16 at 11 08 56](https://cloud.githubusercontent.com/assets/5174481/17692328/46df4e5e-63aa-11e6-8654-6935c465cb44.png)

Exactly what I was hoping for!  Thanks again.

**Comment by jonathanslenders** [comment]
You're welcome! :)
