### ISSUE TITLE
Please tag 1.0.6

### ISSUE THREAD

**Issue by jakirkham** [jonathanslenders/python-prompt-toolkit#381]
Could we please get a tag for the 1.0.6 release? Thanks.

**Comment by jonathanslenders** [comment]
Done. Thanks for reminding me!

**Comment by jakirkham** [comment]
Awesome. Thanks. Closing...

**Comment by jakirkham** [comment]
Just as FYI, we are building this package in [conda-forge]( https://conda-forge.github.io ). This is the [feedstock]( https://github.com/conda-forge/prompt_toolkit-feedstock ) we use to build it. We have been using GitHub tags to build `prompt_toolkit` hence the interest in having one for this release. If you have any interest in helping out in the effort, we would certainly appreciate having you as a maintainer. 😄
