### ISSUE TITLE
wheel package issue

### ISSUE THREAD

**Issue by davidszotten** [jonathanslenders/python-prompt-toolkit#383]
Hi,

It looks like something may have gone wrong during the building of the wheels (at least for the latest version, 1.0.6, which is the only one i've checked)

the wheel seems to include modules with the same name as a bunch of (sub-)packages, e.g.

`prompt_toolkit/styles.py` next to `prompt_toolkit/styles/*`

this mostly works since packages win during regular import, but it confuses e.g. pytest assertion re-writing (c.f. #375) and of course doesn't match the source or the source distro

**Comment by jonathanslenders** [comment]
Hi @davidszotten,

Thanks for pointing this out! There was indeed something wrong there. I'm not sure how it happened, but I see that at least a few other files were included. I'll make sure to remove all files locally, before building a wheel. Now, I released 1.0.7, with a few fixes, and this looks better.

Can you try the new wheel packages for 1.0.7?

**Comment by davidszotten** [comment]
look good, thanks!

btw, i have had pretty good success using travis to build and upload to pypi: https://docs.travis-ci.com/user/deployment/pypi/
