### ISSUE TITLE
Autocompletion fails with colon ":" character

### ISSUE THREAD

**Issue by lambdamusic** [jonathanslenders/python-prompt-toolkit#386]
I noticed that if I put strings including a colon in the autocomplete list, the autocomplete doesn't work as expected (it stops when it reaches the colon). 

E.g. based on the official [autocompleter example](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/autocompletion.py) I have set up a list like this:

```
completer = WordCompleter(['xml:Literal', 'xml:String', 'xml:Integer', '....'])
```

Is there any parameter I should tweak in order to make this work? 

Thanks

**Comment by jonathanslenders** [comment]
Hi @lambdamusic,
For this, pass the ``WORD=True`` parameter to ``WordCompleter``. That should do the job.

**Comment by lambdamusic** [comment]
Awesome thanks!
