### ISSUE TITLE
get_input won't respond to some Chinese characters.

### ISSUE THREAD

**Issue by deangl** [jonathanslenders/python-prompt-toolkit#389]
Simply use a example in windows, 
``` python
from prompt_toolkit.shortcuts import get_input
 
if __name__ == '__main__':
    answer = get_input('Give me some input: ')
    print('You said: %s' % answer)
```
When I try to input characters like '开', It dose not respond.

**Comment by deangl** [comment]
can be patched as follow. Don't know if has other side effect.
``` python
import prompt_toolkit.terminal.win32_input as win32_input
with open(win32_input.__file__, 'r') as source:
    patched = source.read().replace('ascii_char in self.mappings', 'u_char.encode("utf8") in self.mappings')
with open(win32_input.__file__, 'w') as source:
    source.write(patched)
```

**Comment by jonathanslenders** [comment]
Hi @deangl,

Thanks for reporting this bug and proposing the solution!
I'll try asap to replace that line. (My Windows machine crashed recently, so I'm waiting for a replacement right now.)

**Comment by jonathanslenders** [comment]
Hi @deangl,

I'm trying this fix. How do you manage to enter chinese characters in cmd.exe? I can type chinese in notepad (using MS pinyin), but for some reason it doesn't work in notepad.

Secondly, could you tell me which value ``ascii_char`` has when you try to type 开? I'd like to understand what's going on. I guess that for some multibyte characters, Windows sends the first byte in the ASCII value, but I'm not sure.

**Comment by deangl** [comment]
Hi Jonathan,
When I use MS pinyin, it looks like this.
![image](https://cloud.githubusercontent.com/assets/12607057/19105882/07dff048-8b17-11e6-831b-38db553a6c4e.png)

and in line 222, 
u_char is: 开
ascii_char is: b'\x00'

**Comment by jonathanslenders** [comment]
Hi @deangl,

This should be fixed in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/5ab81d7aa5a8081725fd21563b489713719ab7dd
Could you try the latest prompt_toolkit master?
Thanks.

**Comment by deangl** [comment]
Hi @jonathanslenders 

Seems it works well now. Thank :)

**Comment by stonebig** [comment]
time for a 1.0.8 ?

**Comment by jonathanslenders** [comment]
@stonebig @deangl @lv-gh @takluyver : 1.0.8 has been released with this fix.
Please let me know if you experience any issues!

Thanks,
Jonathan
