### ISSUE TITLE
Implement M-y and kill-ring

### ISSUE THREAD

**Issue by jarvisschultz** [jonathanslenders/python-prompt-toolkit#414]
Ever since upgrading to IPython 5.1 I've been bothered by M-y not working. I finally got around to doing some research and came across [this comment](https://github.com/ipython/ipython/issues/9425#issuecomment-215948436) from @jonathanslenders that mentions `python-prompt-toolkit` doesn't yet have an equivalent of a "kill-ring" and that `M-y` is unimplemented. Are there plans to support this feature?

**Comment by jonathanslenders** [comment]
Hi @jarvisschultz,

Yes, I'm definitely willing to implement this, but I need a little help. I'm a Vi user myself, and don't have a very deep understanding of how Emacs and Readline's Emacs mode works.

So, if you could describe which key bindings need to be implemented, and how exactly they should behave, then probably I could do that.

Thanks,
Jonathan

**Comment by mgalgs** [comment]
@jonathanslenders There's an example of how cycling the kill ring works (which is what `M-y` does) on [this question](http://stackoverflow.com/q/39654820/209050).  Thank you for considering it.

**Comment by jarvisschultz** [comment]
It seems to me that Emacs' implementation of the kill ring is slightly more advanced than the one that readline implements. Emacs' `yank-pop` command accepts a numeric argument on many times to cycle the `kill-ring`. My Bash man page (v4.3 Feb 2, 2014.... [this link](https://linux.die.net/man/1/bash) provides a matching copy) doesn't mention this ability, and it doesn't seem to work on my machine.

For reference, here are the relevant lines from my Bash man page:

- From the **Readline Notation** section:

```
When a command is described as killing text, the text deleted is saved for
possible future retrieval (yanking). The killed text is saved in a kill ring.
Consecutive kills cause the text to be accumulated into one unit, which can be
yanked all at once. Commands which do not kill text separate the chunks of text
on the kill ring.
```

- From  the **Killing and Yanking** section:
```
yank (C-y)
       Yank the top of the kill ring into the buffer at point.
yank-pop (M-y)
       Rotate the kill ring, and yank the new top. Only works following yank or yank-pop.
```

The official Emacs documentation is more complex, but more thorough. Specifically, the behavior is described on the [Yanking page](https://www.gnu.org/software/emacs/manual/html_node/emacs/Yanking.html), and the three child pages

1. [Kill Ring](https://www.gnu.org/software/emacs/manual/html_node/emacs/Kill-Ring.html#Kill-Ring)
2. [Earlier Kills](https://www.gnu.org/software/emacs/manual/html_node/emacs/Earlier-Kills.html#Earlier-Kills)
3. [Appending Kills](https://www.gnu.org/software/emacs/manual/html_node/emacs/Appending-Kills.html#Appending-Kills)

**Comment by mgalgs** [comment]
> My suspicion is the readline behavior is sufficient for most use cases (it certainly is for mine).

Indeed it is.  No need to implement prefix arguments or `append-next-kill`.

**Comment by mgalgs** [comment]
While we're at it, another one that I've missed sorely is `yank-last-arg (M-., M-_)`:

```
     yank-last-arg (M-., M-_)
          Insert the  last argument to the  previous command (the
          last  word  of the  previous  history  entry).  With  a
          numeric  argument,  behave exactly  like  yank-nth-arg.
          Successive calls to yank-last-arg move back through the
          history  list, inserting  the  last word  (or the  word
          specified by  the argument to  the first call)  of each
          line in  turn.  Any numeric argument  supplied to these
          successive  calls  determines  the  direction  to  move
          through the history.  A  negative argument switches the
          direction through  the history (back or  forward).  The
          history expansion  facilities are  used to  extract the
          last  argument, as  if the  "!$" history  expansion had
          been specified.
```

I'd be fine if there was no numeric argument support, but cycling backwards with successive `M-.`'s would be critical.

Not sure if you'd like that as a separate issue?

**Comment by jonathanslenders** [comment]
Thank you for all the feedback! This is great. yank-last-arg has been implemented for the last release: https://github.com/jonathanslenders/python-prompt-toolkit/commit/0c09bf034aeeb2facbfbc070cc4fa2f58620baa5

**Comment by jonathanslenders** [comment]
I just learned how to use ``yank`` and ``yank-pop``. This is not going to be too hard to implement.

**Comment by jonathanslenders** [comment]
Hi everyone, I think I have the implementation. It's in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/46d07b00530e76eee8126d38ecb3f9c043bf2eae

Could you all try to clone the latest master commit, and see whether it works?

**Comment by jarvisschultz** [comment]
Working as expected here... Thanks!

**Comment by mgalgs** [comment]
Also confirmed! Thank you!

**Comment by jonathanslenders** [comment]
Thanks @jarvisschultz  and @mgalgs for testing!

Closing this issue now. Feel free to reopen if I forgot anything, or create a new issue if you notice any issue.
