### ISSUE TITLE
Unable to implement redo in ipython 5.0.0

### ISSUE THREAD

**Issue by infokiller** [jonathanslenders/python-prompt-toolkit#419]
I tried implementing a redo keybinding but failed.
I'm not sure why, but it seems like the _redo_stack member is being reset, even though I pass `save_before=lambda x: False` when calling `add_keybinding` on the `key_bindings_registry`.

Code I'm running in ipython:
```python
from IPython import get_ipython
from prompt_toolkit.keys import Keys

def undo(event):
  event.current_buffer.undo()
  # This line prints a non-empty redo stack
  print 'redo stack: {}'.format(event.current_buffer._redo_stack)

# Bind Alt+_ to undo
get_ipython().pt_cli.application.key_bindings_registry.add_binding(Keys.Escape, u'_', filter=True, save_before=lambda x: False)(undo)
```

After running that code, I typed something in the prompt and then invoked `Alt+_` to trigger the undo, which printed a non-empty redo stack.
However, the redo stack of all buffers look empty. To see this I'm running the following:

```python
for b in get_ipython().pt_cli.application.buffers.values():
  print b._redo_stack
```

**Comment by asmeurer** [comment]
It looks like the `save_to_undo_stack()` function gets called all the time in the input_processors because of the constant handling for CPRResponse (by the way, is this being called constantly a performance issue?), and it always clears the redo state.

**Comment by asmeurer** [comment]
Fix at https://github.com/jonathanslenders/python-prompt-toolkit/pull/484.
