### ISSUE TITLE
print_tokens() does not support file= kwarg

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#421]
Ideally the `print_tokens()` would support all of the kwargs as the Python `print()` function. I am not entirely sure if this is possible given console behaviour on windows.

**Comment by jonathanslenders** [comment]
Hi @scopatz,

I just added the file argument: https://github.com/jonathanslenders/python-prompt-toolkit/commit/fcaa8e303effe9b56cbc877aa106ddfe34ce818c

For the other arguments, I'm not sure whether they make sense. (I could be wrong.)

**Comment by scopatz** [comment]
Thanks! File is the only one I really cared about :)
