### ISSUE TITLE
ansi* color names not working in 1.0.9

### ISSUE THREAD

**Issue by jesaerys** [jonathanslenders/python-prompt-toolkit#423]
ANSI color names (e.g., `#ansired`, `#ansiblue`, etc.) don't seem to be working as of version 1.0.9. For example, adding the following to ipython_config.py results in a blue IPython prompt with prompt_toolkit version 1.0.8:

```python
c.TerminalInteractiveShell.highlighting_style_overrides = {
    Token.Prompt: '#ansiblue', Token.PromptNum: '#ansiblue bold'}
```

But in version 1.0.9, the prompt text is just white. Note that hex colors still work as expected.

**Comment by jonathanslenders** [comment]
@jesaerys Thanks for reporting!

See also: https://github.com/jonathanslenders/python-prompt-toolkit/pull/408 and https://github.com/jonathanslenders/python-prompt-toolkit/pull/418

@melund @Carreau Does maybe any of you know what happened? If not, I'll have a look.

**Comment by melund** [comment]
No idea. Maybe check that pygments master is still installed. That gave me similar issues.

**Comment by jonathanslenders** [comment]
Actually, I can't reproduce the issue. I'm using the latest IPython and tested with prompt_toolkit 1.0.9 and master. (Tested using Ubuntu Linux.)

@jesaerys:
- What operating system are you using?
- Which Python version?
- Which IPython version. (pip freeeze|grep -i ipython)
- In the case of Mac/Linux: What terminal are you using?

**Comment by jesaerys** [comment]
@jonathanslenders 

- OS X 10.11.6
- Python 3.5.2
- IPython 5.1.0
- iTerm2 3.0.12

I was just playing with this again and I have to slightly restate the issue: the ansi color names *are* working 1.0.9, but the bold switch causes the "bold" color variant to be applied to the entire token. (The reason I thought the colors weren't working is because I was using a Base16 theme for which bold variants are assigned grayscale values.)

Here is a simple test to illustrate:

First, use the following ipython_config.py (notice that the number token uses the bold switch):
```python
from IPython.terminal.prompts import Token
c.TerminalInteractiveShell.highlighting_style_overrides = {
    Token.Prompt: '#ansiblue', Token.PromptNum: '#ansiblue bold'}
```

Quit and reopen iTerm2, and create a vertical split.

On the left side,
```console
$ conda create -n mytest1 -y ipython prompt_toolkit=1.0.8
$ source activate mytest1
(mytest1)$ ipython
```

On the right side,
```console
$ conda create -n mytest2 -y ipython prompt_toolkit=1.0.9
$ source activate mytest2
(mytest2)$ ipython
```

On the left side (ver 1.0.8), the prompt `In [1]: ` has all text colored "blue" (whatever color is assigned to ANSI index 4) with the `1` set in bold.

On the right side (ver 1.0.9), the prompt has all text colored "bold/bright blue" (whatever color is assigned to ANSI index 12) with the `1` set in bold.

If you then go into iTerm2 preferences, you can tweak the values of ANSI 4 and ANSI 12 and watch the prompts change color on the left and right sides, respectively.

**Comment by jesaerys** [comment]
I should note that the left-side case (ver 1.0.8) is the behavior I expect for the given ipython_config.py file. It's unintuitive to me that setting bold on `PromptNum` would 1) use bright variant of the named color (ANSI 12 instead of ANSI 4) and 2) apply that same color to `Prompt` despite me setting it explicitly.

**Comment by melund** [comment]
#ansiblue is the bright color. The darker version is called #ansidarkblue. The colors being swapped was a bug in 1.0.8.. I don't know what is up the bold stuff you are seeing

**Comment by jesaerys** [comment]
@melund Aha! That's the key. In 1.0.8, `#ansiblue` maps to ANSI 4 and `#ansidarkblue` maps to ANSI 12. In 1.0.9, it's the exact opposite. I didn't see anything in the change log about the naming convention being switched, so it never occurred to me to look in terminal/vt100_output.py where I would have noticed this change.

My comments about the bold switch were a red herring.

Sorry for the trouble, and thanks for clearing this up!

**Comment by melund** [comment]
No problem. Glad you got it sorted.
