### ISSUE TITLE
There's a minor typo in `full_screen_apps.rst`

### ISSUE THREAD

**Issue by yieks** [jonathanslenders/python-prompt-toolkit#424]
In the doc named `full_screen_apps.rst`, it currently says...

We’ll come back at what the `Application` instance is later.

It should probably be...

We’ll come back **to** what the `Application` instance is later.

**Comment by jonathanslenders** [comment]
Thank you @yieks. This was fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/3d4a61d4dca2cfa5792e2be7d16baa9d0ebbc017
