### ISSUE TITLE
Possibility to add custom key binding for repeated "regular key press"

### ISSUE THREAD

**Issue by fogine** [jonathanslenders/python-prompt-toolkit#425]
I'd like to map `jj` key sequence so that it'd switch me to vi command mode:

```python
manager = KeyBindingManager.for_prompt()

@manager.registry.add_binding('jj', eager=False)
def _(event):
    buffer = event.current_buffer
    vi_state = event.cli.vi_state

    vi_state.reset(InputMode.NAVIGATION)

    if bool(buffer.selection_state):
        buffer.exit_selection()
```

Is that currently possible?

The event handler seems to be triggered only for single key press, the following works as expected:
```python
@manager.registry.add_binding('j', eager=False) # single `j` press
def _(event):
 # logic which gets tiggered
```

Thank you for your amazing work!

**Comment by jonathanslenders** [comment]
Hi @fogine ,

Can you try this:
```python
@manager.registry.add_binding('j', 'j', eager=False)
```
The value for ``eager`` probably doesn't matter in this case and can actually be removed.

**Comment by jonathanslenders** [comment]
Also see this commit to see how "jj" could be implemented. (It was actually done before, for pyvim.)

https://github.com/jonathanslenders/pyvim/commit/6729289

**Comment by fogine** [comment]
Thank you very much @jonathanslenders  for your quick and excellent response!

**Comment by jonathanslenders** [comment]
You're welcome! :-)
