### ISSUE TITLE
[Question] Possible to split panes and still use prompt?

### ISSUE THREAD

**Issue by SamStudio8** [jonathanslenders/python-prompt-toolkit#429]
Not sure if this is a trivial question but I can't seem to find an answer in the documentation. I'm looking for a compromise between using `prompt-toolkit` as a fullscreen app, and well, just the prompt.

I'm trying to create a split environment, running my `prompt_toolkit.prompt` command loop, and another containing a buffer that we can send things to arbitrarily for rendering. The documentation seems to indicate an upcoming refactor in terms of the API for full screen applications, but is there anything lightweight that lets me just split my window and still use the `prompt_toolkit.prompt` shortcut? I'm trying to be lazy and avoid having to implement the components of the prompt with API hooks (whether I am currently autocompleting etc.)

**Comment by jonathanslenders** [comment]
Hi @SamStudio8,

Sorry for the late reply. Unfortunately, right now, there is no obvious way to do this.
If you are ok to have a horizontal split with the prompt_toolkit UI at the bottom half of the screen, then it's possible to create a layout and use patch stdout (https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/interface.py#L982) to print all output above the prompt.
However, keep in mind that printing one line to stdout involves erasing the whole prompt_toolkit UI, printing that line, and redrawing the UI. This could be slow.

I'm indeed working on the refactoring of some parts of the UI to make full screen applications like you have in mind easier. For this particular example I'd like to have the "pymux" pane available as a kind of widget that can be embedded in any prompt_toolkit application.

All of this is not trivial and takes some time of course. So, for now, maybe you want to check out other solutions.

Jonathan

**Comment by jonathanslenders** [comment]
This is now possible with prompt_toolkit 2.0. See for instance this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/full-screen/calculator.py

There's possibly still room for improvement, but full screen applications are becoming much easier to build.

Closing this. Feel free to open again if needed.
