### ISSUE TITLE
AssertionError: Please provide a unicode string

### ISSUE THREAD

**Issue by lebe-dev** [jonathanslenders/python-prompt-toolkit#445]
**environment:** 
- CentOS 7.X x64
- Python 2.7.5

**code:** one of your examples

```python
from prompt_toolkit import prompt
from prompt_toolkit.completion import Completer, Completion


class MyCustomCompleter(Completer):
    def get_completions(self, document, complete_event):
        yield Completion('completion', start_position=0)


text = prompt('> ', completer=MyCustomCompleter())
```

**Error:**

> Traceback (most recent call last):
>   File "ptpython-demo.py", line 10, in <module>
>     text = prompt('> ', completer=MyCustomCompleter())
>   File "/usr/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 538, in prompt
>     application = create_prompt_application(message, **kwargs)
>   File "/usr/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 488, in create_prompt_application
>     wrap_lines=wrap_lines),
>   File "/usr/lib/python2.7/site-packages/prompt_toolkit/shortcuts.py", line 227, in create_prompt_layout
>     assert isinstance(message, text_type), 'Please provide a unicode string.'
> AssertionError: Please provide a unicode string.

i tried with python 3.5 and it's work fine but i need Python 2.7. Your description says "from 2.6 to 3.X"

**Comment by jonathanslenders** [comment]
Hi @lebe-dev,

Just add ``from __future__ import unicode_literals`` to the top of the file, or change the prompt-line to:
```python
text = prompt(u'> ', completer=MyCustomCompleter())
```

We expect a unicode string. Not a byte string. This is the default in Python3, which is why it did work in 3.

**Comment by lebe-dev** [comment]
thanks, code works now
