### ISSUE TITLE
Correct way to use inputhook

### ISSUE THREAD

**Issue by ivan-krukov** [jonathanslenders/python-prompt-toolkit#447]
1) What is the correct way to implement `inputhook` functionality?
2) Should there be a way to control the frequency of calling `inputhook`?

The documentation says that the `inputhook` function is [responsible for exiting](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/eventloop/inputhook.py#L9), but it is not very clear.

A working example that I have (with no `gtk`, unlike the documented example) is a thread that periodically updates a global state, which is then consumed by the `inputhook`.

The intended behaviour is printing `got stuff` periodically above the prompt with no user interaction. Upon user input `X<ret>`, I want to see `You typed X` and exit.

```python
from prompt_toolkit.shortcuts import prompt, create_eventloop

stuff = False

def wait_a_bit():
    global stuff
    while True:
        sleep(2)
        stuff = True


def print_a_bit(context):
    global stuff
    while not context.input_is_ready():
        if stuff:
            print('got stuff')
            stuff = False


if __name__ == '__main__':
    t = Thread(target=wait_a_bit)
    t.daemon = True
    t.start()

    p = prompt('> ',
        eventloop=create_eventloop(inputhook=print_a_bit),
        patch_stdout=True)
    print('You typed %s' % p)

```
So the first issue is that I do not know if this is the _intended_ way to implement this.

The second issue is that s that `while not context.input_is_ready()` is eating up 100% CPU. If I put a `time.sleep` in that section, it interferes with typing at the prompt. Should there be an extra option to adjust the frequency of calling `inputhook`?

Thanks.

**Comment by jonathanslenders** [comment]
Hi @ivan-krukov,

There are plenty of examples in the IPython source code. See: https://github.com/ipython/ipython/tree/master/IPython/terminal/pt_inputhooks
However, I'm not sure that inputhooks are what you're looking for. The function print_a_bit doesn't really implement an event loop.

If you simply want to print something from another thread while reading input from a user, check this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/patch-stdout.py

Jonathan

**Comment by ivan-krukov** [comment]
I see. The second example is the behaviour I was expecting.

In fact I was looking for a resolution of [this issue](https://github.com/jupyter/jupyter_console/issues/105) in jupyter_console. I suppose I have to poke around a little more to see what can be done.

Thank you for the pointers!
