### ISSUE TITLE
replace last printed line with patch_stdout=True

### ISSUE THREAD

**Issue by magne4000** [jonathanslenders/python-prompt-toolkit#448]
```python
print('0%', end='')
sys.stdout.flush()
time.sleep(1)
print('\r1%', end='')
sys.stdout.flush()
```
With this snippet, with native python 3, `1%` would replace `0%`.

Is this possible to mimic the same behavior with a prompt which have `patch_stdout=True` ?

**Comment by LoganDark** [comment]
No. Carriage return only works on the current line.

**Comment by magne4000** [comment]
Ok, thanks
