### ISSUE TITLE
Cannot use ansi escape codes in prompt

### ISSUE THREAD

**Issue by LoganDark** [jonathanslenders/python-prompt-toolkit#450]
![](https://puu.sh/trxzb/ada46ebfaa.png)

This looks very ugly and is not what I intended at all.

**Comment by markfink** [comment]
a little hard to tell what you are trying to do. I guess you need to use Tokens instead of inserting ansi escapes directly like so:

```python
from prompt_toolkit.shortcuts import print_tokens, style_from_dict, Token
...
style = style_from_dict({
    Token.Color: '#dfaf00',
})
tokens = [
     (Token.Color, 'hello hello')
]
print_tokens(tokens, style=style)
```

**Comment by LoganDark** [comment]
The issue is I am using ANSI escape codes, like `'\x1b[36m'` and they are not working. I refuse to use tokens because ANSI escape codes are better. *pouts*

**Comment by jonathanslenders** [comment]
This was a design decision. Probably at some point, we'll have a parser that parses those escape sequences and turns it into a token list like prompt_toolkit expects. (Along with a style sheet.)
We're not there yet. The main argument is that ANSI escape codes are not platform independent

**Comment by LoganDark** [comment]
or you could allow us to disable tokens and use ANSI codes instead. I'm not remotely comfortable with the concept of tokens and I never will be.

**Comment by mikeerickson** [comment]
@lhw Hey Logan, have you put any more thought into support ANSI color prompts?

**Comment by LoganDark** [comment]
@mikeerickson yes. I think they should be supported. Just don't strip them on purpose. If using them triggers the system extremely I won't care tbh

**Comment by mikeerickson** [comment]
@logandark I sure can't imagine how it would tax the system too much eh.  Thx for response, appreciated

**Comment by asmeurer** [comment]
I believe prompt-toolkit needs to know about them so it can count the number of visible characters correctly.

**Comment by mikeerickson** [comment]
@asmeurer Would that be taxing to calculate it?

**Comment by asmeurer** [comment]
I'm not sure what you mean by taxing, but I don't think it's an issue of performance, but platform independence. I also don't know if it can safely assume that any ANSI sequence is invisible without knowing about it a priori (although it could be enough to just recognize \1 and \2 as invisible delimiters like readline does).

**Comment by jonathanslenders** [comment]
Right now, there is also ``Token.ZeroWidthEscape``. See this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/finalterm-shell-integration.py Maybe that helps.

**Comment by LoganDark** [comment]
@asmeurer Here's a regex expression that can match ANSI escapes:

`(\x9B|\x1B\[)[0-?]*[ -\/]*[@-~]`

I used it in an old project to strip escape codes from logging output.

**Comment by asmeurer** [comment]
This is one that I've been using to catch sequences that I care about (it's in no way complete):
 `(\x1b.*?\x07)|(\x1b\[.*?m)`.

**Comment by LoganDark** [comment]
The one I used above is official, it catches all actual escape codes.

**Comment by asmeurer** [comment]
It doesn't seem to catch some proprietary escape sequences like the ones [iTerm2 uses](https://www.iterm2.com/documentation-escape-codes.html) (the shell integration ones in particular).

**Comment by LoganDark** [comment]
We shouldn't care about proprietary escape sequences. We should only care about official ones.

**Comment by asmeurer** [comment]
I don't know who "we" is, but I care about them, and I know others do too.

**Comment by LoganDark** [comment]
Whatever.

**Comment by jonathanslenders** [comment]
Hi all,
For prompt_toolkit 2.0, I did implement support for ANSI strings. Basically, many parameters can be either plain text, HTML, or ANSI. See here for an example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/examples/prompts/colored-prompt.py

By using the ``\001`` and ``\002`` separators, it's also possible to embed the finalterm shell integration sequences: https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/examples/prompts/finalterm-shell-integration.py#L35

As it works right now, not all escape sequences are supported. Only those for colors, bold, underline and italic. Further, everything between  ``\001`` and ``\002``  is supposed to not move the cursor in any way. The ANSI string is parsed, turned into a prompt_toolkit data structure, but then rendered again to the output. This means that it also works on Windows (even before Windows 10).

Keep in mind that 2.0 is still unstable. I need to test it much more, and things can still change.

Jonathan

**Comment by jonathanslenders** [comment]
Closing this one as prompt_toolkit 2.0 does support ansi in the prompt by using the ANSI wrapper in the formatted_text module. Feel free to open again if needed.

**Comment by JHubi1** [comment]
Hi there, I know this issue is a bit old, but seemingly escape codes are still not working.

When I try to print this with the prompt function `\x1b[31mName: \x1b[0m`, it spits out `^[[31mName: ^[[0m` without any proper coloring. I don't want to use the style attribute, because I'm not able to hit the colors correctly by my own. Additionally, the colors should always be chosen by the terminal, not by the program.

@jonathanslenders , you said that they should be supported in 2.0? I'm using v3.0.43; isn't it available anymore?

**Comment by HyperionCoding** [comment]
> Hi there, I know this issue is a bit old, but seemingly escape codes are still not working.
> 
> When I try to print this with the prompt function `\x1b[31mName: \x1b[0m`, it spits out `^[[31mName: ^[[0m` without any proper coloring. I don't want to use the style attribute, because I'm not able to hit the colors correctly by my own. Additionally, the colors should always be chosen by the terminal, not by the program.
> 
> [@jonathanslenders](https://github.com/jonathanslenders) , you said that they should be supported in 2.0? I'm using v3.0.43; isn't it available anymore?

Wrap the string in ANSI("...")

```
from prompt_toolkit.formatted_text import ANSI
# Print green "CMD> " and reset formatting
user_input = self.cmd_session.prompt(ANSI("\033[1;32mCMD> \033[0m"))
```
