### ISSUE TITLE
Allow Shift+Enter/Return-only for multiline mode

### ISSUE THREAD

**Issue by LoganDark** [jonathanslenders/python-prompt-toolkit#451]
Where hitting Enter/Return without holding down Shift+Enter would submit instead of making a new line.

**Comment by altaurog** [comment]
Yeah, the current multi-line behavior

> A side effect of this is that the enter key will now insert a newline instead of accepting and returning the input. The user will now have to press Meta+Enter in order to accept the input. (Or Escape followed by Enter.)

is radically different from readline's behavior (and IPython <= 3).  It is causing me and my muscle memory a lot of pain.  Switching these would be nice.

Even nicer would be something closer to the original behavior: enter submits *unless* the cursor is at the end of the line *and* it is inside a block, i.e. line is indented or ends with `:`.  I believe this is what the plain Python shell does also.  If you can give me a pointer on how to implement something like that, I'd be happy to give it a shot.

**Comment by LoganDark** [comment]
I mean a multiline mode where it is single-line except *shift*+enter inserts a new line. Sorry that I didn't explain it better.

**Comment by altaurog** [comment]
Now I'm not sure I understand.  Are you not suggesting a setting whereby "Enter" and "Shift-Enter" in multi-line mode would be switched?

**Comment by asmeurer** [comment]
I don't know if there are terminals that support Shift-Enter, but if there are, it's not universal. I had to create a custom sequence in iTerm2 to make it work.

**Comment by altaurog** [comment]
[The jessies.org Terminator](https://github.com/software-jessies-org/jessies/wiki/Terminator) does, but my pinky doesn't.

**Comment by LoganDark** [comment]
Hmm, well then Shift+Enter isn't possible (without extra effort on the most-likely-clueless user's end).

**Comment by asmeurer** [comment]
FWIW, when Shift-Enter is supported, it's a really great way to do it. So it would be nice to have support for it, if not enabled by default. I use the following setup for my Python shell:

- Enter always executes single line prompts
- In the middle of a multiline prompt (determined syntactically), Enter enters a newline
- At the end of a multiline prompt, Enter executes if there is a blank line (i.e, Enter twice to execute)
- Meta-Enter always enters a newline
- Shift-Enter always executes

Shift-Enter to always execute also matches the keybindings from the Jupyter notebook. 

I think there are clearly different preferences here, but it would be nice if prompt-toolkit made it easy  (or at least easier) to convert between them, like say, a single flag to the `shortcuts` functions (obviously Python syntax specific stuff wouldn't go in prompt-toolkit, but I mean different configs for Enter/M-Enter/S-Enter for entering newlines or accepting).
