### ISSUE TITLE
prompt_toolkit.key_binding.manager in the docs

### ISSUE THREAD

**Issue by asmeurer** [jonathanslenders/python-prompt-toolkit#455]
The [release notes](https://github.com/jonathanslenders/python-prompt-toolkit/blob/114b0f284c62c97a89cddaf5b2f977124df39a3f/CHANGELOG#L42) say that `prompt_toolkit.key_binding.manager` has been deprecated, but [the docs](https://github.com/jonathanslenders/python-prompt-toolkit/blob/114b0f284c62c97a89cddaf5b2f977124df39a3f/docs/pages/building_prompts.rst#adding-custom-key-bindings) still reference it. What should it be replaced with? Might also be worth answering this in the CHANGELOG as well.

**Comment by jonathanslenders** [comment]
Hi Aaron. Good remark! I didn't update this part in the docs.

``KeyBindingManager`` can be replaced by calling ``load_key_bindings`` from this file.
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/defaults.py#L20  Adding multiple sets of key bindings together can then be done using ``MergedRegistry``.

However, this made me realise that deprecating this should have been left for the 2.0 series of ``prompt_toolkit`` I'm working on. So, I removed that line from the CHANGELOG.

This is nothing to worry about for now. Using ``KeyBindingsManager`` is fine for now. When 2.0 is out (hopefully in a few months), then I hope to have extensive documentation about the changes and the transition.
