### ISSUE TITLE
Pressing 'v' drops you into the editor mode

### ISSUE THREAD

**Issue by amjith** [jonathanslenders/python-prompt-toolkit#460]
Pressing 'v' drops you into the editor mode.

Steps to reproduce:

Install `ptpython` and latest `prompt_toolkit` (1.0.10). 
Launch `ptpython` and type the letter 'v'.
It drops you into the `nano` editor instead of inserting the letter `v`.

Platform:

OS X, iTerm2

**Comment by jonathanslenders** [comment]
Hi @amjith,

Thank you for pointing out this issue! See also https://github.com/jonathanslenders/ptpython/issues/170
I fixed it and pushed a new ``prompt_toolkit`` release.

Can you try to upgrade ``prompt_toolkit`` to the latest version, and see whether it works again?
Thank you,
Jonathan

**Comment by amjith** [comment]
Thanks! Fixed in 1.0.11.
