### ISSUE TITLE
complete_while_typing seems ineffective

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#463]
While trying to implement xonsh/xonsh#2089 on v1.010, I cannot seem to figure out how to make the `complete_while_typing` kwarg to `shortcuts.create_prompt_application()` work.  

Digging through the source code, I found that I have to set `enable_history_search=False` in addition to `complete_while_typing=True` (which seems undocumented). Even after these arguments are set properly, completion doesn't seem to happen on each key press, as I would expect. I still have to hit tab and then the completions menu disappears once I type more.

I looked around in Buffer, too, and I didn't see anything obvious.  Are there more hidden restrictions? What I am missing?  FWIW mainline xonsh has a topical branch `compup` for this feature.

**Comment by jonathanslenders** [comment]
Hi @scopatz,
I notice that in the completion code ``xonsh/ptk/completer.py``, there is a check for ``complete_event.completion_requested``. This will be False during an automatic autocompletion. Further, as you discovered, make sure that ``enable_history_search=False``.

**Comment by scopatz** [comment]
Thanks @jonathanslenders! That seemed to be the missing piece!
