### ISSUE TITLE
ctrl-z doesn't suspend to background on linux

### ISSUE THREAD

**Issue by nonagonal** [jonathanslenders/python-prompt-toolkit#464]
I'm using prompt_toolkit v1.0.13 (via IPython 5.2.2) on Ubuntu, and ctrl-z is inserting '^Z' instead of suspending the active process.

I experimented with the prompt_toolkit code a bit, and it seems that in key_binding/bindings/basic.py:
1) load_basic_system_bindings() is called
2) suspend_to_background_supported() does return True
but
3) for some reason the Control-Z event handler registered in load_basic_system_bindings() is never called (instead the one in registered in load_basic_bindings() is always called).

**Comment by jonathanslenders** [comment]
Hi @nonagonal,

Can you try to run this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/system-prompt.py ?
I think this shortcut is disabled by default, and passing ``enable_system_bindings=True`` helps.

It's also always possible to add a new key binding that handles ``Control-Z``.

Maybe it could be enabled by default in a future version if the UI is attached to stdin/stdout. Would that make sense?

**Comment by nonagonal** [comment]
Thanks for the quick response. I tried your example and ctrl-z successfully suspends the process. I also tried with enable_system_bindings and it still suspends the process.

The problem I'm having is in the context of IPython. I've been using IPython for a long time but only looked at the source for the first time today. So I'm not sure what else about IPython is different (compared to your example program).

I can reproduce this easily in IPython, so is there any additional info I can get using something like print() statements from IPython that would be helpful?

It was confusing because the code to register the handler in load_basic_system_bindings() was definitely executing, but the event handler didn't end up getting called (maybe it was filtered or replaced somehow at a later point in time?).

**Comment by takluyver** [comment]
For reference, IPython does not pass `enable_system_bindings`, but does set a specific handler for Ctrl-Z:

```python
    supports_suspend = Condition(lambda cli: hasattr(signal, 'SIGTSTP'))
    registry.add_binding(Keys.ControlZ, filter=supports_suspend
                        )(suspend_to_bg)
```

**Comment by nonagonal** [comment]
Aha that's helpful. So all of the key bindings look like they're set up correctly (i.e. the filter condition returns True and the code is executed). Is it possible that different registries are being used?

When I actually press ctrl-z from within ipdb, only the basic handler which echoes ^Z is called. I'd be happy to look at the internal state of prompt_toolkit when this happens, I'm just not sure where to look.

**Comment by takluyver** [comment]
Ah, right, I forgot this was in the debugger. We do that for the main shell interface in IPython, but we don't currently configure any custom shortcuts in the debugger, so that's probably why.

**Comment by nonagonal** [comment]
It seems to me that load_basic_system_bindings should be handling it (i.e. prompt_toolkit has ctrl-z suspend to background by default on systems that support it), but I wasn't sure where to look to determine why the event handler it registers is not called.

**Comment by takluyver** [comment]
It sounds like that's only used if you pass `enable_system_bindings`, though, which currently we don't. Maybe we should - I haven't looked at all the implications of what that does.

**Comment by nonagonal** [comment]
Aha I was confused because the bindings are filtered after being added, so indeed prompt_toolkit is working fine. I'll close this bug and sorry for the confusion on my part.

I'll open a separate request on IPython to enable system bindings in the debugger.
