### ISSUE TITLE
alt-d alt-d then ctrl-y

### ISSUE THREAD

**Issue by dbolser-ebi** [jonathanslenders/python-prompt-toolkit#479]
In emacs this will eat the next two words then paste them both. In [mycli](https://github.com/dbcli/mycli) (which uses python-prompt-toolkit) it eats two words then pasts only the last one eaten.

**Comment by amjith** [comment]
I think @dbolser-ebi means `alt-d, alt-d, ctrl-y`. Because `alt-d` is the delete word shortcut.

**Comment by dbolser-ebi** [comment]
Ah, sorry! I'll edit the topic.

**Comment by jonathanslenders** [comment]
Implemented in https://github.com/jonathanslenders/python-prompt-toolkit/commit/70dc3769e2da8daa54cebd2db24307527962700e
