### ISSUE TITLE
alt-b and alt-f differ from readline when_moving_over_underscores

### ISSUE THREAD

**Issue by dbolser-ebi** [jonathanslenders/python-prompt-toolkit#480]
Is there a configurable list of characters where alt-f and alt-b will stop? On GNU readline I need to press alt-f 3 times to_get_over that, but in ppt, it seems to jump the whole lot, only stopping on spaces.

Sorry if this is documented somewhere, I couldn't find it.

**Comment by asmeurer** [comment]
Same as https://github.com/jonathanslenders/python-prompt-toolkit/issues/458

**Comment by dbolser-ebi** [comment]
Thanks.
