### ISSUE TITLE
iterm option+left/right not handled

### ISSUE THREAD

**Issue by craigds** [jonathanslenders/python-prompt-toolkit#483]
In iTerm2 (3.0.14) I run ipython (5.2.0, using PT) and get this when I option+left/right:

```
In [1]: awoifej woeifj wefoiwj ef[1;9D[1;9D[1;9C[1;9C
```

As you can see, option+left sends `[1;9D` and option+right sends `[1;9C`.

In the same ipython in OSX Terminal, these work correctly and map to word-left and word-right. Possibly OSX Terminal sends different escape codes. 

I found this comment in the source code: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/vt100_input.py#L178-L190

which says those keys are handled in the input processor, but I was unable to find any such handling.

I don't believe I have any overrides for those keys in my iterm2 profile (I've reset to 'xterm defaults'). In Profiles -> Keys I have both Option keys set to 'Normal': 
<img width="413" alt="screen shot 2017-03-07 at 10 41 15 am" src="https://cloud.githubusercontent.com/assets/32112/23631261/c0665020-0322-11e7-9bfc-aaa284580dd6.png">

If I instead load the preset 'Terminal.app Compatability' it works around the issue. I note that this adds these two hex code overrides for the keys:
<img width="455" alt="screen shot 2017-03-07 at 10 44 47 am" src="https://cloud.githubusercontent.com/assets/32112/23631377/2112ff22-0323-11e7-8b36-86c659787d78.png">

**Comment by jonathanslenders** [comment]
Thans for pointing out! This is a bug, and can be fixed. I'll take this as a feature request and add support as soon as I find time.

**Comment by jonathanslenders** [comment]
Hi @craigds,
Can you check whether this is still the case with the latest iTerm2? I can't reproduce it here.
Maybe also test with prompt_toolkit 2.0, if possible (current master branch).

**Comment by craigds** [comment]
Unfortunately not solved. I tried deleting my iterm profile to see if that changes things, but no dice.

With iTerm2 3.1.6 and a blank/default profile, and a fresh install of:
- ipython 6.4.0 (also tried 6.2.1)
- prompt_toolkit 1.0.15

<img width="558" alt="screen shot 2018-06-06 at 8 55 15 am" src="https://user-images.githubusercontent.com/32112/41002439-e46aa7a8-6967-11e8-8b5c-6d5a605a6b8c.png">

Anything else I could supply that would help with diagnosing the issue?

**Comment by jonathanslenders** [comment]
Hi @craigds,

Can you try adding the appropriate escape sequences to this file: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/input/vt100_parser.py#L42
And if that works, maybe create a pull request?

**Comment by craigds** [comment]
I also tried installing prompt_toolkit 2.0.2 but I wasn't able to get it working with ipython 6.4.0

**Comment by craigds** [comment]
thanks for the suggestion; ^ that fixes it :)
