### ISSUE TITLE
about timer

### ISSUE THREAD

**Issue by gushenghua** [jonathanslenders/python-prompt-toolkit#486]
How call a function periodical or implement a timer? I want to update the text of a child window in the timer， how can that be done？

**Comment by jonathanslenders** [comment]
Hi @gushenghua,
There is no built-in timer functionality, but you can probably run a while-true loop in a background-thread with a sleep.

For simple prompts, check the ``refresh_interval`` option, like in this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/clock-input.py

Another option is to use the asyncio event loop.

Jonathan

**Comment by gushenghua** [comment]
thank you!
