### ISSUE TITLE
Possible to disable status bar?

### ISSUE THREAD

**Issue by robert-dodier** [jonathanslenders/python-prompt-toolkit#498]
Hi, 

I'm using pgcli which uses prompt-toolkit to display stuff. I'd like to disable the status bar at the bottom of the screen. (Just to be clear, I mean the line in reverse video at the bottom of the console which reads "[F2] Smart Completion: ...".) A web search doesn't seem to turn up anything for this topic (neither for prompt-toolkit nor for pgcli). Does anyone know how to do that?

best,

Robert Dodier

**Comment by jonathanslenders** [comment]
Hi Robert,

It's best to open an issue on the pgcli GitHub page for this.
Prompt_toolkit allows this to be disabled/enabled, but it's up to the individual applications on how to do the actual configuration.
