### ISSUE TITLE
Fuzzy search completion list

### ISSUE THREAD

**Issue by sassanh** [jonathanslenders/python-prompt-toolkit#504]
It's a feature request. In readline completion suggestions I can use my terminal's search functionality to search a word in the list of suggestions. In column and multicolumn mode of prompt toolkit I can't search suggestions (when there's lots of suggestions) unless it's the first word of the suggestion. It'd be great if auto completion by prompt toolkit offers an option to enable fuzzy search among suggestions.

**Comment by jonathanslenders** [comment]
Hi @sassanh,

Thanks for the suggestion! However, this is not prompt_toolkit's responsibility, but rather the one of the autocompletion algorithm. Prompt_toolkit offers a universal autocompletion API that any application can implement. Mysql and pgcli for instance have some kind of fuzzy searching. For ptpython, the searching is done entirely by the library called Jedi. Let me know if you think prompt_toolkit is missing something, that would prevent you from implementing fuzzy searching outside of prompt_toolkit.

**Comment by sassanh** [comment]
Thanks for quick response. Can you kindly let me know in which repository it should be done (fuzzy search for ipython I mean) so that I can create an issue/PR there?

**Comment by jonathanslenders** [comment]
There is this library: https://github.com/amjith/fuzzyfinder
It's something you could plug into the auto completion code. Amjith is going to give a talk about this, next week at PyCon. However, I'm not sure how easy this is to integrate with Jedi, if even possible. You want Jedi to return all the completions that match the fuzzy string. See Jedi: https://github.com/davidhalter/jedi

**Comment by sassanh** [comment]
I were able to wrap jedi's results with a fuzzy completion algorithm I like for vim without touching jedi. It'd be great if I could do the same here.

**Comment by sassanh** [comment]
I don't know who's communication with jedi, ipython? or prompt-toolkit?

**Comment by sassanh** [comment]
btw, this is the algorithm I love: https://github.com/sergei-dyshel/vim-abbrev-matcher/blob/master/python2/abbrev_matcher.py It only matches with beginning of words (not every random place in the string)
For example suppose you wanna find `comment_form` in a list, it's unlikely that you try to find it by cmntfm, it's much easier to recall it by comfo (at least that's the case for me.)

**Comment by jonathanslenders** [comment]
Closing this as it's not a prompt_toolkit issue.
It is something that has to be implemented in the completer of the specific applications, like IPython, ptpython, etc...
