### ISSUE TITLE
Hitting Ctrl+R multiple times should cycle through matches

### ISSUE THREAD

**Issue by orlp** [jonathanslenders/python-prompt-toolkit#512]
If you press Ctrl+R to search history, enter something to search on, e.g. `abs`, then you see the most recent match that contains `abs`, as it should.

However, it would be really nice if just like in bash, you could then press Ctrl+R again to find the second most recent match, then third, etc... Note that if you start editing the search buffer again it resets to the most recent match.

**Comment by imomaliev** [comment]
@orlp What version you are using? Because it is working for me in my project https://github.com/imomaliev/ptrepl based on `1.0.14` version

**Comment by orlp** [comment]
It does appear that after upgrading `ptpython` it works.
