### ISSUE TITLE
Different display styling for Completion items 

### ISSUE THREAD

**Issue by vdaskalov** [jonathanslenders/python-prompt-toolkit#514]
Hi is there any way to set different styles for different rows in the completions list?

For example currently i have set the Token.Menu.Completions.Completion dict item to some green style. However I want based on some flag or string item to have different styling for different Completion items returned by the get_completions() function. So instead of having all items in green. I want one of the items to be red or blue or whatever color.

**Comment by jonathanslenders** [comment]
Hi @vdaskalov,

Thanks a lot for this suggestion. I just implemented this on the 2.0 branch (the next version of prompt_toolkit). Hopefully that's ok for you. I hope to release the 2.0 version in a couple of months.

**Comment by jonathanslenders** [comment]
See: https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/examples/prompts/colorful-prompts.py

**Comment by vdaskalov** [comment]
Hi @jonathanslenders ,

Thanks for the update. I'm looking forward to the official release of 2.0 version then. Meanwhile I'm using the display property to add additional '>' character which would server my needs as well.

**Comment by jonathanslenders** [comment]
Hi @vdaskalov, 2.0 has been released now, so closing this issue.
