### ISSUE TITLE
Please add more doc: asynchronous completion

### ISSUE THREAD

**Issue by gpotter2** [jonathanslenders/python-prompt-toolkit#518]
Hello,
I'm currently replacing our pyreadline auto completion by the one of prompt-toolkit.
(https://github.com/secdev/scapy/pull/703)

In our implementation, we encapsulate the `code.interact` function, which acts like a python shell, in which we use the `prompt` function.

Auto completion is working great, but is slow. There's some obscure functions in the doc: http://python-prompt-toolkit.readthedocs.io/en/stable/pages/reference.html#prompt_toolkit.buffer.Buffer.start_completion, which made me feel that this could be speed-up... am I right ?

If so i got several questions:
- What is the `Future` class that all doc talks about ?!
- It's written [here](http://python-prompt-toolkit.readthedocs.io/en/stable/pages/reference.html#prompt_toolkit.eventloop.posix.PosixEventLoop.run_until_complete) that it's located in `prompt_toolkit.eventloop.future.Future`, which does not seem to exist...
- How do we implement asynchronous completion ? There are no examples for that :/

The project's great ! Great work

Thanks !

**Comment by jonathanslenders** [comment]
This is weird. It looks like readthedocs took the documentation of the ``2.0`` branch.
2.0 got both asynchronous+synchronous autocompletion, auto suggestion and input validation.

For the 1.0 version (master branch), autocompletion is always asynchronous (running in a background thread), unless readline-style completions are used (press Tab to trigger completion). 

Currently, there is nothing special you have to do to get asynchronous autocompletion. Just pass the ``Completer`` instance. Know that ``Completer.get_completions`` is called in a background thread, and the completions are displayed when that function call finishes.

**Comment by jonathanslenders** [comment]
By the way, thanks for pointing this out!
Check the documentation here: http://python-prompt-toolkit.readthedocs.io/en/master/
Let me know if you have some questions. When 2.0 is ready, it will have much more documentation (give it maybe half a year).

**Comment by gpotter2** [comment]
Ok thanks for the info ! My only next question is about https://github.com/jonathanslenders/python-prompt-toolkit/issues/519.
I'm looking for a way to implement python-prompt-toolkit in [scapy](https://github.com/secdev/scapy).
