### ISSUE TITLE
Is Input.read actually used? 

### ISSUE THREAD

**Issue by asmeurer** [jonathanslenders/python-prompt-toolkit#524]
I noticed that `PipeInput.read` is [wrong](https://github.com/jonathanslenders/python-prompt-toolkit/blob/36af6561be13530e631e0959fa6c78ccfc37bbba/prompt_toolkit/input.py#L115) (it calls `os.read(self._r)`, but `os.read` takes [two arguments](https://docs.python.org/2/library/os.html#os.read)).

I've used PipeInput and never seen an issue with it, so I'm assuming that no code actually uses `read`, instead directly manipulating the `fileno`. Does this mean that `Input` subclasses have to have a real file number associated with them?

**Comment by jonathanslenders** [comment]
I think you're correct that the ``read`` function is never used, so this looks like a bug indeed.
In any case, this has been changed on the 2.0 branch, the read function has been removed.
I don't recall the details at the moment, I'd need to look into it when I have a little more time.

**Comment by jonathanslenders** [comment]
Closing, because it's fixed in 2.0.
