### ISSUE TITLE
Not an issue .. WordCompleter question.

### ISSUE THREAD

**Issue by securisec** [jonathanslenders/python-prompt-toolkit#525]
Hey, is it possible to add a decorator or a mark that indicates so in the auto completer? for example, lets assume i have following options

a = WordCompleter(['option a', 'option b', 'option c'])

once the user selects an option, say option c, i want the next round of autocompletions to show something like option a, option b, DONE option c. 

Thanks!

**Comment by jonathanslenders** [comment]
Hi @securisec,

``WordCompleter`` can't do this. What you want is to create a custom completer class.
You need to inherit from the ``Completer`` class (https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/completion.py#L118), and implement the ``get_completions`` method. It should return a list of ``Completion`` instances.

In this function, you have access to the current document, (see https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/document.py#L68). You can use the ``get_word_before_cursor`` function (https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/document.py#L402) or ``text_before_cursor`` property to know what's before the cursor: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/document.py#L147.

**Comment by securisec** [comment]
Awesome answer! Thanks!
