### ISSUE TITLE
wait_for_cpr_responses is blocking for too long

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#535]
At 2.0, [`wait_for_cpr_responses`](https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/prompt_toolkit/application/application.py#L547) is blocking the UI for 0.5 second to wait for CPR response. However, if a terminal emulator doesn't support CPR, it can be very annoying.

**Comment by randy3k** [comment]
My current solution is to construct a custom input.

```python
if not is_windows():
    from prompt_toolkit.input.vt100 import Vt100Input

    class CustomVt100Input(Vt100Input):
        @property
        def responds_to_cpr(self):
            return False
```

**Comment by jonathanslenders** [comment]
Good point. Handling this remains a pain. As far as I know there is no way to detect whether the current terminal responds to CPR. Just trying it is also not clean, because probably the CPR request will be displayed.

I guess, I could make this a parameter of Vt100Input, or maybe check an environment variable.

**Comment by randy3k** [comment]
I guess the best solution is still trying. If a terminal enumerator doesn't reply the request then the terminal is marked as not support CPR and we don't send CPR request any more. 

We don't have to worry about printing the CPR request at all. Though some terminals may not respond to CPR, they usually capture those CSI sequences and do not print those sequence.

**Comment by jonathanslenders** [comment]
Hi @randy3k,

I pushed a new commit on the 2.0 branch that should solve this. If it detects that CPR is not supported, it won't send CPR outputs anymore. It also fixes some bugs that could happen in certain edge cases.

**Comment by randy3k** [comment]
It works, except that there should be an option to turn off the warning message.

Thank you anyway.

**Comment by randy3k** [comment]
Also, the warning should not be shown if `input.responds_to_cpr()` is `False`
