### ISSUE TITLE
system toolbar not working at 2.0

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#536]
I just do
```python
p = Prompt()
p.prompt("> ")
```

I first hit `esc + !` but nothing is shown.  I then type `ls` and press `enter.
The following is shown
<img width="493" alt="screen shot 2017-08-13 at 9 29 39 pm" src="https://user-images.githubusercontent.com/1690993/29255426-4147f6c0-806f-11e7-8637-d7f7fc6de79f.png">
and the program is  frozen.

**Comment by randy3k** [comment]
1. I just note that `enable_system_prompt` was `False` in the above example, but the keybind was not disabled.

2. even with `enable_system_prompt=True`, the program freezes after the "Please Enter to continue".

**Comment by jonathanslenders** [comment]
Hi @randy3k, normally the freeze should be solved now. I still have to check the other issue.

**Comment by jonathanslenders** [comment]
The first issue should should now be fixed too.

**Comment by randy3k** [comment]
confirmed.
