### ISSUE TITLE
HighlightMatchingBracketProcessor does not unhighlight after enter key

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#538]
At 2.0

```python
        p = Prompt(extra_input_processor=HighlightMatchingBracketProcessor())
        p.prompt("> ")
```

<img width="187" alt="screen shot 2017-08-15 at 1 48 20 am" src="https://user-images.githubusercontent.com/1690993/29303582-d648fc5a-815b-11e7-9d51-50b55635c7dc.png">

**Comment by jonathanslenders** [comment]
Should be fixed: https://github.com/jonathanslenders/python-prompt-toolkit/commit/428f1a08aa53bb9830c7c64984785026b2914459

Thanks for reporting!

**Comment by randy3k** [comment]
confirm fixed.
