### ISSUE TITLE
Programmatically modifying read-only buffer

### ISSUE THREAD

**Issue by fake-name** [jonathanslenders/python-prompt-toolkit#540]
Is there a way to programmatically append or modify a read-only buffer?

Basically, I want to display log output, so I specifically want a buffer the end-user cannot modify, but apparently setting a buffer to read-only prevents programmatic changes as well?

Is that expected? When I've used Qt or other GUI toolkits in the past, setting a widget read-only prevents just user modifications, rather then any changes. 

What's the proper way to accomplish a display-only buffer that is updated by another thread?

**Comment by jonathanslenders** [comment]
Hi @fake-name,

You can call ``Buffer.set_document``, and set ``bypass_readonly=True``.
The reason it works this way is that it was too cumbersome to check in every key binding that did a modification, to test whether the buffer was read only or not.

**Comment by fake-name** [comment]
Ah, that makes sense. Cool, thanks!
