### ISSUE TITLE
Question about Completer

### ISSUE THREAD

**Issue by abhinavdas** [jonathanslenders/python-prompt-toolkit#541]
(This is not an issue. If there is a better place to post this question please let me know.)

I have an autocompletion list that takes a while to be retrieved (network IO). During this time I want the prompt to be displayed and it the user presses tab, it should show something like `...loading`. As soon as the list is retrieved, the autocompletion list should be populated without the user having to press tab again. Is this possible?

Thank you.

**Comment by jonathanslenders** [comment]
Hi @abhinavdas,

If you don't mind showing this message in a bottom toolbar or rprompt, then this is possible. Check the bottom toolbar and rprompt examples on how to display text over there. Make sure that somewhere before and after the loading the completions, you set a boolean variable somewhere.

If you wish to display this somewhere else, like in a drop down menu, then that's going to be much more complex, because you'll have to design a new layout.

**Comment by asmeurer** [comment]
I've also wanted some way to indicate that the completions are loading, particularly so I can see when they are done loading and I can know that there are no completions and it isn't just still trying to compute them (Jedi can be slow sometimes).

**Comment by abhinavdas** [comment]
Thanks @jonathanslenders. How do I ensure that toolbar or rprompt is redrawn when list is downloaed? I guess the situation would be the following: the prompt is displayed and a new thread is downloading the list of completers. The user sees a `loading possible values...` in toolbar. Once, the values are loaded, I need to inform the user that the values are loaded and that they need to press `tab`. How, do I change the toolbar associated with the prompt that is already displayed?

**Comment by jonathanslenders** [comment]
Have a look at this example: https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/examples/prompts/slow-completions.py
(Also make sure to use the latest 2.0 commit.)

Invalidation should not be necessary in this case, but if you need it, the following can be called in any case to trigger a redraw.
```python
from prompt_toolkit.application.current import get_app
get_app().invalidate()
```
