### ISSUE TITLE
ctrl-c on the search bar throws KeyboardInterrupt

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#543]
at 2.0 branch, ctrl-c doesn't cancel the search prompt but throws KeyboardInterrupt.

**Comment by jonathanslenders** [comment]
Thanks for reporting!

**Comment by jonathanslenders** [comment]
Should be fixed now: https://github.com/jonathanslenders/python-prompt-toolkit/commit/412f4428d27891f0ad5e56e6195fb7fed4812318

**Comment by randy3k** [comment]
confirm fixed.
