### ISSUE TITLE
Return one line at a time from prompt()

### ISSUE THREAD

**Issue by eerimoq** [jonathanslenders/python-prompt-toolkit#548]
Hi,

first of all, thanks for a great package! I've used the autocompletion and persistent history, works very well!

I have a question, is it possible to paste multiple lines into the prompt and return them one at a time from the `prompt()` function?

As an example, I have this script:

``` python
from __future__ import unicode_literals
from prompt_toolkit import prompt
import os

if __name__ == '__main__':
    while True:
        command = prompt('$ ')
        os.system(command)
```

If I paste `ls\nls\n` into the prompt and then press `<ENTER>` the output looks like this:

```
> python3 test.py 
$ ls
  ls
  <ENTER>
bar.txt  foo.txt
bar.txt  foo.txt
$ 
```

I would like the output to look like below, pasting the same string `ls\nls\n`, and without pressing `<ENTER>`:

```
> python3 test.py 
$ ls
bar.txt  foo.txt
ls
bar.txt  foo.txt
$                      
```

Thanks,
Erik

**Comment by jonathanslenders** [comment]
Hi Erik,

There is a good reason why it doesn't work this way. It has to do with how bracketed paste works.
https://cirw.in/blog/bracketed-paste

Currently, the workaround would be to do a ``.splitlines()`` on the given input and print/handle each line independently.

**Comment by eerimoq** [comment]
Ok, thanks for the quick reply. I'll use the workaround for now, crossing my fingers the requested feature will be implemented at some point. =)

**Comment by asmeurer** [comment]
@eerimoq I describe one way to do this at https://github.com/jonathanslenders/python-prompt-toolkit/issues/519#issuecomment-318978114 (in short, use a queue with PipeInput, and add a Keys.BracketedPaste handler that splits the input). 

Another, simpler way would be to re-show each command as it's executed when there are multiple commands, like

```
$ ls
  ls

> ls
bar.txt  foo.txt
> ls
bar.txt  foo.txt
```

That should work fine if your goal is just to make it clear which output comes from which command.

**Comment by jonathanslenders** [comment]
If you really want to disable bracketed paste, then you could probably also create a custom ``Output`` class, which overrides ``Vt100_Output`` and replaces ``enabled_bracketed_paste`` by a no-op.

https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/terminal/vt100_output.py#L528

**Comment by eerimoq** [comment]
Is it possible to save the remaining lines of the input in between calls to `prompt()`?

**Comment by asmeurer** [comment]
@jonathanslenders I imagine that won't work very well outside of the 2.0 branch because of https://github.com/jonathanslenders/python-prompt-toolkit/issues/515.

**Comment by eerimoq** [comment]
It works on the 2.0 branch with `enabled_bracketed_paste` as a no-op, but there is a delay of about a second in between the first and second `ls`. Seems all but the first line are executed with about a second delay in between.

**Comment by jonathanslenders** [comment]
@asmeurer: Good point. Without typeahead, this doesn't work. And only 2.0 has typeahead support.

@eerimoq: Which terminal are you using. Do you know whether it response to cursor position requests? There is a "fix" in prompt_toolkit 2.0 that waits for CPR responses. I think this causes the delay. We might need to fix this.

**Comment by eerimoq** [comment]
I'm using "xfce4-terminal 0.6.3" in XUbuntu 16.04. If I paste a few `ls` separated by line terminations and then press and hold the right arrow key I can see `^[[C>` flickering at the beginning of the line while waiting for the `ls` output. Does that answer your question? If not, please explain how I can test it =)

**Comment by Vyjill** [comment]
For those who might find this post through a search engine, and who are searching for a quick and dirty way of doing that, here is a monkeypatch :

```py
session = prompt_toolkit.PromptSession()

# Save bracketed paste for later
old_enable_bracketed_paste = session.app.renderer.output.enable_bracketed_paste 

# Ugly monkeypatching
session.app.renderer.output.enable_bracketed_paste = session.app.renderer.output.disable_bracketed_paste

# Disable bracketed paste
session.app.renderer.output.disable_bracketed_paste()

# Prompt without bracketed paste
serial_number = session.prompt("Disabled bracketed paste > ") 


# Re-enable bracketed paste
session.app.renderer.output.enable_bracketed_paste = old_enable_bracketed_paste 

```

For those who might be curious, my very specific usage was a quick console app which waited output from a barcode scanner, acting as a keyboard but sending a newline as a bracketed paste style.
