### ISSUE TITLE
Add mssql-cli to "Projects using prompt_toolkit"

### ISSUE THREAD

**Issue by mkt** [jonathanslenders/python-prompt-toolkit#566]
[mssql-cli](https://github.com/dbcli/mssql-cli) is using prompt_toolkit.
Please add mssql-cli to "Projects using prompt_toolkit".

**Comment by jonathanslenders** [comment]
Added in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/6976e0c91d3f115d16aaf4430880bf905954a0c9
Thanks for sharing. Another amazing project!
