### ISSUE TITLE
Examples seem to be out of date

### ISSUE THREAD

**Issue by RobertoPrevato** [jonathanslenders/python-prompt-toolkit#571]
Hi,
I am trying to use examples in the documentation, but many of them seem to be out of date. For example:

```python
from prompt_toolkit.shortcuts import prompt
from prompt_toolkit.styles import Style

style = Style.from_dict({
    # User input.
    '':          '#ff0066',

    # Prompt.
    'username': '#884444',
    'at':       '#00aa00',
    'colon':    '#00aa00',
    'pound':    '#00aa00',
    'host':     '#000088 bg:#aaaaff',
    'path':     '#884444 underline',
})

def get_prompt():
    return [
        ('class:username', 'john'),
        ('class:at',       '@'),
        ('class:host',     'localhost'),
        ('class:colon',    ':'),
        ('class:path',     '/user/john'),
        ('class:pound',    '# '),
    ]

text = prompt(get_prompt, style=style)
```

causes exception: "AttributeError: type object 'Style' has no attribute 'from_dict'". I had issues with most of the examples I tried so far, but had satisfaction following this article: [4 Python libraries for building great command-line user interfaces](https://opensource.com/article/17/5/4-practical-python-libraries).

Am I missing something? Is it maybe because examples are not updated to version 2?

Best Regards

**Comment by RobertoPrevato** [comment]
For people who may end up on this page, I just noticed that here there is a different example of the same feature, here: [https://python-prompt-toolkit.readthedocs.io/en/master/pages/building_prompts.html#](https://python-prompt-toolkit.readthedocs.io/en/master/pages/building_prompts.html#)

**Comment by jonathanslenders** [comment]
Hi @RobertoPrevato,

The examples that you see are coming from the 2.0 branch. This is the newest prompt_toolkit which has not yet been released. Check out the examples on the master branch for the current version.

**Comment by RobertoPrevato** [comment]
Hi @jonathanslenders,
Thanks for the quick reply, I didn't understand that the version 2.0 was not public, yet. Everything is clear now. The work you did with prompt toolkit is amazing!

Kind Regards,
Roberto

**Comment by RobertoPrevato** [comment]
Maybe it would be best to mention this in the README. For example, explaining that, to try the latest examples before the release one can use this command to install the package:

```bash
pip install https://github.com/jonathanslenders/python-prompt-toolkit/archive/2.0.zip
```

Instead of:
```bash
pip install prompt_toolkit
```
