### ISSUE TITLE
print_formatted_text example from documentation doesn’t work for html

### ISSUE THREAD

**Issue by rovitotv** [jonathanslenders/python-prompt-toolkit#572]
I am new to python-prompt-toolkit so I am carefully reading the documentation and have discovered that the example in the “stable” manual for version 1.0.15 that ships with Anaconda for both Python 3.6.4 and Python 2.7

[link to manual on read the docs](http://python-prompt-toolkit.readthedocs.io/en/stable/pages/printing_text.html)

produce this traceback when you fun them.

```
Traceback (most recent call last):
  File "print_html.py", line 2, in <module>
    from prompt_toolkit import print_formatted_text, HTML
ImportError: cannot import name 'print_formatted_text'
```

I have a suspicion that the function “print_formatted_text” was moved and the documentation was not updated but I could be wrong and this could be user error.

**Comment by jonathanslenders** [comment]
Hi @rovitotv,

Thanks for pointing out!
It looks like readthedocs uses the default branch for the documentation. This is the documentation for the 2.0 branch, which has not yet been released. (It will be released in the next couple of months).
Either you have to install the 2.0 branch manually (it's not yet on Pypi), or look for the documentation in the master branch. I'll see whether it's not too much effort to get this back on readthedocs.

See also: https://github.com/jonathanslenders/python-prompt-toolkit/issues/571

Jonathan

**Comment by jonathanslenders** [comment]
Hi @rovitotv,
2.0 has been released, so I'm closing this issue.
