### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by windelbouwman** [jonathanslenders/python-prompt-toolkit#575]
Hello Jonathan,

Thanks for creating this cool thing! I just used it to create the ppci_explorer: https://bitbucket.org/windel/ppci/src/6fca01e39219559f521bda4434e1e050ab6a53e2/tools/ppci_explorer.py?at=default&fileviewer=file-view-default

When will version 2.0 be released with improved fullscreen app support?

Regards,
Windel

**Comment by jonathanslenders** [comment]
Hi Windel,

That looks good. Version 2.0 should be released somewhere in the next couple of months, when its stable. I hope at least before PyCon US. I'm in the progress of converting a couple of tools to 2.0, like pyvim and pymux, and while doing so, I can test the stability of the 2.0 release.

Jonathan

**Comment by asmeurer** [comment]
Do you have any plans to put out an alpha release? I don't want to spend the time converting my code until it's stable, but I would also like to be able to have any potential issues in 2.0 in a released version.

**Comment by jonathanslenders** [comment]
Hi @asmeurer,
You can install it as follows:
```sh
pip install git+https://github.com/jonathanslenders/python-prompt-toolkit.git@2.0
```
I hope to push a release soon.

**Comment by xmijo** [comment]
Discovered prompt-toolkit today and I'm loving it, thanks for making this. Came here to check on progress of the new version with improved fullscreen app support and delighted to see it's in the works. Hoping the new version will also come with documentation for methods of integrating fullscreen apps with asyncio, that would be much appreciated as well. Thanks again

**Comment by jonathanslenders** [comment]
Prompt_toolkit 2.0 has been released. Please let me know if you found any issues.

Check out the changelog: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/CHANGELOG
And documentation: https://python-prompt-toolkit.readthedocs.io/en/master/index.html
