### ISSUE TITLE
multiline toolbar

### ISSUE THREAD

**Issue by sander76** [jonathanslenders/python-prompt-toolkit#587]
Not really an issue. But is there a possibility to have a bottom toolbar consisting of two lines ?
adding "\n" to the string did not work...

**Comment by jonathanslenders** [comment]
Hi @sander76, thanks for creating the issue.
I think it should have been solved in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/b9f6f0f74bc31e35004b553d39db9e275a091cb0
Could you try this?

**Comment by sander76** [comment]
Works!
