### ISSUE TITLE
Add clipwdmgr to "Projects using prompt_toolkit" 

### ISSUE THREAD

**Issue by samisalkosuo** [jonathanslenders/python-prompt-toolkit#591]
[Command Line Password Manager](https://github.com/samisalkosuo/clipasswordmgr) (clipwdmgr) is using prompt_toolkit.

Please add to "Projects using prompt_toolkit".

Thanks! :-)

**Comment by jonathanslenders** [comment]
Hi @samisalkosuo, nice project! Could you create a pull request for this?

**Comment by samisalkosuo** [comment]
Done :-)
