### ISSUE TITLE
Add "go-prompt" on README

### ISSUE THREAD

**Issue by c-bata** [jonathanslenders/python-prompt-toolkit#593]
Hi @jonathanslenders !
First of all, thanks for this awesome library.

I develop an interactive prompt library in Go which is inspired by python-prompt-tolkit.
https://github.com/c-bata/go-prompt

I know this doesn't match a project using python-prompt-toolkit, but I'd like to ask for your consideration.

Thanks.

**Comment by jonathanslenders** [comment]
Hi @c-bata, this looks really nice!

Added here: https://github.com/jonathanslenders/python-prompt-toolkit/commit/6805c0756b6285969a0dc55226025d32688e5109

**Comment by c-bata** [comment]
I'm honored that go-prompt is on python-prompt-toolkit's README.
Thanks!
