### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by hargoniX** [jonathanslenders/python-prompt-toolkit#596]
https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/examples/dialogs/input_dialog.py

This example is not working for me. Just did a fresh install, some other examples did but this one throws
```Python
>>> from prompt_toolkit.shortcuts.dialogs import input_dialog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'prompt_toolkit.shortcuts.dialogs'; 'prompt_toolkit.shortcuts' is not a package
>>> 
```

**Comment by asmeurer** [comment]
That file is from the 2.0 branch, which has several API changes, but master and the latest release are pre-2.0.

**Comment by jonathanslenders** [comment]
Closing this issue. Please feel free to open again if you have any further questions.
