### ISSUE TITLE
prompt, Prompt, Application, ... inconsistency

### ISSUE THREAD

**Issue by markfink** [jonathanslenders/python-prompt-toolkit#597]
prompt docstring states: "Display the prompt. All the arguments are the same as for the
        :class:`~.Prompt` class.".
... but what happened to **input**, and **output**? Or am I doing something wrong?

I was expecting prompt to properly **assemble** and then **run** an application.

but somehow prompt does something interesting :) but difficult to grasp:

```python
def prompt(*a, **kw):
    """ The global `prompt` function. This will create a new `Prompt` instance
    for every call.  """
    prompt = Prompt()
    return prompt.prompt(*a, **kw)
```

I liked "create_prompt_application" better in this regard.

**Comment by markfink** [comment]
thank you for the explanation. 
prompt.prompt does not have input / output. I am quite sure since I got an exception. My understanding from the docstring was that you want to have them consistent. A testcase could help to make sure of it

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/cdf6790752cb114b09b7c04adf7f6c9365b69cec
Thanks for pointing out, @markfink !

**Comment by markfink** [comment]
I think you have to use .pop instead of .get:

```python
        prompt = Prompt(input=input, output=output)
>       return prompt.prompt(*a, **kw)
E       TypeError: prompt() got an unexpected keyword argument 'input'
```

**Comment by jonathanslenders** [comment]
Fixed the pop/get issue: https://github.com/jonathanslenders/python-prompt-toolkit/commit/897b0965a261268416609ee1d71a26a8c79a88f2

**Comment by jonathanslenders** [comment]
Closing this. I think all issues have been fixed here. Let me know if not.
