### ISSUE TITLE
Some hex colors don't seem to work.

### ISSUE THREAD

**Issue by williexu** [jonathanslenders/python-prompt-toolkit#603]
```
from pygments.token import Token
from prompt_toolkit.shortcuts import prompt
from prompt_toolkit.styles import style_from_dict

example_style = style_from_dict({
    # User input.
    Token.Mytext: '#EECD86',
    Token.Othertext: '#C3C3E5',
})

def get_prompt_tokens(cli):
    return [
        (Token.Mytext, 'mary had a little lamb'),
        (Token.Othertext, 'sad, did not get colored'),
    ]

text = prompt(get_prompt_tokens=get_prompt_tokens, style=example_style)
```
![image](https://user-images.githubusercontent.com/8580552/37377276-20748526-26e6-11e8-8961-ba3b38cde8a2.png)

#EECD86, which is a yellow seems to work, while #C3C3E5, a light purple does not.

Any idea why? Tried this on both Unix and windows terminals.

I've also noticed some very different colors (such as #884444), when using in windows vs unix.

**Comment by jonathanslenders** [comment]
Hi @williexu,

These colors are mapped to 256 colors on unix terminals by default, and to the 16 available colors on a Windows terminal. The closest color is always used, which could be the reason why you're getting different colors.

Prompt_toolkit 2.0 does some refactoring regarding this. It supports any color depth on Windows consoles, and makes it easier to configure by setting the ``PROMPT_TOOLKIT_COLOR_DEPTH`` environment variable. See: https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/prompt_toolkit/output/color_depth.py#L34    2.0 will be released in the coming months.

**Comment by jonathanslenders** [comment]
Closing this issue. Please feel free to open again if you have any further questions.
