### ISSUE TITLE
search highlight is not clear after hitting enter

### ISSUE THREAD

**Issue by randy3k** [jonathanslenders/python-prompt-toolkit#613]
I am on the current `2.0` branch. When I use `ctrl+r` or `ctrl+s` to search history, the matching highlight is not clear after hitting enter. Moreover, it persists if I navigate through history.

See the following screencast.

![apr-21-2018 20-27-30](https://user-images.githubusercontent.com/1690993/39090071-7e9eb9c0-45a2-11e8-8811-992151704ce9.gif)

**Comment by randy3k** [comment]
it turns out it is caused by my own code. sorry for the noise.

**Comment by jonathanslenders** [comment]
No problem, @randy3k!
