### ISSUE TITLE
Buggy behavior with completions in 2.0 (possibly related to CPR requests)

### ISSUE THREAD

**Issue by asmeurer** [jonathanslenders/python-prompt-toolkit#617]
In the 2.0 branch I am seeing very buggy behavior with tab completion. 

If the prompt is at the bottom of the terminal, the completion columns do not appear. It acts as if they are below the visible screen.

If the prompt is above the bottom (like if I Ctrl-L), then all input is extremely laggy, taking 10-20 seconds before any input appears. It causes my terminal (iTerm2) to beachball, so it's quite possible there is a bug there.  When I eventually do get the completions, the completion columns appear as expected (unrelated question: is READLINE_LIKE supposed to be identical to COLUMNS?). I tested it in Terminal.app and the lagging is not there (although the above issue with the no columns still is). 

I'm guessing this is related to CPR codes. If I comment out the CPR request code in vt100.py, I get a message `WARNING: your terminal doesn't support cursor position requests (CPR).`, and then completions happen as in the above case, with no columns, regardless of whether the text is at the bottom of the terminal (that is, it removes the lagging, but also any columns). 

If I do the same in `master` (comment out the CPR request), the completions work just fine from anywhere. 

I wasn't able to reproduce this in the completions example script, so I'm not sure what all I am doing to cause this. If you need help reproducing, you can test [this branch](https://github.com/asmeurer/mypython/tree/2.0) against my 2.0-fixes branch (type `%` then `TAB`) (you'll have to pip install a few dependencies first, sorry, I never designed that to be usable by other people).

**Comment by jonathanslenders** [comment]
All the useless ``\x1b[0m`` escapes are now removed with this small optimization: https://github.com/jonathanslenders/python-prompt-toolkit/commit/c13572e135037da11ca2de9ea477d1cbf34777b2

When the screen is cleared, all lines are rendered again. The current in memory screen is then compared with the previous screen (for only outputting the diff). When going through the new screen, the style is compared with the style of the last drawn character. There we checked ``if the_last_style``. In this case, this was an empty string, and we always ended up in the second branch. That caused the spam of escape sequences, but it should not hurt the terminal in any case.

I can't seem to reproduce the not showing of completions column. Can you reproduce it with any of the examples, or do you have some code? Which iTerm2 version is this?

**Comment by jonathanslenders** [comment]
Apparently, after applying this patch: https://github.com/jonathanslenders/python-prompt-toolkit/commit/c13572e135037da11ca2de9ea477d1cbf34777b2 on your branch, it seems to work much better. At least here I don't get the spinning wheel anymore half of the time. It surprises me. I think it should be a bug in iTerm2, but that terminal is known for prioritizing UI fanciness above performance.

The completion menus also render fine. The bug that appears at the bottom of the screen is actually in your changes. ``_get_default_buffer_control_height`` returns the height that is used for the completion menu. If ``self.completer`` is ``None``, 0 will be returned and nothing will be shown.
Either we should assign the completer to ``self.completer`` or we have to check ``self.default_buffer.completer``.

This also makes me wonder whether I want to merge these changes to the ``Prompt`` class. There are some good ideas, and I'll probably merge some commits or changes, but the class was never intended to be inherited from. I don't want to support everyone who thinks it's a good idea to override these internals. Can you still elaborate on why the things you want to do are not possible without these modifications?

BTW: I also saw a suggestion about renaming ``Prompt`` to ``PromptSession`` (or something like that). I think this is a good idea.

FYI: 
```
  File "/Users/jonathan/git/python-prompt-toolkit/prompt_toolkit/completion.py", line 169, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/Users/jonathan/git/mypython/mypython/completion.py", line 107, in get_completions
    script = get_jedi_script_from_document(document, self.get_locals(), self.get_globals())
  File "/Users/jonathan/git/mypython/mypython/completion.py", line 41, in get_jedi_script_from_document
    full_document = '\n'.join(i for _, i in sorted(_locals['_CLI'].builtins['In'].items()))
Exception '_CLI'
```

**Comment by asmeurer** [comment]
> edit: I'm testing your code right now. It's slow indeed. Rendering here is also mixed up because wcwidth('🐍') returns 2, while my iTerm2 only uses one cell for this character.

You have to enable double width emoji in some setting (still not sure why this isn't the default). 

> It surprises me. I think it should be a bug in iTerm2, but that terminal is known for not being the fastest.

Well I did open the upstream issue. So we'll see if things improve. 

> The bug that appears at the bottom of the screen is actually in your changes. 

Ah, I should have guessed as much. I've fixed it. 

> This also makes me wonder whether I want to merge these changes to the Prompt class. There are some good ideas, and I'll probably merge some commits or changes, but the class was never intended to be inherited from. I don't want to support everyone who thinks it's a good idea to override these internals. Can you still elaborate on why the things you want to do are not possible without these modifications?

Well the main thing I need is the ability to set my own buffer. You can see that not only do I use my own [Buffer subclass](https://github.com/asmeurer/mypython/blob/2.0/mypython/mypython.py#L55) which implements my own history search logic, but I am also using a custom `accept_handler`. I've also elaborated on this [here](https://github.com/asmeurer/mypython/blob/2.0/prompt_toolkit_extensions.md). 

I added the rest of the stuff from `_create_application` for completeness, but I don't actually need them (although as I mentioned I might want to create a custom layout at some point in the future). To do this without split methods, I would have to copy the entire 240 line method _create_application and modify only the relatively small parts I want to change. I basically have to do everything from scratch. But I like *most* of the defaults from shortcuts, and I don't want to throw the baby out with the water and reinvent everything from scratch. I might get there at some point as I customize things more and more. When I started, I just used `prompt` (1.0). Then I needed to modify stuff beyond what `prompt` allowed so I copied most of the code (you can see [this function](https://github.com/asmeurer/mypython/blob/4a50ea6186f883123fe940273b5adcb146b70bd4/mypython/mypython.py#L574-L639) is more or less a copy of `prompt` with some modifications and additions. 

> FYI

Yeah I know I still have a lot of bugs. Trying to get everything working so I can find the bugs in the 2.0 branch before it gets released (though don't let me block you by any means).

**Comment by asmeurer** [comment]
This is working better now performance-wise, and the other issue I guess was in my own code. Closing this.
