### ISSUE TITLE
Strange behaviour with IPython -> Plot window hangs prompt

### ISSUE THREAD

**Issue by ThatGeoGuy** [jonathanslenders/python-prompt-toolkit#63]
This is using python3.4.1, on Windows 7 Professional 64 bit, with the latest IPython, as well as numpy / scipy / matplotlib. 

I was just playing around with the experimental windows support, just to test out the features (like autocompletion, ipython integration, etc). Anyways, the first thing I usually do is try out matplotlib, to see if it's working / loading correctly. 

    $ ptipython --vi
    In [1]: %pylab
    Using matplotlib backend: TkAgg
    Populating the interactive namespace from numpy and matplotlib
    In [2]: plot([1,2,3,4], 'r')
    Out[2]: [<matplotlib.lines.Line2D at 0x5c92ed0>]

This should, ideally, plot a single figure window with the line x = y in it. It draws the window, but the plot inside cannot be seen. What's more, if you try to interact with the window in any way, it crashes the python instance. 

So I figured I'd try the same thing by pasting the relevant matplotlib code directly from python. 

    # File: test.py
    import matplotlib.pyplot as plt
    plt.plot([1,2,3,4], 'r')
    plt.show()

This works, but there is a drawback, ptpython (and of course, ptipython) both plot the figure, but do not return the prompt until the window with the plot is closed. This is somewhat of a serious flaw, as it requires you can't use plots / data visualization interactively.

Unfortunately, I have not really narrowed down the factors as to why these bugs are apparent. I had initially thought it had something to do with ipython, but running the code listed in `test.py` in ptpython exhibits the same behaviour. However, there does appear to be some issue using `%pylab` and its associated functions (calling plot directly) in ptipython. In any case, I'll check when I get home and have access to a Linux machine to see if this behaviour is replicable there as well.

**Comment by darikg** [comment]
Hi, thanks for python-prompt-toolkit! Any luck with this issue?

**Comment by jonathanslenders** [comment]
No, not yet. I had a look at the event loops of IPython, but I remember there was no way to plug my own code in there. I guess this needs changes on both IPython and prompt-toolkit. (prompt-toolkit needs an event loop that supports run_in_executor and call_from_executor as well as monitoring for stdin.)

Currently I'm busy working on the refactoring of the layout system. But maybe I'll have a second look later on.

**Comment by darikg** [comment]
gotcha, sounds like a headache. thanks!

On Fri, Jan 9, 2015 at 11:15 AM, Jonathan Slenders <notifications@github.com

**Comment by jonathanslenders** [comment]
Hi everyone,
ptpython now integrates automatically with the tk eventloop when it detects that the ``tkinter`` package was imported. So, the ``turtle`` package and other tk stuff should work again.
This also means that ``ptipython`` will display plots correctly when the ``TkAgg`` matplotlib backend is used. (That's the default, I think.)

For a better integration with IPython, I refer to this ticket: https://github.com/ipython/ipython/issues/8489

Jonathan

**Comment by ThatGeoGuy** [comment]
Hey @jonathanslenders, thanks for looking into this. I'm impressed and amazed that my bug report has come this far. 

Thanks again for the work you've done on this until now. I've begun playing around with ptipython again, and it's much more polished. I'm excited to see future integrations with IPython, so thanks again for your work!

**Comment by jonathanslenders** [comment]
You're welcome!
