### ISSUE TITLE
prompt shortcut history option breaks in 2.0

### ISSUE THREAD

**Issue by theazureshadow** [jonathanslenders/python-prompt-toolkit#632]
In 2.0, the `prompt` shortcut doesn't accept the `history` option, even though the [documentation implies that it should](http://python-prompt-toolkit.readthedocs.io/en/stable/pages/reference.html#prompt_toolkit.shortcuts.prompt), since `history` is an option for `PromptSession`:

>`prompt_toolkit.shortcuts.prompt(*a, **kw)`
>Display the prompt. All the arguments are a subset of the `PromptSession` class itself.

Looks like the arguments are actually passed to `PromptSession.prompt` rather than `PromptSession`:

https://github.com/jonathanslenders/python-prompt-toolkit/blob/dc2282d17a9d132e0049545f0ccc2c778b5c3143/prompt_toolkit/shortcuts/prompt.py#L784-L793

This breaks functionality from 1.x, so might consider passing arguments like `history` to `PromptSession`. At the very least, it would be helpful to clarify the documentation.

See https://github.com/click-contrib/click-repl/issues/43 for an issue caused by this change.

**Comment by jonathanslenders** [comment]
Hi @theazureshadow,
That should be fixed in this commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/f17096b4393aaed07fb53af68be6ae718fc60475

**Comment by theazureshadow** [comment]
Thanks!

**Comment by theazureshadow** [comment]
Do you expect to release a new patch version for this?
