### ISSUE TITLE
master is non-fastforward? 

### ISSUE THREAD

**Issue by asmeurer** [jonathanslenders/python-prompt-toolkit#642]
My `master` on my computer is currently at 4476b3c28add85c5a8169fbb81ded8c3b845e588, which is the tagged commit for 1.0.15. However, when I pull, it tries to do a merge (it isn't fast-forward). Was there a force push to master? I think you should do fast-forward pushes only, and enable branch protection in GitHub's settings to avoid this happening in the future. For now, you should merge the old master into the new one to make it fast-forward.

**Comment by jonathanslenders** [comment]
Hi @asmeurer,

The 2.0 branch has been renamed to master, and master has been renamed to 1.0. I know it's not the cleanest thing to do, but it was a one time thing only. Fast-forward was not an option, because the 1.0 branch had a couple of small fixes that didn't had to be merged in 2.0.

**Comment by asmeurer** [comment]
You can do a merge with a strategy that only picks the 2.0 changes, so that the contents of the branch are the same, but git will still consider it to be fast-forward.

**Comment by jonathanslenders** [comment]
Ok, I'll think about that next time.

**Comment by asmeurer** [comment]
You can still do it.

**Comment by jonathanslenders** [comment]
No, I'm sorry, I don't want the latest commits from the 1.0 branch to appear as a parent of the current master branch. It is a little inconvenient, I know, but it's easy enough to delete the local master branch and pull again. Next time, I'll handle it better.

**Comment by asmeurer** [comment]
It's not "a little inconvenient". Everyone who cloned prompt-toolkit before you swapped the branches will be unable to pull (git gives an error). I know how to fix it because I understand what is going on, but people who aren't as adept with git will be a complete lost. 

I don't understand what your concern is with the 1.0 branch. 1.0 won't be fast-forward of master if you merge an earlier commit (ideally, the one from when you swapped the branches), or if you merge it as it is now, it won't be as soon as you make more commits (but again, why is this an issue?).

**Comment by jonathanslenders** [comment]
Ok. Can you explain how I merge 4476b3 into master while ignoring all these changes?

**Comment by asmeurer** [comment]
`git merge 4476b3 -s ours`

You can test it first in a detached HEAD if you want (`git checkout $(git rev-parse HEAD)`). I just did it myself against origin/master and `git diff origin/master` after shows no difference. And then I checked out `origin/master` again and `git merge <the merge commit hash> --ff-only` works, meaning a `pull` would work without creating a new merge commit.

**Comment by jonathanslenders** [comment]
Thank you @asmeurer! I'll try it this evening or tomorrow

**Comment by jonathanslenders** [comment]
Done! Thanks for the explanation @asmeurer.
