### ISSUE TITLE
HtmlLexer moved in Pygments 2.2.0

### ISSUE THREAD

**Issue by tsvenson** [jonathanslenders/python-prompt-toolkit#657]
In: examples/full-screen/full-screen-demo.py

`from pygments.lexers import HtmlLexer`

Needs to be changed to:

`from pygments.lexers.html import HtmlLexer`

When using Pygments 2.2.0

PS: Haven't checked if this change happened in earlier version as I just installed latest version and stumbled on it.

**Comment by jonathanslenders** [comment]
@tsvenson,

I'm not sure this is correct.
Starting from a fresh docker container, it looks like this should work:

![image](https://user-images.githubusercontent.com/216638/42180628-361f2904-7e38-11e8-9e45-d386ecf36398.png)

**Comment by tsvenson** [comment]
The thing that confused me was that in PyCharm, without `.html` then `HtmlLexer` was underlined in red with the error "Cannot find reference 'HtmlLexer' in '__init__.py'". It was also not possible to autocomplete it until I added `.html`.

I does work without for me too though.

**Comment by tsvenson** [comment]
Thanks for the clarification @asmeurer, will report this to Jetbrains and see if it is something that can be addressed in PyCharm then.

**Comment by jonathanslenders** [comment]
Hi @tsvenson,

If you create a pull request, I don't mind merging that, if you think that's better. Otherwise, we can close this issue. Personally, I think the Pygments plugin system is too dynamic.

**Comment by tsvenson** [comment]
Hi @jonathanslenders,

Done. Even though it does work, this is better as it avoids the confusion I experienced while using PyCharm.

**Comment by asmeurer** [comment]
I spoke to some pycharm devs here at SciPy. Apparently if pygments stubs were added to https://github.com/python/typeshed it would fix the issue (pycharm uses typeshed).

**Comment by jonathanslenders** [comment]
@tsvenson: Can we close this issue?

**Comment by tsvenson** [comment]
@jonathanslenders: Of course. Thanks for letting me contribute!
