### ISSUE TITLE
Can't get completer to work using dynamic list

### ISSUE THREAD

**Issue by mudderman** [jonathanslenders/python-prompt-toolkit#663]
I have successfully made a completer in which I fetch data from internet and displays it and all that black magic. 

My problem now is that I have another completer which based on a decorator gives me a list of possible commands in a class. See the example:

```python
from __future__ import unicode_literals, print_function

from prompt_toolkit import prompt, PromptSession
from prompt_toolkit.completion import WordCompleter, Completer, Completion


def commandFunction():
    methods = []
    def register(func):
        methods.append(func.__name__)
        return func
    register.all = methods
    return register

PublicCommand = commandFunction()

class TestClass(object):
    @PublicCommand
    def help(self):
        print('This is the help command')

    @PublicCommand
    def login(self):
        print('This is the login command')

    def secret(self):
        print('This is a secret command')


class CommandCompleter(Completer):
    def __init__(self, public_commands):
        super(CommandCompleter, self).__init__()
        # self.public_commands = ['one', 'two'] # this works fine
        self.public_commands = public_commands # this does not work

    def get_completions(self, document, event):
        text = document.text

        # print(self.public_commands) # prints out ['help', 'login']

        for cmd in self.public_commands:
            yield Completion(cmd)

def main():
    session = PromptSession(completer=CommandCompleter(PublicCommand.all))
    # session = PromptSession(completer=WordCompleter(PublicCommand.all)) # does not work either

    while True:
        try:
            command = session.prompt("> ")
        except KeyboardInterrupt:
            continue
        except EOFError:
            break

        try:
            getattr(test_class, command)()
        except:
            print('Got unrecognized command "{}"'.format(command))

if __name__ == '__main__':
    main()
```

The @PublicCommand pushes the name of method it's decorating into a list and I try to use that list as suggestions in the completer (this is a basic sample, the finished product will have more functionality than this). But I can't get it to work. Nor does it work using the shipped WordCompleter.

I can't for the life of me figure it out!

**Comment by lwm** [comment]
Hmmm, not really sure from reading this over a few times.

Have you tried dropping into the debugger and inspecting:

https://github.com/jonathanslenders/python-prompt-toolkit/blob/deb7488b7b24814ae12518639a2fbe0b67c43ec3/prompt_toolkit/completion/word_completer.py#L38

Any more information to provide for this report?

**Comment by mudderman** [comment]
Hi @jonathanslenders 

Having it the way I have it actually works for me.

The thing that does not work for me is that I get no list of autocomplete suggestions. :(

**Comment by jonathanslenders** [comment]
I just copy/pasted the code that you shared above, and the autocompletions are working fine. (latest prompt_toolkit master here). I'm not sure I understand what's going on.

**Comment by mudderman** [comment]
My standard env is latest prompt_toolkit using python 2.7.12 running in cmder on win 10. Then it won't work for me.

Just tried it on python 3.4.3 in the "Bash on Ubunbtu on Windows" and it works fine.

So maybe it's just time for me to hop on over to python 3...

Thank you.

**Comment by mudderman** [comment]
Actually just found out how to make it work in my python 2 env.

Either i wrap the adding of the function name into the list in a unicode:

```python
methods.append(unicode(func.__name__))
```

or the yield in the CommandCompleter:

```python
yield Completion(unicode(cmd))
```

\o/
