### ISSUE TITLE
Terminal windows exists on Windows 10 build 17692

### ISSUE THREAD

**Issue by melund** [jonathanslenders/python-prompt-toolkit#664]
I am having problems with prompt-toolkit 1 after getting the newest update to Windows (Insiders slow ring build 17692). 

Both xonsh (#2703) and ptpython with ptk1 causes the terminal window to exit when I start the programs. No error messages or anything. The conhost terminal window just disappears.  

I haven't tried to debug this yet, to see when it happens. But I will try it this weekend. 

I would really love to see if this is a problem with PTK 2 as well. Is there any application I could try to test that? 

![test](https://user-images.githubusercontent.com/1038978/42321155-30008172-8058-11e8-8395-4e87fddaa4ba.gif)

**Comment by melund** [comment]
I have just tried IPython and ptpython with PTK2 as well. 

Unfortunately, the same behaviour. Terminal window just shuts down. 

I guess this is most likely a bug in the console on Windows. So maybe I should also report it here: https://github.com/Microsoft/console/issues

@jonathanslenders Any pointers to how I can best help solve and debug it before we report it to the console team?

**Comment by scopatz** [comment]
That is not good. Maybe that console repo is the right place to bring it up.

**Comment by scopatz** [comment]
Ahh that is good to know!

**Comment by melund** [comment]
@jonathanslenders Here is some more debug info. 

The crash happens when the PTK1 tries to call [`_erase()`](https://github.com/jonathanslenders/python-prompt-toolkit/blob/1.0.15/prompt_toolkit/terminal/win32_output.py#L210) 

The following is a close as I could debug before the terminal disapears. 
```
(Pdb) where
  c:\users\mel\documents\scratch\ptpython\debug.py(2)<module>()
-> run()
  c:\users\mel\documents\scratch\ptpython\ptpython\entry_points\run_ptpython.py(71)run()
-> title='Python REPL (ptpython)')
  c:\users\mel\documents\scratch\ptpython\ptpython\repl.py(315)embed()
-> cli.run()
  c:\users\mel\anaconda3\lib\site-packages\prompt_toolkit\interface.py(400)run()
-> assert pre_run is None or callable(pre_run)
  c:\users\mel\anaconda3\lib\site-packages\prompt_toolkit\interface.py(358)_redraw()
-> self.renderer.render(self, self.layout, is_done=self.is_done)
  c:\users\mel\anaconda3\lib\site-packages\prompt_toolkit\renderer.py(450)render()
-> previous_width=(self._last_size.columns if self._last_size else 0))
  c:\users\mel\anaconda3\lib\site-packages\prompt_toolkit\renderer.py(128)_output_screen_diff()
-> output.erase_down()
  c:\users\mel\anaconda3\lib\site-packages\prompt_toolkit\terminal\win32_output.py(200)erase_down()
-> self._erase(start, length)
  c:\users\mel\anaconda3\lib\site-packages\prompt_toolkit\terminal\win32_output.py(216)_erase()
-> byref(chars_written))
> c:\users\mel\anaconda3\lib\site-packages\prompt_toolkit\terminal\win32_output.py(135)_winapi()
-> return func(*a, **kw)
```

I also captured the debug render info from the [`_winapi()`](https://github.com/jonathanslenders/python-prompt-toolkit/blob/1.0.15/prompt_toolkit/terminal/win32_output.py#L128) wrapper. 

```
b"'FillConsoleOutputCharacterA'\n"
b"     68, c_char(b' '), c_ulong(1076400), c_long(2031616), <cparam 'P' (000002D942529A10)>\n"
b"     <class 'int'>, <class 'ctypes.c_char'>, <class 'ctypes.c_ulong'>, <class 'ctypes.c_long'>, <class 'CArgObject'>\n"
```

Hope this helps you a bit.

**Comment by melund** [comment]
> Ahh that is good to know!

@scopatz  Yes. The best fix in xonsh is probably to upgrade to PTK 2. But I hope IPython will also follow soon. Otherwise, it will be a little annoying.

**Comment by jonathanslenders** [comment]
@melund, thank you for debugging this so far!
The reason that PTK 2 doesn't crash is probably because it detects that the Windows console now supports ANSI escape sequences, and it will output that instead.

I hope to find some time this weekend to debug it.

IPython merged a patch for PTK 2 support, so I think the next (major) release will include it.

**Comment by melund** [comment]
> IPython merged a patch for PTK 2 support, so I think the next (major) release will include it.

Thanks for letting us know. That is great. @scopatz timing xonsh support for ptk2 with the IPython release would probably be a good idea. Unless we plan to support both versions.

**Comment by jonathanslenders** [comment]
I have some issues upgrading to the latest Windows 10. (see screenshot below...) If someone has some time to debug this bug above, that would be great. I'll see whether I can fix my PC in the meantime.

--

![image](https://user-images.githubusercontent.com/216638/42420924-804c2470-82cd-11e8-9dd4-5e474e9a69bc.png)

**Comment by jonathanslenders** [comment]
So I managed to update.

While working on pymux, in certain situations, I could make the console window crash as well, but only after running my server/client experiment, detaching the pymux client, waiting until the Python process is finished, and then typing "ls" would make the console window close. Very weird. I wonder whether that's a bug in Windows, or whether I'm leaving the console in a bad state.
I can't reproduce it however with simple PTK prompts, those work fine here...

**Comment by melund** [comment]
> I can't reproduce it however with simple PTK prompts, those work fine here...

That is great to hear. My Windows installation just updated to build 17713.rs5, and that has solved the problem for me as well.

**Comment by melund** [comment]
Unless @jonathanslenders has any objections I think I will close this issue.

**Comment by jonathanslenders** [comment]
That's fine. Thanks! We'll open again if needed.
