### ISSUE TITLE
PKT2 - History Subclass cannot be passed to PromptSession without __bool__

### ISSUE THREAD

**Issue by scopatz** [jonathanslenders/python-prompt-toolkit#684]
While updating xonsh to PTK v2, we discovered that a custom History subclass will fallback to the `InMemory` history backend, unless you put something to make it it `bool(hist) is True`.  For example, 

```python
from prompt_toolkit.history import History
from prompt_toolkit.shortcuts.prompt import PromptSession

class MyHistory(History):

   def __bool__(self):
        return True

    ...

app = PromptSession(history=MyHistory())
isinstance(app.history, MyHistory) is False
```

Oddly this does not happen when using the `ThreadedHistory` class.

**Comment by jonathanslenders** [comment]
Hi @scopatz,
Is it possible that your ``MyHistory`` implements a ``__len__``, which returns 0? You can completely remove this ``__len__``.

**Comment by scopatz** [comment]
Hey @jonathanslenders - Ahh yes, it does have a len that returns 0. Initially.  We wanted to use the ThreadedHistory anyway, so I suppose this isn't a big deal. Thanks!
