### ISSUE TITLE
PromptSession.prompt() default argument only works once

### ISSUE THREAD

**Issue by Blue9** [jonathanslenders/python-prompt-toolkit#685]
Passing in a default value to `PromptSession.prompt` only works on the first call to `prompt`. Example code:

    import prompt_toolkit
    session = prompt_toolkit.PromptSession()
    good = session.prompt('How are you? ', default='good')  # Output: How are you? good
    bad = session.prompt('How are you? ', default='bad')  # Output: How are you? 

The default text is stored in a `Document` object which is used to set the default buffer ([code](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/shortcuts/prompt.py#L714)). On every call to prompt, [this](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/application/application.py#L489) loop is executed. On the first call to `prompt`, `self.pre_run_callables` is an empty list. On subsequent calls, `self.pre_run_callables` contains [`Buffer.reset`](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/buffer.py#L268), and since no arguments are passed in, `document` defaults to `None`. I think this somehow overrides the original default text. Is there a fix for this?

**Comment by jonathanslenders** [comment]
See: https://github.com/jonathanslenders/python-prompt-toolkit/issues/644

It should be fixed in the master branch. I hope to push a new release this weekend.

Thanks for taking the time to troubleshoot!

**Comment by Blue9** [comment]
Thanks!
