### ISSUE TITLE
Large number of threads created when run under PyCharm

### ISSUE THREAD

**Issue by vlovich** [jonathanslenders/python-prompt-toolkit#687]
request_absolute_cursor_position keeps getting called when running a simple app which starts a new thread if the CPR state is unknown (default) to do a timeout set of NOT_SUPPORTED.  However, there's no check to enforce that only 1 such timeout thread exists.  Running in PyCharm with a debugger can easily get >100 threads created & completely bog down the debugger.

**Comment by jonathanslenders** [comment]
This should be fixed now.
