### ISSUE TITLE
Buffer dimensions based on content

### ISSUE THREAD

**Issue by 6r1d** [jonathanslenders/python-prompt-toolkit#697]
I want buffer height to extend depending on the text inside, but when I tried using `Dimension` with minimum and maximum height, buffer size stayed on maximum value. Is there any better way than using a function like `get_input_height` in this example?

    from __future__ import unicode_literals
    import os
    import asyncio
    from prompt_toolkit.eventloop import use_asyncio_event_loop
    from prompt_toolkit.application import Application
    from prompt_toolkit.buffer import Buffer
    from prompt_toolkit.key_binding import KeyBindings
    from prompt_toolkit.layout.containers import HSplit, Window, FloatContainer, \
        Float
    from prompt_toolkit.layout.controls import BufferControl
    from prompt_toolkit.layout.layout import Layout
    from prompt_toolkit.layout.menus import CompletionsMenu
    from prompt_toolkit.document import Document
    from prompt_toolkit.history import InMemoryHistory
    from prompt_toolkit.layout.dimension import Dimension, LayoutDimension
    from prompt_toolkit.filters import has_focus

    use_asyncio_event_loop()

    history = InMemoryHistory()

    input_buffer = Buffer(multiline=True)
    history_buffer = Buffer()

    def get_input_height():
        height = len(input_buffer.text.splitlines()) or 1
        if height > 5:
            height = 5
        return Dimension(min=1, max=height)

    body = FloatContainer(
        content=HSplit([
            Window(BufferControl(
                buffer=history_buffer
            )),
            Window(height=1, char='-', style='class:line'),
            Window(
                BufferControl(input_buffer),
                height=get_input_height,
                ignore_content_height=False
            ),
        ]),
        floats=[
            Float(xcursor=True,
                  ycursor=True,
                  content=CompletionsMenu(max_height=16, scroll_offset=1))
        ]
    )

    kb = KeyBindings()

    @kb.add('c-c')
    def _(event):
        " Quit application. "
        event.app.exit()

    @kb.add('enter', filter=has_focus(input_buffer))
    def _(event):
        b = event.current_buffer
        if b.validate():
            try:
                output = '{}\n'.format(b.text)
            except BaseException as e:
                output = '\n{}'.format(e)
            b.reset(append_to_history=True)
            new_text = history_buffer.text + output
            history_buffer.document = Document(text=new_text, cursor_position=len(new_text))
            input_buffer.text = ''

    layout = Layout(body)
    layout.focus(input_buffer)

    application = Application(
        layout=layout,
        key_bindings=kb,
        full_screen=True
    )

    if __name__ == '__main__':
        asyncio.get_event_loop().run_until_complete(
            application.run_async().to_asyncio_future()
        )

**Comment by jonathanslenders** [comment]
Hi @6r1d,

I've found two working solutions:

1. Set ``dont_extend_height=True`` on the second control (and ``ignore_content_height=False`` as well, but that's the default). Don't set any height for the first content. This would be my preferred solution.

```python
body = FloatContainer(
    content=HSplit([
        Window(BufferControl(
            buffer=history_buffer,
        )),
        Window(height=1, char='-', style='class:line'),
        Window(
            BufferControl(input_buffer),
            dont_extend_height=True,
        ),
    ]),
    floats=[
        Float(xcursor=True,
              ycursor=True,
              content=CompletionsMenu(max_height=16, scroll_offset=1))
    ]
)
```

2. The alternative is to pass a very big preferred height to the first element. This way, it will consume all the space, except what is required by the second control. (I have to look into how this works exactly, because, I forgot some details myself.)

```python
body = FloatContainer(
    content=HSplit([
        Window(BufferControl(
            buffer=history_buffer,
        ),
        height=Dimension(preferred=1000000),
        ),
        Window(height=1, char='-', style='class:line'),
        Window(
            BufferControl(input_buffer),
        ),
    ]),
    floats=[
        Float(xcursor=True,
              ycursor=True,
              content=CompletionsMenu(max_height=16, scroll_offset=1))
    ]
)
```

**Comment by jonathanslenders** [comment]
Closing this. Feel free to open again if the above answer is not sufficient.
