### ISSUE TITLE
How to handle changed ansicolor names?

### ISSUE THREAD

**Issue by melund** [jonathanslenders/python-prompt-toolkit#700]
@jonathanslenders It seems that the interpretation of all the ansi-color names changed with PTK2. 

Now "ansired" is the dark color (instead of `ansidarkred`) and `ansibrightred` is new key for bright red. 

In xonsh (atleast on windows without VT100) going to PTK 2 changes almost all colors from bright to dark (because on windows we had a hack that only used light colors)

I like the new names much better but  they conflict a bit with pygments which still uses the old names. 

Shouldn't functions like `style_from_pygments_cls()` and `style_from_pygments_dict()` map the  old names to the new names?

   
|   PTK 2             |      Pygments       |
|---------------------|---------------------|
|  ansiblack          |      ansiblack      |
|  ansired            |      ansidarkred    |
|  ansigreen          |      ansidarkgreen  |
|  ansiyellow         |      ansibrown      |
|  ansiblue           |      ansidarkblue   |
|  ansimagenta        |      ansipurple     |
|  ansicyan           |      ansiteal       | 
|  ansigray           |      ansilightgray  | 
|  ansibrightblack    |      ansidarkgray   |
|  ansibrightred      |      ansired        |
|  ansibrightgreen    |      ansigreen      |
|  ansibrightyellow   |      ansiyellow     | 
|  ansibrightblue     |      ansiblue       |
|  ansibrightmagenta  |      ansifuchsia    |
|  ansibrightcyan     |      ansiturquoise  |
|  ansiwhite          |      ansiwhite      |

**Comment by melund** [comment]
Alternatively, we (in xonsh) could change all the ansicolor names to the new names, and add wrapper functions around the styles if people are using PTK1. Do you have any preferences about this @scopatz ?

**Comment by melund** [comment]
Ahh. I see there is already partial [alias handling](https://github.com/jonathanslenders/python-prompt-toolkit/blob/deb7488b7b24814ae12518639a2fbe0b67c43ec3/prompt_toolkit/styles/base.py#L61-L72) in prompt_toolkit for the new color names. But it doesn't take into account that some names that were previously bright are now dark. 

I think the best option is to change all the ansi color names in xonsh to the new names used in PTK 2 (e.g. `#ansired` to `ansibrightred`) and also drop the hashtag `#` prefix. 

Then we can implement a mapping from the new names to the old names when people use PTK1. 

What is your recommendation @jonathanslenders

**Comment by jonathanslenders** [comment]
@melund,

This is correct.
IMHO, what we have in Pygments and prompt_toolkit 1.0 is a bug, and people have pointed this out.
I'm not going to change the existing behavior for PTK1 anymore, so you can create a mapping table and change the color names back if PTK1 is used.

See:  https://github.com/jonathanslenders/python-prompt-toolkit/issues/559
https://github.com/jonathanslenders/python-prompt-toolkit/issues/423

**Comment by melund** [comment]
Great. I will make the necessary changes to xonsh. Closing this now.

**Comment by jonathanslenders** [comment]
For Pygments, see: https://bitbucket.org/birkenfeld/pygments-main/issues/1463/ansi-color-names-not-correct
