### ISSUE TITLE
prompt_continuation without multiline

### ISSUE THREAD

**Issue by njalerikson** [jonathanslenders/python-prompt-toolkit#701]
I want to be able to effectively say this:

```python
from prompt_toolkit import prompt
from lorem import text

def prompt_continuation(width, line_number, is_soft_wrap):
    return ' ' * width

prompt("THIS> ",
       prompt_continuation=prompt_continuation,
       default=text())
```

Unfortunately `prompt_continuation` is not used unless `multiline` is enabled. This can been see in the src here:

https://github.com/jonathanslenders/python-prompt-toolkit/blob/b7ab3ba67df2e7dbf63463fb98f817878dfd256a/prompt_toolkit/shortcuts/prompt.py#L439-L446

Clearly I could manually maneuver around this by implementing my own "shortcut" but before doing so I'm wondering if there is an obvious reason for why the `prompt_continuation` is dependent on `multiline`?

**Comment by jonathanslenders** [comment]
Hi @njalerikson,

Yes, there was a reason for this. The prompt continuation creates a left margin, where every line of that margin has the same width. Even if this prompt_continuation function doesn't return anything, the same width as the first line is used. A normal prompt doesn't create a margin, but uses an "InputProcessor``, something that transforms the input of a buffer and in this case inserts the prompt in front.

Your question however is a good one. I realize that both implementations are not flexible enough to support this use case. It should become the responsible of the ``Window`` class to insert the prompt in front of every line individually.

So right now, it's unfortunately not possible, but it shouldn't be too hard to fix.

It's this ``_copy_body`` method where the prompt should be inserted before every line:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/layout/containers.py#L1545
This means that ``Window`` should receive a ``prompt(_continuation)`` argument somehow, and we can deprecate ``PromptMargin`` and ``BeforeInput``.

**Comment by jonathanslenders** [comment]
Hi @njalerikson,
I started experimenting with this and ended up with the following pull request: https://github.com/jonathanslenders/python-prompt-toolkit/pull/717
It needs a bit more testing, and I'm not entirely sure what happens in a couple of special cases, but it seems doable. Feel free to test it. I think the code that you had should work now.

**Comment by jonathanslenders** [comment]
Hi @njalerikson, this has been implemented and is part of the last release. Thanks again for the suggestion!
