### ISSUE TITLE
Help: scrolling in FormattedTextControl

### ISSUE THREAD

**Issue by alejandrogallo** [jonathanslenders/python-prompt-toolkit#702]
Hi

I am the main developer of [ papis ]( https://github.com/papis/papis ) and I
am currently developing a so-called papis using your wonderful library.

I don't seem to be able to implement a scrolling in the FormattedTextControl,
I have some html formatted text, that I then convert into HTML FormattedText
and gets fed into the FormattedTextControl, but as much as I've tried to
understand how the scrolling could work, I failed.

https://asciinema.org/a/g04fnUFjVuk4cEhvULBfC5pU2

Above is an asciinema example of what I would like to scroll.

And here is the code for it

https://github.com/papis/papis/blob/click/papis/pick.py

So the question is:

  How can I implement scroll in the content of FormattedTextControl

Thanks so much!
Ale

**Comment by alejandrogallo** [comment]
Nevermind, I already figured out, it's just implementin get_cursor_position function and it automatically
scrolls down if you surpass the displayed lines, thanks anyways!

**Comment by MrMino** [comment]
Example:

```
from prompt_toolkit.data_structures import Point
from prompt_toolkit.layout import FormattedTextControl

row_position = 0
control = FormattedTextControl(
    '\n'.join(str(n) for n in range(80)),
    get_cursor_position=lambda: Point(0, row_position)
)
```

Put the `control` above into a Window. Changing `row_position` in a keybinding (might also require using `app.invalidate()`) should now change the position of the formatted text cursor.
