### ISSUE TITLE
RadioList won't focus

### ISSUE THREAD

**Issue by stloma** [jonathanslenders/python-prompt-toolkit#704]
Hi there. Thanks for this great library!

Something broke in v2.0.4 where RadioList won't take focus (I confirmed it working in v2.0.3).

An example of this not working is in: `examples/full-screen/full-screen-demo.py`. If you tab around, the radio dialog will be skipped.

**Comment by jonathanslenders** [comment]
Hi @stloma,
This is indeed a bug! Thanks a lot for reporting!

I'll fix it asap. (Or if anybody find it and does a pull request, I'll also merge it.)

**Comment by jonathanslenders** [comment]
This should fix it: https://github.com/jonathanslenders/python-prompt-toolkit/commit/ea93753ba6eaae23f8fac7f94c91f74d587155a5
Can you try again?

**Comment by stloma** [comment]
Awesome, that fixed it!

That fix makes sense too; I tried a couple things the past few days so I could submit a PR, but didn't quite get it in the time I had.

Thanks again for this project!

**Comment by jonathanslenders** [comment]
You're welcome!
I'll close this. Feel free to open again if needed.
