### ISSUE TITLE
Fix tests or drop Python 2.6?

### ISSUE THREAD

**Issue by techtonik** [jonathanslenders/python-prompt-toolkit#708]
Failing tests make me uneasy/
https://travis-ci.org/jonathanslenders/python-prompt-toolkit/jobs/414685909

**Comment by jonathanslenders** [comment]
It looks like restarting the build worked. I guess this was a Travis issue.
Python 2.6 will still be supported for now. At some point in the future, we'll probably drop Python 2 completely, and use asyncio natively.
