### ISSUE TITLE
split-screen.py doesn't work without modification under Python 3

### ISSUE THREAD

**Issue by duck57** [jonathanslenders/python-prompt-toolkit#710]
Under Python 2, the `split-screen.py` demo works just fine.  However, when changing to Python 3 (including changing to `#!/usr/bin/env python3` at the start of the file), it gives me

`ImportError: cannot import name 'KeyBindings' from 'prompt_toolkit.key_binding' (/usr/local/lib/python3.7/site-packages/prompt_toolkit/key_binding/__init__.py)`

instead of the demo.

**Comment by toolleeo** [comment]
Everything works fine - including `split-screen.py` - with `prompt_toolkit` commit `48d7fe0f` under
```
$ python3
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
```
@duck57 : It would be better to provide more context regarding your environment.

**Comment by duck57** [comment]
Telling pip3 to uninstall and reinstall prompt_toolkit fixed things.

— Chris

**Comment by jonathanslenders** [comment]
Hi @duck57,
Good to hear you were able to fix it!
I'm closing this issue for now. Feel free to open a new one if you have other questions.
Cheers,
Jonathan
