### ISSUE TITLE
Looking for an example to use prompt-toolkit with ssh/telnet 

### ISSUE THREAD

**Issue by 1001QAdotNET** [jonathanslenders/python-prompt-toolkit#714]
Hi 

I am just curious if this can be used to highlight text in the output of the commands that I am sending to a remote device via an ssh or telnet session using libraries like paramiko

Please if you know of an example I would be grateful if you can post the link in reply to this question

thanks

**Comment by jonathanslenders** [comment]
Hi @1001QAdotNET,

prompt_toolkit is a library to create interactive applications. If you do the interaction with Paramiko, the only thing that remains to be done is printing the output to the terminal.

prompt_toolkit comes with some utilities to print "Formatted Text", but it requires some external lexer like Pygments to do syntax highlighting.
Check out the documentation about formatted text: https://python-prompt-toolkit.readthedocs.io/en/2.0/pages/printing_text.html
