### ISSUE TITLE
Does prompt-toolkit have a version api?

### ISSUE THREAD

**Issue by ReddyKilowatt** [jonathanslenders/python-prompt-toolkit#719]
All python packages should have a version api that returns a string, as well as a tuple that returns the version and subversions numerically.

These allow logging of the package version, as well as having applications that can make decisions that are applicable for older/newer versions.

It looks like prompt-toolkit does not have either of these.

**Comment by jonathanslenders** [comment]
Hi @ReddyKilowatt,

Can you point me to the Python documentation where this is specified. For the "requests" library for instance, I only find ``__version__``.

**Comment by jonathanslenders** [comment]
I added ``prompt_toolkit.VERSION``, so I'm closing this issue.
