### ISSUE TITLE
Conpty compatibility ? PTY+ utf-8 on windows10 fall 2018

### ISSUE THREAD

**Issue by stonebig** [jonathanslenders/python-prompt-toolkit#723]
https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/

I guess it's good news  for Python-prompt.

**Comment by jonathanslenders** [comment]
Hi @stonebig,

Yes, this is absolutely great news. I've been following this blog for some time.

For prompt_toolkit, I think this doesn't offer anything new. However, in prompt_toolkit 2.0, we already take advantage of Windows 10 supporting ANSI escapes sequences for the output, and we use that when possible. This means we have 24 bit color support and better rendering speeds.

Conpty however is what I think will help me improve ptterm on Windows (https://github.com/jonathanslenders/ptterm) Right now, we use winpty which isn't that great, and the Python library, yawinpty that I use there, seems to be removed from GitHub. Windows PTY support will simplify things a lot.
