### ISSUE TITLE
Switch Meta+Enter with Enter for multilne inputs

### ISSUE THREAD

**Issue by certik** [jonathanslenders/python-prompt-toolkit#728]
When using [multiline inputs](https://python-prompt-toolkit.readthedocs.io/en/stable/pages/asking_for_input.html#multiline-input), one has to use Meta+Enter to submit the input. Since most of the time, I use single lines, I would like to just use Enter to submit it, and use Meta+Enter to create another line.

What is the best way to do that?

**Comment by jonathanslenders** [comment]
Hi @certik,

This will only work in Emacs input mode (not for Vi mode, because escape always returns to navigation mode, from where you can't insert text).

If you want this, you can create a custom key bindings object, something like:

```python
from prompt_toolkit.key_binding import KeyBindings
from prompt_toolkit.shortcuts import prompt

kb = KeyBindings()

@kb.add('escape', 'enter')
def _(event):
    event.current_buffer.insert_text('\n')

@kb.add('enter')
def _(event):
    event.current_buffer.validate_and_handle()

result = prompt('>', key_bindings=kb, multiline=True)
print(result)
```

**Comment by certik** [comment]
@jonathanslenders I updated to 2.0 and tried your suggestion and it works! Thank you.
