### ISSUE TITLE
Add PyInquirer to Python Prompt Toolkit

### ISSUE THREAD

**Issue by CITGuru** [jonathanslenders/python-prompt-toolkit#729]
Hello,
I'd glad if PyInquirer - https://github.com/CITGuru/PyInquirer/ is added to prompr-toolkit. Its a python module for Inquirer.js clone. Its built base on Inquirer.js and works the same.

**Comment by jonathanslenders** [comment]
Hi @CITGuru, that's a nice project!
I've added it to the README: https://github.com/jonathanslenders/python-prompt-toolkit/commit/c7986732448a49ac2070752e1c636ecaeb7237ef

Feel free to create a pull request, if you prefer a different description.

**Comment by CITGuru** [comment]
Great! :+1:
