### ISSUE TITLE
callback at start of prompt()?

### ISSUE THREAD

**Issue by frankseide** [jonathanslenders/python-prompt-toolkit#734]
Hi, is there a way to have a callback function called first thing from prompt(), before any key is entered?

Specifically, I would like to pre-populate the input (like `prompt(default=...)` but position the cursor on a specific position. I couldn't find an option for this.

Thanks!

**Comment by jonathanslenders** [comment]
Hi @frankseide,
Can you have a look at this pull request: https://github.com/jonathanslenders/python-prompt-toolkit/pull/736
Does that do what you need?
