### ISSUE TITLE
completion broken?

### ISSUE THREAD

**Issue by 2sn** [jonathanslenders/python-prompt-toolkit#743]
following the example from https://python-prompt-toolkit.readthedocs.io/en/2.0.5/pages/asking_for_input.html

```python3
from prompt_toolkit import prompt
from prompt_toolkit.completion import WordCompleter

html_completer = WordCompleter(['<html>', '<body>', '<head>', '<title>'])
text = prompt('Enter HTML: ', completer=html_completer)
print('You said: %s' % text)
```

when I type `<` I get the drop-down box as shown and can go down the list using `<TAB>`, but when I also type `b` so the total is `<b`, `<TAB>` no longer does anything, let alone completion to `<body>`.  The latter is what I would have expected, but maybe I misunderstand?  This is certainly what my bash shell or emacs would do.  If I don't misunderstand how completion is supposed to work, is Version 2.0.5 ready to use in real-world applications yet?

**Comment by jonathanslenders** [comment]
Hi @2sn,

You'll have to pass ``WORD=True`` as an argument to ``WordCompleter``. This will ensure that it defines a "word" as a sequence of non whitespace characters, instead of ``[a-zA-Z]`` or something like that. This is required, because you have special characters as part of the words.
