### ISSUE TITLE
`TextArea.accept_handler` does not get called

### ISSUE THREAD

**Issue by nickoala** [jonathanslenders/python-prompt-toolkit#749]
Hello, I was trying the `full-screen/calculator.py` example, and found that the `accept_handler` attached to a `TextArea` doesn't really work. The `accept_handler` does not seem to get called when I type `enter`, or `escape-enter`.

To confirm the issue, I simplify the example into a somewhat bare-bone program like this:

```python
from prompt_toolkit.application import Application
from prompt_toolkit.key_binding import KeyBindings
from prompt_toolkit.widgets import TextArea
from prompt_toolkit.layout.layout import Layout
from prompt_toolkit.application.current import get_app

input_field = TextArea(
    height=1, prompt='>>> ', multiline=False, wrap_lines=False)

def accept(buff):
    get_app().exit()

input_field.accept_handler = accept

kb = KeyBindings()

@kb.add('c-c')
@kb.add('c-q')
def _(event):
    event.app.exit()

application = Application(
    layout=Layout(input_field),
    key_bindings=kb,
    full_screen=True)

application.run()
```

Still, nothing happens when I type `enter` or `escape-enter`.

In case you need to know, I am on:

- Ubuntu 18.04
- Python 3.6.6

Thanks for the great toolkit!

**Comment by jonathanslenders** [comment]
Hi @nickoala,
Thank you for reporting this issue!
Can you try again with the latest prompt_toolkit release or with the master branch. I believe this issue was fixed recently.

When I execute your example code, it executes fine for me.

**Comment by nickoala** [comment]
I just tried it on prompt_toolkit 2.0.6, and it works!

Thank you for fixing it :+1:
