### ISSUE TITLE
solved: release 2.0.6 fixed the crash of xonsh, the py shell

### ISSUE THREAD

**Issue by dimyme** [jonathanslenders/python-prompt-toolkit#753]
the older pyPI version used to crash xonshell right upon launch of    **xonsh**

**everything is back to working normal** with xonshell now. Thanks!  well done !

**issue resolved.** just so you know or others know that they ought to upgrade their py-pr-tk to rel. 2.0.6
if error msg from the prmpt-tk appears.

**Comment by jonathanslenders** [comment]
Thanks @dimyme! That's great.
I'll try to test Xonsh with prompt_toolkit before pushing new releases.
