### ISSUE TITLE
[RFC] Config class and tools

### ISSUE THREAD

**Issue by imomaliev** [jonathanslenders/python-prompt-toolkit#755]
Hi, what do you think about providing some type of tools or classes to handle config files. For example to store history in https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html https://github.com/srstevenson/xdg. Or providing settings files or reading from `.env`?

**Comment by jonathanslenders** [comment]
Hi @imomaliev,
Thank you for the suggestion.
The XDG specification looks good. I've actually been thinking about using it for ptpython, pyvim and pymux.

However, providing configuration classes and tools is not really prompt_toolkit's responsibility. I'm not planning to make it part of this library. If somebody wants to use XDG, they can install it and pass the appropriate paths.

Thanks for the understanding.
