### ISSUE TITLE
Broken on Windows: ImportError: cannot import name KeyPress

### ISSUE THREAD

**Issue by ionelmc** [jonathanslenders/python-prompt-toolkit#80]
This happens on Windows 8.1 and Python 2.7.9 (tested from https://github.com/jonathanslenders/python-prompt-toolkit/tree/d87196e3d46e9024117c477579a7fda4cab2be90)
```
C:\Users\ionel_000>ptpython
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\ptpython.exe\__main__.py", line 5, in <module>
  File "C:\Python27\lib\site-packages\prompt_toolkit\__init__.py", line 31, in <module>
    from .terminal.win32_input import raw_mode, cooked_mode
  File "C:\Python27\lib\site-packages\prompt_toolkit\terminal\win32_input.py", line 5, in <module>
    from ..key_binding import KeyPress
ImportError: cannot import name KeyPress
```

**Comment by ionelmc** [comment]
Perhaps some AppVeyor could be used to have CI testing for this on Windows (akin to Travis).

**Comment by jonathanslenders** [comment]
Thanks for reporting @ionelmc . I'll try to fix this asap!
I'll have a look at AppVeyor.

**Comment by ionelmc** [comment]
Here's a guide to get you started with AppVeyor: https://packaging.python.org/en/latest/appveyor.html#appveyor-yml

**Comment by jonathanslenders** [comment]
Hi @ionelmc ,

https://github.com/jonathanslenders/python-prompt-toolkit/commit/67a489f7856daa3b7df9a22578008670278befb9 and https://github.com/jonathanslenders/python-prompt-toolkit/commit/a5aba5d21cff9879792c5ea6e763628725562742  should fix Windows support again!

Thanks for reporting! If I find time, I have a look at Appveyor.

**Comment by jonathanslenders** [comment]
I created an issue for the Appveyor part: https://github.com/jonathanslenders/python-prompt-toolkit/issues/82
