### ISSUE TITLE
Does not handle f1-f4 in rxvt-unicode / use terminfo?

### ISSUE THREAD

**Issue by blueyed** [jonathanslenders/python-prompt-toolkit#83]
rxvt-unicode has non-standard escape codes for `F1` to `F1`: it uses `\E[11~` to `\E[14~`, instead of `\EOP` to `\EOS`.

This can be seen in `infocmp -1`.

Do you plan to use `terminfo`, instead of the hard coded escape sequences?

(I've came here because I've noticed that the function keys do not work in https://github.com/amjith/pgcli)

**Comment by jonathanslenders** [comment]
Right now, I had no plans yet to use terminfo (maybe in the future), but I can easily support these sequences. (I don't think they conflict with any other sequences.)
Thanks for reporting! I'll do this asap.

**Comment by jonathanslenders** [comment]
Ok, I just see your pull request. Thanks!
