### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by macobo** [jonathanslenders/python-prompt-toolkit#85]
I'm eager to start using ctrl-arrow functionality.

Mind bumping the version and releasing to pypi?

**Comment by jonathanslenders** [comment]
Hi @macobo . Good to remind me! I should be able to release a new version today or tomorrow.

**Comment by jonathanslenders** [comment]
HI @macobo, 0.26 has been released on Pypi. But please not that if you had custom key bindings, that this api has been changed. If you encounter any issues, please tell me.

Cheers!

**Comment by macobo** [comment]
Thanks for the pointers! Got everything upgraded quite quickly.
