### ISSUE TITLE
Prompt Search mode doesn't allow backspace

### ISSUE THREAD

**Issue by amjith** [jonathanslenders/python-prompt-toolkit#87]
Right now when I press Ctrl-R to go into the prompt search mode, I'm unable to correct my search term using backspace or Ctrl-W or Ctrl-U. 

But all those keys work fine if I use the SearchToolbar mode.

**Comment by jonathanslenders** [comment]
Fixed in: https://github.com/jonathanslenders/python-prompt-toolkit/commit/e6660b5010bd1e7feacc1e65c6a924090087890d

Does GNU readline support Ctrl-W/U in incremental search?

**Comment by amjith** [comment]
No, I was wrong.

I will try the patch. 

Although readline does support C-E, C-A, C-F, C-B, which basically kicks you out of the search mode and puts the cursor on the matching character and does the appropriate movement (C-A: home, C-E, end etc).
