### ISSUE TITLE
Make wheel packages.

### ISSUE THREAD

**Issue by jonathanslenders** [jonathanslenders/python-prompt-toolkit#92]
(We don't publish wheels on Pypi yet.)

**Comment by stonebig** [comment]
Would it be possible for you to add the necessary pieces for it ? 
(so it becomes just a matter of doing python setup.py sdist bdist_wheel on the pc or mac that wants it)

**Comment by jonathanslenders** [comment]
Done. :)

**Comment by stonebig** [comment]
thanks.
